package io.github.turbopro.ism.resource.print;
import io.github.turbopro.ism.common.infrastructure.tenant.TenantScopedMapper;import org.apache.ibatis.annotations.*;import java.time.LocalDateTime;import java.util.*;
@Mapper public interface PrintMapper extends TenantScopedMapper{
 @Select("SELECT id,template_code,template_name,business_type,draft_html,variable_schema,page_config,status,current_version,version FROM prt_template WHERE tenant_id=#{tenantId} ORDER BY template_code")List<PrintModels.TemplateRow>templates(long tenantId);
 @Select("SELECT id,template_code,template_name,business_type,draft_html,variable_schema,page_config,status,current_version,version FROM prt_template WHERE tenant_id=#{tenantId} AND id=#{id}")PrintModels.TemplateRow template(long tenantId,long id);
 @Insert("INSERT INTO prt_template(id,tenant_id,template_code,template_name,business_type,draft_html,variable_schema,page_config,status) VALUES(#{id},#{tenantId},#{code},#{name},#{businessType},#{html},CAST(#{schema} AS JSON),CAST(#{page} AS JSON),'DRAFT')")int insert(long tenantId,long id,String code,String name,String businessType,String html,String schema,String page);
 @Update("UPDATE prt_template SET template_name=#{name},business_type=#{businessType},draft_html=#{html},variable_schema=CAST(#{schema} AS JSON),page_config=CAST(#{page} AS JSON),status='DRAFT',version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND version=#{version}")int update(long tenantId,long id,String name,String businessType,String html,String schema,String page,int version);
 @Insert("INSERT INTO prt_template_version(id,tenant_id,template_id,version_no,html_content,variable_schema,page_config,published_by,published_at) SELECT #{versionId},#{tenantId},id,current_version+1,draft_html,variable_schema,page_config,#{userId},#{now} FROM prt_template WHERE tenant_id=#{tenantId} AND id=#{id} AND version=#{version}")int insertVersion(long tenantId,long id,long versionId,long userId,int version,LocalDateTime now);
 @Update("UPDATE prt_template SET current_version=current_version+1,status='PUBLISHED',version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND version=#{version}")int publish(long tenantId,long id,int version);
 @Select("SELECT id,template_id,version_no,html_content,variable_schema,page_config FROM prt_template_version WHERE tenant_id=#{tenantId} AND template_id=#{templateId} ORDER BY version_no DESC LIMIT 1")PrintModels.VersionRow currentVersion(long tenantId,long templateId);
 @Insert("INSERT INTO prt_print_job(id,tenant_id,task_id,template_version_id,requester_id,business_type,business_id,render_payload) VALUES(#{id},#{tenantId},#{taskId},#{versionId},#{userId},#{businessType},#{businessId},CAST(#{payload} AS JSON))")int insertJob(long tenantId,long id,long taskId,long versionId,long userId,String businessType,Long businessId,String payload);
}
