package io.github.turbopro.ism.resource.print;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import io.github.turbopro.ism.common.api.error.*;import io.github.turbopro.ism.common.infrastructure.tenant.TenantContext;import io.github.turbopro.ism.operation.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import java.util.regex.*;
@Service public class PrintService{private static final Pattern VAR=Pattern.compile("\\{\\{([a-zA-Z][a-zA-Z0-9_.-]{0,63})}}");private static final Pattern UNSAFE=Pattern.compile("(?i)<\\s*script|on[a-z]+\\s*=|javascript:");private final PrintMapper mapper;private final OperationIdGenerator ids;private final AsyncTaskService tasks;private final ObjectMapper json;public PrintService(PrintMapper mapper,OperationIdGenerator ids,AsyncTaskService tasks,ObjectMapper json){this.mapper=mapper;this.ids=ids;this.tasks=tasks;this.json=json;}
 public List<PrintModels.TemplateView>templates(){return mapper.templates(tenant()).stream().map(this::view).toList();}
 @Transactional public PrintModels.TemplateView create(PrintModels.SaveTemplate c){validate(c);long id=ids.nextId();try{mapper.insert(tenant(),id,c.code(),c.name(),c.businessType(),c.html(),write(c.requiredVariables()),write(Map.of("pageSize",c.pageSize(),"orientation",c.orientation())));}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT);}return view(require(id));}
 @Transactional public PrintModels.TemplateView update(long id,PrintModels.SaveTemplate c){validate(c);if(mapper.update(tenant(),id,c.name(),c.businessType(),c.html(),write(c.requiredVariables()),write(Map.of("pageSize",c.pageSize(),"orientation",c.orientation())),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);return view(require(id));}
 @Transactional public PrintModels.TemplateView publish(long id,int version){var i=TenantContext.require();long versionId=ids.nextId();if(mapper.insertVersion(i.tenantId(),id,versionId,i.actorId(),version,LocalDateTime.now(ZoneOffset.UTC))!=1||mapper.publish(i.tenantId(),id,version)!=1)throw new ApiException(CommonErrorCode.CONFLICT);return view(require(id));}
 public PrintModels.Preview preview(long id,PrintModels.RenderRequest r){var t=require(id);validateVariables(readSet(t.variableSchema()),r.variables());Map<String,String> page=readMap(t.pageConfig());return new PrintModels.Preview(t.templateName(),render(t.draftHtml(),r.variables()),page.get("pageSize"),page.get("orientation"));}
 @Transactional public PrintModels.PrintJob print(long id,PrintModels.RenderRequest r){var i=TenantContext.require();var version=mapper.currentVersion(i.tenantId(),id);if(version==null)throw new ApiException(CommonErrorCode.CONFLICT,"打印模板尚未发布");validateVariables(readSet(version.variableSchema()),r.variables());Long businessId=r.businessId()==null?null:parseId(r.businessId());long taskId=tasks.submit("PRINT_DOCUMENT",Map.of("templateVersionId",Long.toString(version.id()),"variables",r.variables()),10),jobId=ids.nextId();mapper.insertJob(i.tenantId(),jobId,taskId,version.id(),i.actorId(),r.businessType(),businessId,write(r.variables()));return new PrintModels.PrintJob(Long.toString(jobId),Long.toString(taskId),version.versionNo());}
 private void validate(PrintModels.SaveTemplate c){if(UNSAFE.matcher(c.html()).find())throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"模板包含不安全内容");Set<String> used=new HashSet<>();Matcher m=VAR.matcher(c.html());while(m.find())used.add(m.group(1));if(!used.equals(c.requiredVariables()))throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"模板变量与声明不一致");}
 private void validateVariables(Set<String> required,Map<String,String> values){if(!values.keySet().containsAll(required))throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"打印变量不完整");}private String render(String html,Map<String,String> values){Matcher m=VAR.matcher(html);StringBuffer b=new StringBuffer();while(m.find())m.appendReplacement(b,Matcher.quoteReplacement(escape(values.get(m.group(1)))));m.appendTail(b);return b.toString();}private String escape(String s){if(s==null)return "";return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace("\"","&quot;");}
 private PrintModels.TemplateRow require(long id){var t=mapper.template(tenant(),id);if(t==null)throw new ApiException(CommonErrorCode.NOT_FOUND);return t;}private PrintModels.TemplateView view(PrintModels.TemplateRow t){Map<String,String>p=readMap(t.pageConfig());return new PrintModels.TemplateView(Long.toString(t.id()),t.templateCode(),t.templateName(),t.businessType(),t.draftHtml(),readSet(t.variableSchema()),p.get("pageSize"),p.get("orientation"),t.status(),t.currentVersion(),t.version());}
 private String write(Object o){try{return json.writeValueAsString(o);}catch(Exception e){throw new IllegalStateException(e);}}private Set<String>readSet(String s){try{return json.readValue(s,new TypeReference<Set<String>>(){});}catch(Exception e){throw new IllegalStateException(e);}}private Map<String,String>readMap(String s){try{return json.readValue(s,new TypeReference<Map<String,String>>(){});}catch(Exception e){throw new IllegalStateException(e);}}private long parseId(String s){try{return Long.parseLong(s);}catch(Exception e){throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"业务 ID 无效");}}private long tenant(){return TenantContext.require().tenantId();}}
