package io.github.turbopro.ism.resource.supplier;
import io.github.turbopro.ism.common.infrastructure.tenant.TenantScopedMapper;import org.apache.ibatis.annotations.*;import java.time.LocalDate;import java.util.*;
@Mapper public interface SupplierResourceMapper extends TenantScopedMapper{
 String PS="<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND x.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'PROJECT_SET'\"> AND x.project_id IN <foreach collection='projectIds' item='p' open='(' separator=',' close=')'>#{p}</foreach></when><when test=\"scopeType == 'CREATED'\"> AND x.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>";
 String PF="<if test='keyword != null'> AND (x.person_code LIKE #{keyword} ESCAPE '=' OR x.person_name LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')</if><if test='status != null'> AND x.status=#{status}</if>";
 String AF="<if test='keyword != null'> AND (x.asset_code LIKE #{keyword} ESCAPE '=' OR x.asset_name LIKE #{keyword} ESCAPE '=' OR x.plate_no LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')</if><if test='status != null'> AND x.status=#{status}</if>";
 @Select("SELECT organization_id FROM sup_supplier WHERE tenant_id=#{tenantId} AND id=#{supplierId} AND deleted=0 AND status='ACTIVE' FOR UPDATE")Long supplierOrg(long tenantId,long supplierId);
 @Select("SELECT COUNT(*) FROM prj_project WHERE tenant_id=#{tenantId} AND id=#{projectId} AND supplier_id=#{supplierId} AND status IN ('PLANNED','ACTIVE','SUSPENDED')")int projectMatches(long tenantId,long projectId,long supplierId);
 @Select("<script>SELECT COUNT(*) FROM res_supplier_person x JOIN sup_supplier s ON s.id=x.supplier_id WHERE x.tenant_id=#{tenantId}"+PS+PF+"</script>")long countPersons(long tenantId,String keyword,String status,String scopeType,Set<Long> organizationIds,Set<Long> projectIds,long actorId);
 @Select("<script>SELECT x.id,x.organization_id,x.supplier_id,x.project_id,s.supplier_code,s.supplier_name,p.project_code,x.person_code,x.person_name,x.id_type,x.id_number_masked,x.mobile,x.job_title,x.trade_type,x.special_work_type,x.entry_date,x.exit_date,x.status,x.status_reason,x.created_by,x.version,x.updated_at FROM res_supplier_person x JOIN sup_supplier s ON s.id=x.supplier_id AND s.tenant_id=x.tenant_id LEFT JOIN prj_project p ON p.id=x.project_id AND p.tenant_id=x.tenant_id WHERE x.tenant_id=#{tenantId}"+PS+PF+" ORDER BY x.updated_at DESC LIMIT #{size} OFFSET #{offset}</script>")List<SupplierResourceModels.PersonRow> persons(long tenantId,String keyword,String status,String scopeType,Set<Long> organizationIds,Set<Long> projectIds,long actorId,int offset,int size);
 @Select("SELECT x.id,x.organization_id,x.supplier_id,x.project_id,s.supplier_code,s.supplier_name,p.project_code,x.person_code,x.person_name,x.id_type,x.id_number_masked,x.mobile,x.job_title,x.trade_type,x.special_work_type,x.entry_date,x.exit_date,x.status,x.status_reason,x.created_by,x.version,x.updated_at FROM res_supplier_person x JOIN sup_supplier s ON s.id=x.supplier_id AND s.tenant_id=x.tenant_id LEFT JOIN prj_project p ON p.id=x.project_id AND p.tenant_id=x.tenant_id WHERE x.tenant_id=#{tenantId} AND x.id=#{id}")SupplierResourceModels.PersonRow person(long tenantId,long id);
 @Insert("INSERT INTO res_supplier_person(id,tenant_id,organization_id,supplier_id,project_id,person_code,person_name,id_type,id_number_hash,id_number_masked,mobile,job_title,trade_type,special_work_type,entry_date,created_by,updated_by) VALUES(#{id},#{tenantId},#{org},#{supplierId},#{projectId},#{code},#{name},#{idType},#{idHash},#{idMasked},#{mobile},#{jobTitle},#{tradeType},#{specialWorkType},#{entryDate},#{actorId},#{actorId})")int insertPerson(long id,long tenantId,long actorId,long org,long supplierId,Long projectId,String code,String name,String idType,String idHash,String idMasked,String mobile,String jobTitle,String tradeType,String specialWorkType,LocalDate entryDate);
 @Update("UPDATE res_supplier_person SET person_name=#{name},project_id=#{projectId},mobile=#{mobile},job_title=#{jobTitle},trade_type=#{tradeType},entry_date=#{entryDate},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status IN ('PENDING','ACTIVE','SUSPENDED') AND version=#{version}")int updatePerson(long tenantId,long actorId,long id,Long projectId,String name,String mobile,String jobTitle,String tradeType,LocalDate entryDate,int version);
 @Select("SELECT COUNT(*) FROM saf_person_credential WHERE tenant_id=#{tenantId} AND person_id=#{personId} AND credential_kind='TRAINING' AND status='VERIFIED' AND passed=1 AND effective_date<=CURRENT_DATE AND expiry_date>=CURRENT_DATE")int validTraining(long tenantId,long personId);
 @Select("SELECT COUNT(*) FROM saf_person_credential WHERE tenant_id=#{tenantId} AND person_id=#{personId} AND credential_kind='SPECIAL_WORK' AND work_type=#{workType} AND status='VERIFIED' AND effective_date<=CURRENT_DATE AND expiry_date>=CURRENT_DATE")int validSpecialWork(long tenantId,long personId,String workType);
 @Update("UPDATE res_supplier_person SET status=#{status},status_reason=#{reason},exit_date=CASE WHEN #{status}='EXITED' THEN CURRENT_DATE ELSE exit_date END,updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND version=#{version}")int personStatus(long tenantId,long actorId,long id,String status,String reason,int version);
 @Select("<script>SELECT COUNT(*) FROM res_supplier_asset x JOIN sup_supplier s ON s.id=x.supplier_id WHERE x.tenant_id=#{tenantId}"+PS+AF+"</script>")long countAssets(long tenantId,String keyword,String status,String scopeType,Set<Long> organizationIds,Set<Long> projectIds,long actorId);
 @Select("<script>SELECT x.id,x.organization_id,x.supplier_id,x.project_id,s.supplier_code,s.supplier_name,p.project_code,x.asset_code,x.asset_name,x.asset_type,x.plate_no,x.serial_no,x.brand,x.model,x.inspection_expiry_date,x.file_id,x.status,x.status_reason,x.created_by,x.version,x.updated_at FROM res_supplier_asset x JOIN sup_supplier s ON s.id=x.supplier_id LEFT JOIN prj_project p ON p.id=x.project_id WHERE x.tenant_id=#{tenantId}"+PS+AF+" ORDER BY x.updated_at DESC LIMIT #{size} OFFSET #{offset}</script>")List<SupplierResourceModels.AssetRow> assets(long tenantId,String keyword,String status,String scopeType,Set<Long> organizationIds,Set<Long> projectIds,long actorId,int offset,int size);
 @Select("SELECT x.id,x.organization_id,x.supplier_id,x.project_id,s.supplier_code,s.supplier_name,p.project_code,x.asset_code,x.asset_name,x.asset_type,x.plate_no,x.serial_no,x.brand,x.model,x.inspection_expiry_date,x.file_id,x.status,x.status_reason,x.created_by,x.version,x.updated_at FROM res_supplier_asset x JOIN sup_supplier s ON s.id=x.supplier_id LEFT JOIN prj_project p ON p.id=x.project_id WHERE x.tenant_id=#{tenantId} AND x.id=#{id}")SupplierResourceModels.AssetRow asset(long tenantId,long id);
 @Insert("INSERT INTO res_supplier_asset(id,tenant_id,organization_id,supplier_id,project_id,asset_code,asset_name,asset_type,plate_no,serial_no,brand,model,inspection_expiry_date,file_id,created_by,updated_by) VALUES(#{id},#{tenantId},#{org},#{supplierId},#{projectId},#{code},#{name},#{type},NULLIF(#{plateNo},''),#{serialNo},#{brand},#{model},#{expiry},#{fileId},#{actorId},#{actorId})")int insertAsset(long id,long tenantId,long actorId,long org,long supplierId,Long projectId,String code,String name,String type,String plateNo,String serialNo,String brand,String model,LocalDate expiry,Long fileId);
 @Update("UPDATE res_supplier_asset SET asset_name=#{name},project_id=#{projectId},plate_no=NULLIF(#{plateNo},''),serial_no=#{serialNo},brand=#{brand},model=#{model},inspection_expiry_date=#{expiry},file_id=#{fileId},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status IN ('PENDING','AVAILABLE','MAINTENANCE') AND version=#{version}")int updateAsset(long tenantId,long actorId,long id,Long projectId,String name,String plateNo,String serialNo,String brand,String model,LocalDate expiry,Long fileId,int version);
 @Update("UPDATE res_supplier_asset SET status=#{status},status_reason=#{reason},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND version=#{version}")int assetStatus(long tenantId,long actorId,long id,String status,String reason,int version);
}
