package io.github.turbopro.ism.resource.supplier;
import io.github.turbopro.ism.common.api.error.*;import io.github.turbopro.ism.common.infrastructure.authorization.*;import io.github.turbopro.ism.common.infrastructure.tenant.TenantContext;import io.github.turbopro.ism.operation.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.util.*;
@Service public class SupplierResourceService{
 private final SupplierResourceMapper mapper;private final OperationIdGenerator ids;private final AuditService audit;private final io.github.turbopro.ism.supplier.SupplierReferenceService suppliers;
 public SupplierResourceService(SupplierResourceMapper m,OperationIdGenerator i,AuditService a,io.github.turbopro.ism.supplier.SupplierReferenceService s){mapper=m;ids=i;audit=a;suppliers=s;}
 public SupplierResourceModels.PersonPage persons(String keyword,String status,int page,int size){var i=TenantContext.require();var s=scope("resource:person");String k=like(keyword),st=parsePersonStatus(status);return new SupplierResourceModels.PersonPage(mapper.countPersons(i.tenantId(),k,st,s.type().name(),s.organizationIds(),s.projectIds(),i.actorId()),page,size,mapper.persons(i.tenantId(),k,st,s.type().name(),s.organizationIds(),s.projectIds(),i.actorId(),page*size,size).stream().map(this::personView).toList());}
 @Transactional public SupplierResourceModels.PersonView createPerson(SupplierResourceModels.SavePerson c){if(c.version()!=0)throw val("新建人员 version 必须为 0");var i=TenantContext.require();long supplier=id(c.supplierId(),"供应商 ID 无效");var reference=suppliers.activeForNewBusiness(supplier);Long org=reference==null?null:reference.organizationId();if(org==null)throw val("只有有效供应商可以登记人员");Long project=project(c.projectId(),supplier);require("resource:person",org,project,i.actorId());long pid=ids.nextId();String normalized=c.idNumber().trim().toUpperCase(Locale.ROOT);try{mapper.insertPerson(pid,i.tenantId(),i.actorId(),org,supplier,project,c.code(),c.name().trim(),c.idType().name(),sha256(normalized),maskId(normalized),blank(c.mobile()),blank(c.jobTitle()),blank(c.tradeType()),c.specialWorkType()==null?null:c.specialWorkType().name(),c.entryDate());}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"人员编码或证件已存在");}audit("PERSON_CREATE","PERSON",pid);return personView(mapper.person(i.tenantId(),pid));}
 @Transactional public SupplierResourceModels.PersonView updatePerson(long id,SupplierResourceModels.SavePerson c){var before=requirePerson(id);if(!before.personCode().equals(c.code())||before.supplierId()!=id(c.supplierId(),"供应商 ID 无效")||!before.idType().equals(c.idType().name())||!Objects.equals(before.specialWorkType(),c.specialWorkType()==null?null:c.specialWorkType().name()))throw val("人员编码、供应商、证件类型和特种作业类型不可修改");Long project=project(c.projectId(),before.supplierId());var i=TenantContext.require();if(mapper.updatePerson(i.tenantId(),i.actorId(),id,project,c.name().trim(),blank(c.mobile()),blank(c.jobTitle()),blank(c.tradeType()),c.entryDate(),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);return personView(mapper.person(i.tenantId(),id));}
 @Transactional public SupplierResourceModels.PersonView personStatus(long id,SupplierResourceModels.PersonStatusCommand c){var b=requirePerson(id);var from=SupplierResourceModels.PersonStatus.valueOf(b.status());if(!personMove(from,c.status()))throw val("人员状态跳转无效");if((c.status()==SupplierResourceModels.PersonStatus.SUSPENDED||c.status()==SupplierResourceModels.PersonStatus.EXITED)&&(c.reason()==null||c.reason().isBlank()))throw val("停用或离场必须填写原因");var i=TenantContext.require();if(c.status()==SupplierResourceModels.PersonStatus.ACTIVE){if(suppliers.activeForNewBusiness(b.supplierId())==null)throw val("供应商无效或存在生效限制，不能启用人员");if(mapper.validTraining(i.tenantId(),id)==0)throw val("缺少有效且已审核的安全培训记录");if(b.specialWorkType()!=null&&mapper.validSpecialWork(i.tenantId(),id,b.specialWorkType())==0)throw val("缺少对应且有效的特种作业凭证");}if(mapper.personStatus(i.tenantId(),i.actorId(),id,c.status().name(),blank(c.reason()),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);return personView(mapper.person(i.tenantId(),id));}
 public SupplierResourceModels.AssetPage assets(String keyword,String status,int page,int size){var i=TenantContext.require();var s=scope("resource:asset");String k=like(keyword),st=parseAssetStatus(status);return new SupplierResourceModels.AssetPage(mapper.countAssets(i.tenantId(),k,st,s.type().name(),s.organizationIds(),s.projectIds(),i.actorId()),page,size,mapper.assets(i.tenantId(),k,st,s.type().name(),s.organizationIds(),s.projectIds(),i.actorId(),page*size,size).stream().map(this::assetView).toList());}
 @Transactional public SupplierResourceModels.AssetView createAsset(SupplierResourceModels.SaveAsset c){if(c.version()!=0)throw val("新建设备 version 必须为 0");validateAsset(c);var i=TenantContext.require();long supplier=id(c.supplierId(),"供应商 ID 无效");var reference=suppliers.activeForNewBusiness(supplier);Long org=reference==null?null:reference.organizationId();if(org==null)throw val("只有有效供应商可以登记车辆设备");Long project=project(c.projectId(),supplier);require("resource:asset",org,project,i.actorId());long aid=ids.nextId();try{mapper.insertAsset(aid,i.tenantId(),i.actorId(),org,supplier,project,c.code(),c.name().trim(),c.type().name(),blank(c.plateNo()),blank(c.serialNo()),blank(c.brand()),blank(c.model()),c.inspectionExpiryDate(),optionalId(c.fileId(),"文件 ID 无效"));}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"资产编码或车牌号已存在");}audit("ASSET_CREATE","ASSET",aid);return assetView(mapper.asset(i.tenantId(),aid));}
 @Transactional public SupplierResourceModels.AssetView updateAsset(long id,SupplierResourceModels.SaveAsset c){var b=requireAsset(id);if(!b.assetCode().equals(c.code())||b.supplierId()!=id(c.supplierId(),"供应商 ID 无效")||!b.assetType().equals(c.type().name()))throw val("资产编码、供应商和资产类型不可修改");validateAsset(c);Long project=project(c.projectId(),b.supplierId());var i=TenantContext.require();if(mapper.updateAsset(i.tenantId(),i.actorId(),id,project,c.name().trim(),blank(c.plateNo()),blank(c.serialNo()),blank(c.brand()),blank(c.model()),c.inspectionExpiryDate(),optionalId(c.fileId(),"文件 ID 无效"),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);return assetView(mapper.asset(i.tenantId(),id));}
 @Transactional public SupplierResourceModels.AssetView assetStatus(long id,SupplierResourceModels.AssetStatusCommand c){var b=requireAsset(id);if(b.handedOverAt()!=null)throw val("已交接离场资产不能变更使用状态");var from=SupplierResourceModels.AssetStatus.valueOf(b.status());if(!assetMove(from,c.status()))throw val("资产状态跳转无效");if((c.status()==SupplierResourceModels.AssetStatus.MAINTENANCE||c.status()==SupplierResourceModels.AssetStatus.RETIRED)&&(c.reason()==null||c.reason().isBlank()))throw val("维修或退役必须填写原因");if(c.status()==SupplierResourceModels.AssetStatus.IN_USE&&suppliers.activeForNewBusiness(b.supplierId())==null)throw val("供应商无效或存在生效限制，不能投入使用");var i=TenantContext.require();if(mapper.assetStatus(i.tenantId(),i.actorId(),id,c.status().name(),blank(c.reason()),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);return assetView(mapper.asset(i.tenantId(),id));}
 @Transactional public SupplierResourceModels.AssetView handoverAsset(long id,SupplierResourceModels.AssetHandoverCommand c){var b=requireAsset(id);if(b.status().equals("IN_USE"))throw val("使用中的资产须先结束使用");if(b.handedOverAt()!=null)throw val("资产已完成交接离场");var i=TenantContext.require();if(mapper.handoverAsset(i.tenantId(),i.actorId(),id,c.recipient().trim(),c.note().trim(),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);audit.append(new AuditService.AuditCommand("ASSET_HANDOVER","ASSET",id,null,Map.of(),Map.of("recipient",c.recipient().trim(),"note",c.note().trim()),null,null));return assetView(mapper.asset(i.tenantId(),id));}
 private SupplierResourceModels.PersonRow requirePerson(long id){var i=TenantContext.require();var r=mapper.person(i.tenantId(),id);if(r==null||!scope("resource:person").allows(new DataTarget(r.organizationId(),r.projectId(),null,r.createdBy()),i.actorId()))throw new ApiException(CommonErrorCode.NOT_FOUND);return r;}
 private SupplierResourceModels.AssetRow requireAsset(long id){var i=TenantContext.require();var r=mapper.asset(i.tenantId(),id);if(r==null||!scope("resource:asset").allows(new DataTarget(r.organizationId(),r.projectId(),null,r.createdBy()),i.actorId()))throw new ApiException(CommonErrorCode.NOT_FOUND);return r;}
 private DataScope scope(String r){return AuthorizationContext.require().dataScope(r);}private void require(String r,long org,Long project,long actor){if(!scope(r).allows(new DataTarget(org,project,null,actor),actor))throw new ApiException(CommonErrorCode.FORBIDDEN);}
 private Long project(String value,long supplier){Long p=optionalId(value,"项目 ID 无效");if(p!=null&&mapper.projectMatches(TenantContext.require().tenantId(),p,supplier)!=1)throw val("项目不存在、不可用或不属于该供应商");return p;}
 private void validateAsset(SupplierResourceModels.SaveAsset c){if(c.type()==SupplierResourceModels.AssetType.VEHICLE&&(c.plateNo()==null||c.plateNo().isBlank()))throw val("车辆必须填写车牌号");if(c.type()!=SupplierResourceModels.AssetType.VEHICLE&&c.serialNo()!=null&&c.serialNo().length()>100)throw val("出厂编号过长");}
 private boolean personMove(SupplierResourceModels.PersonStatus f,SupplierResourceModels.PersonStatus t){return f!=t&&switch(f){case PENDING->t==SupplierResourceModels.PersonStatus.ACTIVE||t==SupplierResourceModels.PersonStatus.EXITED;case ACTIVE->t==SupplierResourceModels.PersonStatus.SUSPENDED||t==SupplierResourceModels.PersonStatus.EXITED;case SUSPENDED->t==SupplierResourceModels.PersonStatus.ACTIVE||t==SupplierResourceModels.PersonStatus.EXITED;case EXITED->false;};}
 private boolean assetMove(SupplierResourceModels.AssetStatus f,SupplierResourceModels.AssetStatus t){return f!=t&&switch(f){case PENDING->t==SupplierResourceModels.AssetStatus.AVAILABLE||t==SupplierResourceModels.AssetStatus.RETIRED;case AVAILABLE->t==SupplierResourceModels.AssetStatus.IN_USE||t==SupplierResourceModels.AssetStatus.MAINTENANCE||t==SupplierResourceModels.AssetStatus.RETIRED;case IN_USE->t==SupplierResourceModels.AssetStatus.AVAILABLE||t==SupplierResourceModels.AssetStatus.MAINTENANCE;case MAINTENANCE->t==SupplierResourceModels.AssetStatus.AVAILABLE||t==SupplierResourceModels.AssetStatus.RETIRED;case RETIRED->false;};}
 private String parsePersonStatus(String s){if(s==null||s.isBlank())return null;try{return SupplierResourceModels.PersonStatus.valueOf(s).name();}catch(Exception e){throw val("人员状态无效");}}private String parseAssetStatus(String s){if(s==null||s.isBlank())return null;try{return SupplierResourceModels.AssetStatus.valueOf(s).name();}catch(Exception e){throw val("资产状态无效");}}
 private String sha256(String s){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}private String maskId(String s){return s.length()<=4?"****":"*".repeat(Math.min(14,s.length()-4))+s.substring(s.length()-4);}
 private String like(String s){return s==null||s.isBlank()?null:"%"+s.trim().replace("=","==").replace("%","=%").replace("_","=_")+"%";}private long id(String s,String m){try{return Long.parseLong(s);}catch(Exception e){throw val(m);}}private Long optionalId(String s,String m){return s==null||s.isBlank()?null:id(s,m);}private String blank(String s){return s==null||s.isBlank()?null:s.trim();}private ApiException val(String m){return new ApiException(CommonErrorCode.VALIDATION_FAILED,m);}private void audit(String action,String type,long id){audit.append(new AuditService.AuditCommand(action,type,id,null,Map.of(),Map.of("created",true),null,null));}
 private SupplierResourceModels.PersonView personView(SupplierResourceModels.PersonRow r){return new SupplierResourceModels.PersonView(""+r.id(),""+r.organizationId(),""+r.supplierId(),r.projectId()==null?null:""+r.projectId(),r.supplierCode(),r.supplierName(),r.projectCode(),r.personCode(),r.personName(),SupplierResourceModels.IdType.valueOf(r.idType()),r.idNumberMasked(),r.mobile(),r.jobTitle(),r.tradeType(),r.specialWorkType()==null?null:SupplierResourceModels.SpecialWorkType.valueOf(r.specialWorkType()),r.entryDate(),r.exitDate(),SupplierResourceModels.PersonStatus.valueOf(r.status()),r.statusReason(),r.version(),r.updatedAt());}
 private SupplierResourceModels.AssetView assetView(SupplierResourceModels.AssetRow r){return new SupplierResourceModels.AssetView(""+r.id(),""+r.organizationId(),""+r.supplierId(),r.projectId()==null?null:""+r.projectId(),r.supplierCode(),r.supplierName(),r.projectCode(),r.assetCode(),r.assetName(),SupplierResourceModels.AssetType.valueOf(r.assetType()),r.plateNo(),r.serialNo(),r.brand(),r.model(),r.inspectionExpiryDate(),r.fileId()==null?null:""+r.fileId(),SupplierResourceModels.AssetStatus.valueOf(r.status()),r.statusReason(),r.version(),r.updatedAt(),r.handedOverAt(),r.handoverRecipient(),r.handoverNote());}
}
