package io.github.turbopro.ism.project;

import io.github.turbopro.ism.common.api.error.*;
import io.github.turbopro.ism.common.infrastructure.authorization.*;
import io.github.turbopro.ism.common.infrastructure.tenant.TenantContext;
import io.github.turbopro.ism.operation.*;
import io.github.turbopro.ism.supplier.SupplierReferenceService;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.*;

@Service
public class ProjectService {
    private final ProjectMapper mapper;private final OperationIdGenerator ids;private final AuditService audit;private final SupplierReferenceService suppliers;
    public ProjectService(ProjectMapper mapper,OperationIdGenerator ids,AuditService audit,SupplierReferenceService suppliers){this.mapper=mapper;this.ids=ids;this.audit=audit;this.suppliers=suppliers;}
    public ProjectModels.ContractPage contracts(String keyword,String status,int page,int size){var i=TenantContext.require();var scope=AuthorizationContext.require().dataScope("contract");String like=like(keyword),state=parseContractStatus(status);return new ProjectModels.ContractPage(mapper.countContracts(i.tenantId(),like,state,scope.type().name(),scope.organizationIds(),i.actorId()),page,size,mapper.contracts(i.tenantId(),like,state,scope.type().name(),scope.organizationIds(),i.actorId(),Math.multiplyExact(page,size),size));}
    public ProjectModels.ContractView contract(long id){return contractView(requireContract(id));}
    @Transactional public ProjectModels.ContractView createContract(ProjectModels.SaveContract c){if(c.version()!=0)throw validation("新建合同的 version 必须为 0");validateContract(c);var i=TenantContext.require();long supplier=id(c.supplierId(),"供应商 ID 无效");var reference=suppliers.activeForNewBusiness(supplier);if(reference==null)throw validation("只有有效且未列入黑名单的供应商可以签订合同");long org=reference.organizationId();requireScope("contract",org,i.actorId());long contract=ids.nextId();try{mapper.insertContract(contract,i.tenantId(),i.actorId(),org,supplier,c.contractNo(),c.name().trim(),c.type().name(),c.amount(),c.currency(),c.signedDate(),c.startDate(),c.endDate(),id(c.ownerId(),"负责人 ID 无效"),id(c.fileId(),"合同文件 ID 无效"));}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"合同编号已存在");}audit("CONTRACT_CREATE","CONTRACT",contract,null,"DRAFT",c.contractNo());return contractView(mapper.contract(i.tenantId(),contract));}
    @Transactional public ProjectModels.ContractView updateContract(long id,ProjectModels.SaveContract c){var before=requireContract(id);if(!before.contractNo().equals(c.contractNo())||before.supplierId()!=id(c.supplierId(),"供应商 ID 无效"))throw validation("合同编号和供应商不可修改");validateContract(c);var i=TenantContext.require();if(mapper.updateContract(i.tenantId(),i.actorId(),id,c.name().trim(),c.type().name(),c.amount(),c.currency(),c.signedDate(),c.startDate(),c.endDate(),id(c.ownerId(),"负责人 ID 无效"),id(c.fileId(),"合同文件 ID 无效"),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);return contractView(mapper.contract(i.tenantId(),id));}
    @Transactional public ProjectModels.ContractView changeContractStatus(long id,ProjectModels.ChangeContractStatus c){var before=requireContract(id);var from=ProjectModels.ContractStatus.valueOf(before.status());if(!contractTransition(from,c.status()))throw validation("不允许从 "+from+" 变更为 "+c.status());if(c.status()==ProjectModels.ContractStatus.TERMINATED&&(c.reason()==null||c.reason().isBlank()))throw validation("终止合同必须填写原因");if(c.status()==ProjectModels.ContractStatus.ACTIVE&&suppliers.activeForNewBusiness(before.supplierId())==null)throw validation("供应商无效或存在生效限制，不能激活合同");var i=TenantContext.require();if(mapper.changeContractStatus(i.tenantId(),i.actorId(),id,c.status().name(),blank(c.reason()),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);audit("CONTRACT_STATUS","CONTRACT",id,from.name(),c.status().name(),Objects.toString(c.reason(),""));return contractView(mapper.contract(i.tenantId(),id));}
    public ProjectModels.ProjectPage projects(String keyword,String status,int page,int size){var i=TenantContext.require();var scope=AuthorizationContext.require().dataScope("project");String like=like(keyword),state=parseProjectStatus(status);return new ProjectModels.ProjectPage(mapper.countProjects(i.tenantId(),like,state,scope.type().name(),scope.organizationIds(),scope.projectIds(),i.actorId()),page,size,mapper.projects(i.tenantId(),like,state,scope.type().name(),scope.organizationIds(),scope.projectIds(),i.actorId(),Math.multiplyExact(page,size),size));}
    public ProjectModels.ProjectView project(long id){return projectView(requireProject(id));}
    @Transactional public ProjectModels.ProjectView createProject(ProjectModels.SaveProject c){if(c.version()!=0)throw validation("新建项目的 version 必须为 0");validateProject(c);var i=TenantContext.require();long supplier=id(c.supplierId(),"供应商 ID 无效");var reference=suppliers.activeForNewBusiness(supplier);if(reference==null)throw validation("只有有效且未列入黑名单的供应商可以创建项目");long org=reference.organizationId();requireScope("project",org,i.actorId());Long contract=optionalId(c.contractId(),"合同 ID 无效");if(contract!=null&&!Objects.equals(mapper.activeContractSupplier(i.tenantId(),contract),supplier))throw validation("关联合同必须有效且属于同一供应商");long project=ids.nextId();try{mapper.insertProject(project,i.tenantId(),i.actorId(),org,supplier,contract,c.projectCode(),c.name().trim(),c.type().name(),blank(c.siteAddress()),c.plannedStartDate(),c.plannedEndDate(),id(c.managerId(),"项目负责人 ID 无效"),c.budgetAmount(),blank(c.currency()));}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"项目编码已存在");}audit("PROJECT_CREATE","PROJECT",project,null,"PLANNED",c.projectCode());return projectView(mapper.project(i.tenantId(),project));}
    @Transactional public ProjectModels.ProjectView updateProject(long id,ProjectModels.SaveProject c){var before=requireProject(id);if(!before.projectCode().equals(c.projectCode())||before.supplierId()!=id(c.supplierId(),"供应商 ID 无效")||!Objects.equals(before.contractId(),optionalId(c.contractId(),"合同 ID 无效")))throw validation("项目编码、供应商和关联合同不可修改");validateProject(c);var i=TenantContext.require();if(mapper.updateProject(i.tenantId(),i.actorId(),id,c.name().trim(),c.type().name(),blank(c.siteAddress()),c.plannedStartDate(),c.plannedEndDate(),id(c.managerId(),"项目负责人 ID 无效"),c.budgetAmount(),blank(c.currency()),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);return projectView(mapper.project(i.tenantId(),id));}
    @Transactional public ProjectModels.ProjectView changeProjectStatus(long id,ProjectModels.ChangeProjectStatus c){var before=requireProject(id);var from=ProjectModels.ProjectStatus.valueOf(before.status());if(!projectTransition(from,c.status()))throw validation("不允许从 "+from+" 变更为 "+c.status());if(Set.of(ProjectModels.ProjectStatus.SUSPENDED,ProjectModels.ProjectStatus.CANCELLED).contains(c.status())&&(c.reason()==null||c.reason().isBlank()))throw validation("暂停或取消项目必须填写原因");if(c.status()==ProjectModels.ProjectStatus.ACTIVE&&suppliers.activeForNewBusiness(before.supplierId())==null)throw validation("供应商无效或存在生效限制，不能开工或复工");var i=TenantContext.require();if(mapper.changeProjectStatus(i.tenantId(),i.actorId(),id,c.status().name(),blank(c.reason()),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);audit("PROJECT_STATUS","PROJECT",id,from.name(),c.status().name(),Objects.toString(c.reason(),""));return projectView(mapper.project(i.tenantId(),id));}
    private ProjectModels.ContractRow requireContract(long id){var i=TenantContext.require();var r=mapper.contract(i.tenantId(),id);if(r==null||!AuthorizationContext.require().dataScope("contract").allows(new DataTarget(r.organizationId(),null,r.ownerId(),r.createdBy()),i.actorId()))throw new ApiException(CommonErrorCode.NOT_FOUND);return r;}
    private ProjectModels.ProjectRow requireProject(long id){var i=TenantContext.require();var r=mapper.project(i.tenantId(),id);if(r==null||!AuthorizationContext.require().dataScope("project").allows(new DataTarget(r.organizationId(),r.id(),r.managerId(),r.createdBy()),i.actorId()))throw new ApiException(CommonErrorCode.NOT_FOUND);return r;}
    private void requireScope(String resource,long org,long actor){if(!AuthorizationContext.require().dataScope(resource).allows(new DataTarget(org,null,actor,actor),actor))throw new ApiException(CommonErrorCode.FORBIDDEN);}
    private void validateContract(ProjectModels.SaveContract c){if(c.startDate().isAfter(c.endDate()))throw validation("合同开始日期不能晚于结束日期");if(c.signedDate()!=null&&c.signedDate().isAfter(LocalDate.now()))throw validation("签订日期不能晚于今天");}
    private void validateProject(ProjectModels.SaveProject c){if(c.plannedStartDate().isAfter(c.plannedEndDate()))throw validation("计划开始日期不能晚于计划结束日期");if(c.budgetAmount()!=null&&(c.currency()==null||c.currency().isBlank()))throw validation("填写预算金额时必须填写币种");}
    private boolean contractTransition(ProjectModels.ContractStatus f,ProjectModels.ContractStatus t){return f!=t&&switch(f){case DRAFT->t==ProjectModels.ContractStatus.ACTIVE||t==ProjectModels.ContractStatus.TERMINATED;case ACTIVE->t==ProjectModels.ContractStatus.COMPLETED||t==ProjectModels.ContractStatus.TERMINATED||t==ProjectModels.ContractStatus.EXPIRED;default->false;};}
    private boolean projectTransition(ProjectModels.ProjectStatus f,ProjectModels.ProjectStatus t){return f!=t&&switch(f){case PLANNED->t==ProjectModels.ProjectStatus.ACTIVE||t==ProjectModels.ProjectStatus.CANCELLED;case ACTIVE->t==ProjectModels.ProjectStatus.SUSPENDED||t==ProjectModels.ProjectStatus.COMPLETED||t==ProjectModels.ProjectStatus.CANCELLED;case SUSPENDED->t==ProjectModels.ProjectStatus.ACTIVE||t==ProjectModels.ProjectStatus.CANCELLED;default->false;};}
    private String parseContractStatus(String s){if(s==null||s.isBlank())return null;try{return ProjectModels.ContractStatus.valueOf(s).name();}catch(Exception e){throw validation("合同状态无效");}}
    private String parseProjectStatus(String s){if(s==null||s.isBlank())return null;try{return ProjectModels.ProjectStatus.valueOf(s).name();}catch(Exception e){throw validation("项目状态无效");}}
    private String like(String s){return s==null||s.isBlank()?null:"%"+s.trim().replace("=","==").replace("%","=%").replace("_","=_")+"%";}
    private long id(String s,String message){try{return Long.parseLong(s);}catch(Exception e){throw validation(message);}}
    private Long optionalId(String s,String message){return s==null||s.isBlank()?null:id(s,message);}
    private String blank(String s){return s==null||s.isBlank()?null:s.trim();}
    private ApiException validation(String m){return new ApiException(CommonErrorCode.VALIDATION_FAILED,m);}
    private void audit(String action,String type,long id,String from,String to,String note){audit.append(new AuditService.AuditCommand(action,type,id,null,from==null?Map.of():Map.of("status",from),Map.of("status",to,"note",note),null,null));}
    private ProjectModels.ContractView contractView(ProjectModels.ContractRow r){return new ProjectModels.ContractView(Long.toString(r.id()),Long.toString(r.organizationId()),Long.toString(r.supplierId()),r.supplierCode(),r.supplierName(),r.contractNo(),r.contractName(),ProjectModels.ContractType.valueOf(r.contractType()),r.amount(),r.currency(),r.signedDate(),r.startDate(),r.endDate(),Long.toString(r.ownerId()),Long.toString(r.fileId()),ProjectModels.ContractStatus.valueOf(r.status()),r.terminationReason(),r.version(),r.createdAt(),r.updatedAt());}
    private ProjectModels.ProjectView projectView(ProjectModels.ProjectRow r){return new ProjectModels.ProjectView(Long.toString(r.id()),Long.toString(r.organizationId()),Long.toString(r.supplierId()),r.supplierCode(),r.supplierName(),r.contractId()==null?null:Long.toString(r.contractId()),r.contractNo(),r.projectCode(),r.projectName(),ProjectModels.ProjectType.valueOf(r.projectType()),r.siteAddress(),r.plannedStartDate(),r.plannedEndDate(),r.actualStartDate(),r.actualEndDate(),Long.toString(r.managerId()),r.budgetAmount(),r.currency(),ProjectModels.ProjectStatus.valueOf(r.status()),r.statusReason(),r.version(),r.createdAt(),r.updatedAt());}
}
