package io.github.turbopro.ism.project;

import io.github.turbopro.ism.common.infrastructure.tenant.TenantScopedMapper;
import org.apache.ibatis.annotations.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.*;

@Mapper
public interface ProjectMapper extends TenantScopedMapper {
    @Select("SELECT id FROM prj_contract WHERE tenant_id=#{tenantId} AND supplier_id=#{supplierId} AND status IN ('DRAFT','ACTIVE') FOR UPDATE")
    List<Long> openContracts(long tenantId,long supplierId);
    @Select("SELECT id FROM prj_project WHERE tenant_id=#{tenantId} AND supplier_id=#{supplierId} AND status IN ('PLANNED','ACTIVE','SUSPENDED') FOR UPDATE")
    List<Long> openProjects(long tenantId,long supplierId);
    String CONTRACT_SCOPE="<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND c.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'OWNED'\"> AND c.owner_id=#{actorId}</when><when test=\"scopeType == 'CREATED'\"> AND c.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>";
    String PROJECT_SCOPE="<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND p.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'PROJECT_SET'\"> AND p.id IN <foreach collection='projectIds' item='x' open='(' separator=',' close=')'>#{x}</foreach></when><when test=\"scopeType == 'OWNED'\"> AND p.manager_id=#{actorId}</when><when test=\"scopeType == 'CREATED'\"> AND p.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>";
    String CONTRACT_FILTER="<if test='keyword != null and keyword != &quot;&quot;'> AND (c.contract_no LIKE #{keyword} ESCAPE '=' OR c.contract_name LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')</if><if test='status != null and status != &quot;&quot;'> AND c.status=#{status}</if>";
    String PROJECT_FILTER="<if test='keyword != null and keyword != &quot;&quot;'> AND (p.project_code LIKE #{keyword} ESCAPE '=' OR p.project_name LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')</if><if test='status != null and status != &quot;&quot;'> AND p.status=#{status}</if>";
    @Select("<script>SELECT COUNT(*) FROM prj_contract c JOIN sup_supplier s ON s.id=c.supplier_id WHERE c.tenant_id=#{tenantId}"+CONTRACT_SCOPE+CONTRACT_FILTER+"</script>") long countContracts(long tenantId,String keyword,String status,String scopeType,Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT c.id,c.organization_id,c.supplier_id,s.supplier_code,s.supplier_name,c.contract_no,c.contract_name name,c.contract_type type,c.amount,c.currency,c.start_date,c.end_date,c.status,c.version,c.updated_at FROM prj_contract c JOIN sup_supplier s ON s.id=c.supplier_id WHERE c.tenant_id=#{tenantId}"+CONTRACT_SCOPE+CONTRACT_FILTER+" ORDER BY c.updated_at DESC,c.id DESC LIMIT #{size} OFFSET #{offset}</script>") List<ProjectModels.ContractSummary> contracts(long tenantId,String keyword,String status,String scopeType,Set<Long> organizationIds,long actorId,int offset,int size);
    @Select("SELECT c.id,c.organization_id,c.supplier_id,s.supplier_code,s.supplier_name,c.contract_no,c.contract_name,c.contract_type,c.amount,c.currency,c.signed_date,c.start_date,c.end_date,c.owner_id,c.file_id,c.status,c.termination_reason,c.created_by,c.version,c.created_at,c.updated_at FROM prj_contract c JOIN sup_supplier s ON s.id=c.supplier_id WHERE c.tenant_id=#{tenantId} AND c.id=#{id}") ProjectModels.ContractRow contract(long tenantId,long id);
    @Select("SELECT organization_id FROM sup_supplier WHERE tenant_id=#{tenantId} AND id=#{supplierId} AND deleted=0 AND status='ACTIVE'") Long activeSupplierOrganization(long tenantId,long supplierId);
    @Insert("INSERT INTO prj_contract(id,tenant_id,organization_id,supplier_id,contract_no,contract_name,contract_type,amount,currency,signed_date,start_date,end_date,owner_id,file_id,created_by,updated_by) VALUES(#{id},#{tenantId},#{organizationId},#{supplierId},#{number},#{name},#{type},#{amount},#{currency},#{signedDate},#{startDate},#{endDate},#{ownerId},#{fileId},#{actorId},#{actorId})") int insertContract(long id,long tenantId,long actorId,long organizationId,long supplierId,String number,String name,String type,BigDecimal amount,String currency,LocalDate signedDate,LocalDate startDate,LocalDate endDate,long ownerId,long fileId);
    @Update("UPDATE prj_contract SET contract_name=#{name},contract_type=#{type},amount=#{amount},currency=#{currency},signed_date=#{signedDate},start_date=#{startDate},end_date=#{endDate},owner_id=#{ownerId},file_id=#{fileId},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status='DRAFT' AND version=#{version}") int updateContract(long tenantId,long actorId,long id,String name,String type,BigDecimal amount,String currency,LocalDate signedDate,LocalDate startDate,LocalDate endDate,long ownerId,long fileId,int version);
    @Update("UPDATE prj_contract SET status=#{status},termination_reason=#{reason},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND version=#{version}") int changeContractStatus(long tenantId,long actorId,long id,String status,String reason,int version);
    @Select("<script>SELECT COUNT(*) FROM prj_project p JOIN sup_supplier s ON s.id=p.supplier_id WHERE p.tenant_id=#{tenantId}"+PROJECT_SCOPE+PROJECT_FILTER+"</script>") long countProjects(long tenantId,String keyword,String status,String scopeType,Set<Long> organizationIds,Set<Long> projectIds,long actorId);
    @Select("<script>SELECT p.id,p.organization_id,p.supplier_id,s.supplier_code,s.supplier_name,p.contract_id,c.contract_no,p.project_code,p.project_name name,p.project_type type,p.planned_start_date,p.planned_end_date,p.status,p.version,p.updated_at FROM prj_project p JOIN sup_supplier s ON s.id=p.supplier_id LEFT JOIN prj_contract c ON c.id=p.contract_id WHERE p.tenant_id=#{tenantId}"+PROJECT_SCOPE+PROJECT_FILTER+" ORDER BY p.updated_at DESC,p.id DESC LIMIT #{size} OFFSET #{offset}</script>") List<ProjectModels.ProjectSummary> projects(long tenantId,String keyword,String status,String scopeType,Set<Long> organizationIds,Set<Long> projectIds,long actorId,int offset,int size);
    @Select("SELECT p.id,p.organization_id,p.supplier_id,p.contract_id,s.supplier_code,s.supplier_name,c.contract_no,p.project_code,p.project_name,p.project_type,p.site_address,p.planned_start_date,p.planned_end_date,p.actual_start_date,p.actual_end_date,p.manager_id,p.budget_amount,p.currency,p.status,p.status_reason,p.created_by,p.version,p.created_at,p.updated_at FROM prj_project p JOIN sup_supplier s ON s.id=p.supplier_id LEFT JOIN prj_contract c ON c.id=p.contract_id WHERE p.tenant_id=#{tenantId} AND p.id=#{id}") ProjectModels.ProjectRow project(long tenantId,long id);
    @Select("SELECT supplier_id FROM prj_contract WHERE tenant_id=#{tenantId} AND id=#{contractId} AND status='ACTIVE'") Long activeContractSupplier(long tenantId,long contractId);
    @Insert("INSERT INTO prj_project(id,tenant_id,organization_id,supplier_id,contract_id,project_code,project_name,project_type,site_address,planned_start_date,planned_end_date,manager_id,budget_amount,currency,created_by,updated_by) VALUES(#{id},#{tenantId},#{organizationId},#{supplierId},#{contractId},#{code},#{name},#{type},#{siteAddress},#{startDate},#{endDate},#{managerId},#{budgetAmount},#{currency},#{actorId},#{actorId})") int insertProject(long id,long tenantId,long actorId,long organizationId,long supplierId,Long contractId,String code,String name,String type,String siteAddress,LocalDate startDate,LocalDate endDate,long managerId,BigDecimal budgetAmount,String currency);
    @Update("UPDATE prj_project SET project_name=#{name},project_type=#{type},site_address=#{siteAddress},planned_start_date=#{startDate},planned_end_date=#{endDate},manager_id=#{managerId},budget_amount=#{budgetAmount},currency=#{currency},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status='PLANNED' AND version=#{version}") int updateProject(long tenantId,long actorId,long id,String name,String type,String siteAddress,LocalDate startDate,LocalDate endDate,long managerId,BigDecimal budgetAmount,String currency,int version);
    @Update("UPDATE prj_project SET status=#{status},status_reason=#{reason},actual_start_date=CASE WHEN #{status}='ACTIVE' AND actual_start_date IS NULL THEN CURRENT_DATE ELSE actual_start_date END,actual_end_date=CASE WHEN #{status}='COMPLETED' THEN CURRENT_DATE ELSE actual_end_date END,updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND version=#{version}") int changeProjectStatus(long tenantId,long actorId,long id,String status,String reason,int version);
}
