<script setup lang="ts">
import { reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { ElMessage } from 'element-plus';
import { Fold, FullScreen, SwitchButton } from '@element-plus/icons-vue';
import { useSessionStore } from './stores/session';
const session=useSessionStore();const router=useRouter();const collapsed=ref(false);const submitting=ref(false);const form=reactive({tenantCode:'demo',username:'admin',password:'Admin@123456'});
async function login(){submitting.value=true;try{await session.login(form);await router.replace('/suppliers/master');ElMessage.success('登录成功');}catch(e){ElMessage.error(e instanceof Error?e.message:'登录失败');}finally{submitting.value=false;}}
async function logout(){session.logout();await router.replace('/');}
function route(path:string){return router.resolve(path).matched.some(r=>r.path===path)?path:'/coming-soon';}
</script>
<template>
  <div v-if="!session.accessToken" class="login-page"><section class="brand-panel"><div class="brand-mark">ISM</div><p>INDUSTRIAL SUPPLIER MANAGEMENT</p><h1>工业供应商管理平台</h1><span>面向制造业与化工企业的供应商全生命周期协同平台</span></section><el-card class="login-card" shadow="always"><template #header><div><h2>欢迎登录</h2><p>请输入租户和账号信息</p></div></template><el-form label-position="top" @submit.prevent="login"><el-form-item label="租户编码"><el-input v-model="form.tenantCode" size="large" /></el-form-item><el-form-item label="用户名"><el-input v-model="form.username" size="large" /></el-form-item><el-form-item label="密码"><el-input v-model="form.password" type="password" show-password size="large" @keyup.enter="login" /></el-form-item><el-button type="primary" size="large" :loading="submitting" class="login-button" @click="login">登录系统</el-button></el-form></el-card></div>
  <el-container v-else class="app-shell"><el-aside :width="collapsed?'68px':'232px'" class="sidebar"><div class="logo"><strong>ISM</strong><span v-if="!collapsed">工业供应链</span></div><el-menu router :collapse="collapsed" :default-active="$route.path" background-color="#102a43" text-color="#b8c7d5" active-text-color="#fff"><el-sub-menu v-for="menu in session.menus" :key="menu.id" :index="menu.route"><template #title><el-icon><FullScreen /></el-icon><span>{{menu.name}}</span></template><el-menu-item v-for="child in menu.children" :key="child.id" :index="route(child.route)">{{child.name}}</el-menu-item></el-sub-menu></el-menu></el-aside><el-container><el-header class="topbar"><div class="topbar-left"><el-button text :icon="Fold" @click="collapsed=!collapsed"/><el-breadcrumb separator="/"><el-breadcrumb-item>供应商管理平台</el-breadcrumb-item><el-breadcrumb-item>{{ $route.meta.title }}</el-breadcrumb-item></el-breadcrumb></div><div class="topbar-right"><el-select :model-value="session.currentOrganization?.id" style="width:220px" @change="session.switchOrganization"><el-option v-for="item in session.organizationOptions" :key="item.id" :label="item.label" :value="item.id"/></el-select><span class="user-name">租户管理员</span><el-button text :icon="SwitchButton" @click="logout">退出</el-button></div></el-header><el-main class="content"><router-view /></el-main></el-container></el-container>
</template>
