<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus, Refresh, Search } from '@element-plus/icons-vue';
import type { components } from '@ism/api-client';
import { useSessionStore } from '../stores/session';
type Summary=components['schemas']['SupplierSummary'];type Status=components['schemas']['SupplierStatus'];
const session=useSessionStore();const loading=ref(false);const saving=ref(false);const dialog=ref(false);const rows=ref<Summary[]>([]);const total=ref(0);
const exitDialog=ref(false);const exitRow=ref<Summary|null>(null);const exitReason=ref('');const readiness=ref<components['schemas']['SupplierExitReadiness']|null>(null);
async function previewExit(row:Summary){const {data,error}=await session.client.GET('/suppliers/{id}/exit-readiness',{params:{path:{id:row.id}}});if(error){ElMessage.error(error.error.message);return;}readiness.value=data?.data??null;exitRow.value=row;exitReason.value='';exitDialog.value=true;}
async function confirmExit(){if(!exitRow.value||!readiness.value?.ready||!exitReason.value.trim())return;const {error}=await session.client.POST('/suppliers/{id}/status',{params:{path:{id:exitRow.value.id}},body:{status:'EXITED',reason:exitReason.value,version:exitRow.value.version}});if(error){ElMessage.error(error.error.message);return;}exitDialog.value=false;ElMessage.success('供应商已退出，历史记录保留');await load();}
const query=reactive<{keyword:string;status?:Status;page:number;size:number}>({keyword:'',status:undefined,page:0,size:20});
const form=reactive({code:'',name:'',shortName:'',unifiedSocialCreditCode:'',type:'MANUFACTURER' as components['schemas']['SupplierType'],industry:'',organizationId:'',riskLevel:'LOW' as components['schemas']['SupplierRiskLevel'],contactName:'',mobile:'',email:''});
const typeNames={MANUFACTURER:'生产商',TRADER:'贸易商',SERVICE_PROVIDER:'服务商',CONTRACTOR:'承包商',OTHER:'其他'};const statusNames={DRAFT:'草稿',ACTIVE:'有效',SUSPENDED:'停用',EXITED:'已退出'};const riskNames={LOW:'低',MEDIUM:'中',HIGH:'高'};
async function load(){loading.value=true;const result=await session.client.GET('/suppliers',{params:{query:{keyword:query.keyword||undefined,status:query.status,page:query.page,size:query.size}}});loading.value=false;if(!result.data?.data){ElMessage.error('供应商列表加载失败');return;}rows.value=result.data.data.items;total.value=result.data.data.total;}
function openCreate(){Object.assign(form,{code:'',name:'',shortName:'',unifiedSocialCreditCode:'',type:'MANUFACTURER',industry:'',organizationId:session.currentOrganization?.id??'',riskLevel:'LOW',contactName:'',mobile:'',email:''});dialog.value=true;}
async function create(){if(!form.code||!form.name||!form.organizationId){ElMessage.warning('请填写编码、名称和归属组织');return;}saving.value=true;const contacts=form.contactName?[{name:form.contactName,mobile:form.mobile||undefined,email:form.email||undefined,primary:true,sortOrder:0}]:[];const {error}=await session.client.POST('/suppliers',{body:{code:form.code,name:form.name,shortName:form.shortName||undefined,unifiedSocialCreditCode:form.unifiedSocialCreditCode||undefined,type:form.type,industry:form.industry||undefined,countryCode:'CN',organizationId:form.organizationId,riskLevel:form.riskLevel,contacts,version:0}});saving.value=false;if(error){ElMessage.error(error.error.message);return;}dialog.value=false;ElMessage.success('供应商档案已创建');await load();}
async function activate(row:Summary){await ElMessageBox.confirm(`确认启用供应商“${row.name}”？`,'状态确认',{type:'warning'});const {error}=await session.client.POST('/suppliers/{id}/status',{params:{path:{id:row.id}},body:{status:'ACTIVE',reason:'档案审核通过',version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('供应商已启用');await load();}}
function pageChanged(value:number){query.page=value-1;void load();}
const financeDialog=ref(false),financeBusy=ref(false),finance=ref<components['schemas']['ManualClearanceView']|null>(null),financeSupplier=ref<Summary|null>(null);const financeForm=reactive({evidenceFileId:'',statement:''});
async function openFinance(row:Summary){const {data,error}=await session.client.GET('/suppliers/{id}/financial-clearance',{params:{path:{id:row.id}}});if(error){ElMessage.error(error.error.message);return;}financeSupplier.value=row;finance.value=data?.data??null;financeForm.evidenceFileId=data?.data?.record?.evidenceFileId??'';financeForm.statement=data?.data?.record?.statement??'';financeDialog.value=true;}
async function submitFinance(){if(!financeSupplier.value||!financeForm.evidenceFileId||!financeForm.statement.trim())return;financeBusy.value=true;try{const {data,error}=await session.client.POST('/suppliers/{id}/financial-clearance',{params:{path:{id:financeSupplier.value.id}},body:{...financeForm,version:finance.value?.record?.version??0}});if(error)ElMessage.error(error.error.message);else{finance.value=data?.data??null;ElMessage.success('已提交，须由另一名复核人确认');}}finally{financeBusy.value=false;}}
async function reviewFinance(decision:'APPROVE'|'REJECT'|'REVOKE'){if(!financeSupplier.value||!finance.value?.record)return;try{const comment=(await ElMessageBox.prompt('请填写复核结论；批准表示人工核验，不代表 ERP 已结清','财务复核',{inputValidator:(value:string)=>!!value.trim()||'结论不能为空'})).value;financeBusy.value=true;const {data,error}=await session.client.POST('/suppliers/{id}/financial-clearance/review',{params:{path:{id:financeSupplier.value.id}},body:{decision,comment,version:finance.value.record.version}});if(error)ElMessage.error(error.error.message);else{finance.value=data?.data??null;ElMessage.success('复核结果已记录');}}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error('操作失败，请重试');}finally{financeBusy.value=false;}}
onMounted(load);
</script>
<template><div class="page"><div class="page-heading"><div><h1>供应商档案</h1><p>统一维护供应商基础信息、归属组织、风险等级与生命周期状态</p></div><el-button type="primary" :icon="Plus" @click="openCreate">新建供应商</el-button></div>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键词"><el-input v-model="query.keyword" clearable placeholder="编码、名称、信用代码" :prefix-icon="Search" @keyup.enter="query.page=0;load()"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部状态" style="width:150px"><el-option v-for="(name,key) in statusNames" :key="key" :label="name" :value="key"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="query.page=0;load()">查询</el-button><el-button :icon="Refresh" @click="query.keyword='';query.status=undefined;query.page=0;load()">重置</el-button></el-form-item></el-form></el-card>
  <el-card shadow="never" class="table-card"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="code" label="供应商编码" width="160"/><el-table-column prop="name" label="供应商名称" min-width="220"><template #default="{row}"><strong>{{row.name}}</strong><el-tag v-if="row.observed" type="warning" size="small" style="margin-left:8px">观察中</el-tag><div class="subtext">{{row.shortName||row.unifiedSocialCreditCode||'—'}}</div></template></el-table-column><el-table-column label="类型" width="110"><template #default="{row}">{{typeNames[row.type as keyof typeof typeNames]}}</template></el-table-column><el-table-column label="风险" width="90"><template #default="{row}"><el-tag :type="row.riskLevel==='HIGH'?'danger':row.riskLevel==='MEDIUM'?'warning':'success'">{{riskNames[row.riskLevel as keyof typeof riskNames]}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':row.status==='SUSPENDED'?'warning':row.status==='EXITED'?'info':''">{{statusNames[row.status as keyof typeof statusNames]}}</el-tag></template></el-table-column><el-table-column prop="updatedAt" label="更新时间" width="180"/><el-table-column label="操作" width="230" fixed="right"><template #default="{row}"><el-button v-if="row.status==='DRAFT'||row.status==='SUSPENDED'" link type="primary" @click="activate(row)">启用</el-button><el-button link type="primary" @click="openFinance(row)">财务核验</el-button><el-button v-if="row.status!=='EXITED'" link type="danger" @click="previewExit(row)">退出检查</el-button></template></el-table-column></el-table><div class="pagination"><span>共 {{total}} 条</span><el-pagination background layout="prev, pager, next" :total="total" :page-size="query.size" :current-page="query.page+1" @current-change="pageChanged"/></div></el-card>
  <el-dialog v-model="dialog" title="新建供应商档案" width="760px" destroy-on-close><el-form label-position="top"><el-row :gutter="18"><el-col :span="12"><el-form-item label="供应商编码 *"><el-input v-model="form.code" placeholder="如 SUP-0001"/></el-form-item></el-col><el-col :span="12"><el-form-item label="供应商名称 *"><el-input v-model="form.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="简称"><el-input v-model="form.shortName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="统一社会信用代码"><el-input v-model="form.unifiedSocialCreditCode" maxlength="18"/></el-form-item></el-col><el-col :span="8"><el-form-item label="供应商类型"><el-select v-model="form.type"><el-option v-for="(name,key) in typeNames" :key="key" :label="name" :value="key"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="归属组织 *"><el-select v-model="form.organizationId"><el-option v-for="item in session.organizationOptions" :key="item.id" :label="item.label" :value="item.id"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="风险等级"><el-select v-model="form.riskLevel"><el-option v-for="(name,key) in riskNames" :key="key" :label="name" :value="key"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="所属行业"><el-input v-model="form.industry"/></el-form-item></el-col><el-col :span="12"><el-form-item label="主要联系人"><el-input v-model="form.contactName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="联系人手机"><el-input v-model="form.mobile"/></el-form-item></el-col><el-col :span="12"><el-form-item label="联系人邮箱"><el-input v-model="form.email"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">保存草稿</el-button></template></el-dialog>
<el-dialog v-model="exitDialog" :title="`${exitRow?.name??''} · 退出前检查`" width="600px"><p>退出不可恢复。请先完成全部待处置事项，历史记录不会删除。</p><el-table :data="readiness?.blockers??[]"><el-table-column prop="label" label="检查项"/><el-table-column prop="count" label="待处置数量"/></el-table><el-alert v-if="!readiness?.ready" title="尚有待处置事项或检查能力未配置，不能退出" type="warning" :closable="false"/><el-input v-model="exitReason" type="textarea" maxlength="500" placeholder="填写退出原因" style="margin-top:16px"/><template #footer><el-button @click="exitDialog=false">取消</el-button><el-button type="danger" :disabled="!readiness?.ready||!exitReason.trim()" @click="confirmExit">确认不可逆退出</el-button></template></el-dialog>
<el-dialog v-model="financeDialog" :title="`${financeSupplier?.name??''} · 人工财务核验`" width="650px"><el-alert title="人工证据复核，不代表 ERP 已付款。确认短期有效，退出时仍会重新检查。" type="warning" :closable="false"/><p v-if="!finance?.manualEnabled">当前为 ERP 模式，不能使用人工核验覆盖 ERP 结果。</p><el-descriptions v-if="finance?.record" :column="1" border><el-descriptions-item label="状态">{{finance.record.status}}</el-descriptions-item><el-descriptions-item label="提交人">{{finance.record.submittedBy}}</el-descriptions-item><el-descriptions-item label="复核人">{{finance.record.reviewedBy??'—'}}</el-descriptions-item><el-descriptions-item label="复核时间">{{finance.record.reviewedAt??'—'}}</el-descriptions-item><el-descriptions-item label="结论">{{finance.record.reviewComment??'—'}}</el-descriptions-item></el-descriptions><el-form label-position="top"><el-form-item label="已上传的证据文件 ID"><el-input v-model="financeForm.evidenceFileId" :disabled="!finance?.manualEnabled"/></el-form-item><el-form-item label="核验范围及结清说明（含预付款、质保金、扣款、索赔等）"><el-input v-model="financeForm.statement" type="textarea" maxlength="2000" :disabled="!finance?.manualEnabled"/></el-form-item></el-form><template #footer><el-button @click="financeDialog=false">关闭</el-button><template v-if="finance?.manualEnabled && financeSupplier?.status!=='EXITED'"><el-button :loading="financeBusy" @click="submitFinance">提交核验</el-button><template v-if="finance.record?.status==='SUBMITTED' && finance.record.submittedBy!==session.actorId"><el-button :loading="financeBusy" @click="reviewFinance('REJECT')">驳回</el-button><el-button type="primary" :loading="financeBusy" @click="reviewFinance('APPROVE')">复核通过</el-button></template><el-button v-if="finance.record?.status==='APPROVED'" type="danger" :loading="financeBusy" @click="reviewFinance('REVOKE')">撤销确认</el-button></template></template></el-dialog>
</div></template>
