<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus, Refresh, Search } from '@element-plus/icons-vue';
import type { components } from '@ism/api-client';
import { useSessionStore } from '../stores/session';
type Summary=components['schemas']['SupplierSummary'];type Status=components['schemas']['SupplierStatus'];
const session=useSessionStore();const loading=ref(false);const saving=ref(false);const dialog=ref(false);const rows=ref<Summary[]>([]);const total=ref(0);
const query=reactive<{keyword:string;status?:Status;page:number;size:number}>({keyword:'',status:undefined,page:0,size:20});
const form=reactive({code:'',name:'',shortName:'',unifiedSocialCreditCode:'',type:'MANUFACTURER' as components['schemas']['SupplierType'],industry:'',organizationId:'',riskLevel:'LOW' as components['schemas']['SupplierRiskLevel'],contactName:'',mobile:'',email:''});
const typeNames={MANUFACTURER:'生产商',TRADER:'贸易商',SERVICE_PROVIDER:'服务商',CONTRACTOR:'承包商',OTHER:'其他'};const statusNames={DRAFT:'草稿',ACTIVE:'有效',SUSPENDED:'停用',EXITED:'已退出'};const riskNames={LOW:'低',MEDIUM:'中',HIGH:'高'};
async function load(){loading.value=true;const result=await session.client.GET('/suppliers',{params:{query:{keyword:query.keyword||undefined,status:query.status,page:query.page,size:query.size}}});loading.value=false;if(!result.data?.data){ElMessage.error('供应商列表加载失败');return;}rows.value=result.data.data.items;total.value=result.data.data.total;}
function openCreate(){Object.assign(form,{code:'',name:'',shortName:'',unifiedSocialCreditCode:'',type:'MANUFACTURER',industry:'',organizationId:session.currentOrganization?.id??'',riskLevel:'LOW',contactName:'',mobile:'',email:''});dialog.value=true;}
async function create(){if(!form.code||!form.name||!form.organizationId){ElMessage.warning('请填写编码、名称和归属组织');return;}saving.value=true;const contacts=form.contactName?[{name:form.contactName,mobile:form.mobile||undefined,email:form.email||undefined,primary:true,sortOrder:0}]:[];const {error}=await session.client.POST('/suppliers',{body:{code:form.code,name:form.name,shortName:form.shortName||undefined,unifiedSocialCreditCode:form.unifiedSocialCreditCode||undefined,type:form.type,industry:form.industry||undefined,countryCode:'CN',organizationId:form.organizationId,riskLevel:form.riskLevel,contacts,version:0}});saving.value=false;if(error){ElMessage.error(error.error.message);return;}dialog.value=false;ElMessage.success('供应商档案已创建');await load();}
async function activate(row:Summary){await ElMessageBox.confirm(`确认启用供应商“${row.name}”？`,'状态确认',{type:'warning'});const {error}=await session.client.POST('/suppliers/{id}/status',{params:{path:{id:row.id}},body:{status:'ACTIVE',reason:'档案审核通过',version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('供应商已启用');await load();}}
function pageChanged(value:number){query.page=value-1;void load();}
onMounted(load);
</script>
<template><div class="page"><div class="page-heading"><div><h1>供应商档案</h1><p>统一维护供应商基础信息、归属组织、风险等级与生命周期状态</p></div><el-button type="primary" :icon="Plus" @click="openCreate">新建供应商</el-button></div>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键词"><el-input v-model="query.keyword" clearable placeholder="编码、名称、信用代码" :prefix-icon="Search" @keyup.enter="query.page=0;load()"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部状态" style="width:150px"><el-option v-for="(name,key) in statusNames" :key="key" :label="name" :value="key"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="query.page=0;load()">查询</el-button><el-button :icon="Refresh" @click="query.keyword='';query.status=undefined;query.page=0;load()">重置</el-button></el-form-item></el-form></el-card>
  <el-card shadow="never" class="table-card"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="code" label="供应商编码" width="160"/><el-table-column prop="name" label="供应商名称" min-width="220"><template #default="{row}"><strong>{{row.name}}</strong><div class="subtext">{{row.shortName||row.unifiedSocialCreditCode||'—'}}</div></template></el-table-column><el-table-column label="类型" width="110"><template #default="{row}">{{typeNames[row.type as keyof typeof typeNames]}}</template></el-table-column><el-table-column label="风险" width="90"><template #default="{row}"><el-tag :type="row.riskLevel==='HIGH'?'danger':row.riskLevel==='MEDIUM'?'warning':'success'">{{riskNames[row.riskLevel as keyof typeof riskNames]}}</el-tag></template></el-table-column><el-table-column label="状态" width="100"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':row.status==='SUSPENDED'?'warning':row.status==='EXITED'?'info':''">{{statusNames[row.status as keyof typeof statusNames]}}</el-tag></template></el-table-column><el-table-column prop="updatedAt" label="更新时间" width="180"/><el-table-column label="操作" width="150" fixed="right"><template #default="{row}"><el-button v-if="row.status==='DRAFT'||row.status==='SUSPENDED'" link type="primary" @click="activate(row)">启用</el-button><el-button link>查看</el-button></template></el-table-column></el-table><div class="pagination"><span>共 {{total}} 条</span><el-pagination background layout="prev, pager, next" :total="total" :page-size="query.size" :current-page="query.page+1" @current-change="pageChanged"/></div></el-card>
  <el-dialog v-model="dialog" title="新建供应商档案" width="760px" destroy-on-close><el-form label-position="top"><el-row :gutter="18"><el-col :span="12"><el-form-item label="供应商编码 *"><el-input v-model="form.code" placeholder="如 SUP-0001"/></el-form-item></el-col><el-col :span="12"><el-form-item label="供应商名称 *"><el-input v-model="form.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="简称"><el-input v-model="form.shortName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="统一社会信用代码"><el-input v-model="form.unifiedSocialCreditCode" maxlength="18"/></el-form-item></el-col><el-col :span="8"><el-form-item label="供应商类型"><el-select v-model="form.type"><el-option v-for="(name,key) in typeNames" :key="key" :label="name" :value="key"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="归属组织 *"><el-select v-model="form.organizationId"><el-option v-for="item in session.organizationOptions" :key="item.id" :label="item.label" :value="item.id"/></el-select></el-form-item></el-col><el-col :span="8"><el-form-item label="风险等级"><el-select v-model="form.riskLevel"><el-option v-for="(name,key) in riskNames" :key="key" :label="name" :value="key"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="所属行业"><el-input v-model="form.industry"/></el-form-item></el-col><el-col :span="12"><el-form-item label="主要联系人"><el-input v-model="form.contactName"/></el-form-item></el-col><el-col :span="12"><el-form-item label="联系人手机"><el-input v-model="form.mobile"/></el-form-item></el-col><el-col :span="12"><el-form-item label="联系人邮箱"><el-input v-model="form.email"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">保存草稿</el-button></template></el-dialog>
</div></template>
