<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus, Refresh, Search, Setting } from '@element-plus/icons-vue';
import type { components } from '@ism/api-client';
import { useSessionStore } from '../stores/session';
type Row=components['schemas']['QualificationSummary'];type Type=components['schemas']['QualificationType'];type Supplier=components['schemas']['SupplierSummary'];type Status=components['schemas']['QualificationStatus'];
const session=useSessionStore();const tab=ref('ledger');const loading=ref(false);const saving=ref(false);const dialog=ref(false);const typeDialog=ref(false);const rows=ref<Row[]>([]);const types=ref<Type[]>([]);const suppliers=ref<Supplier[]>([]);const total=ref(0);
const query=reactive<{keyword:string;status?:Status;page:number;size:number}>({keyword:'',status:undefined,page:0,size:20});
const form=reactive({supplierId:'',typeId:'',certificateNo:'',issuingAuthority:'',issueDate:'',effectiveDate:'',expiryDate:'',permanent:false,warningDays:30,fileId:''});
const typeForm=reactive({code:'',name:'',category:'LEGAL',validityRequired:true,defaultWarningDays:30,description:''});
const statusNames={DRAFT:'待核验',VALID:'有效',EXPIRING:'即将到期',EXPIRED:'已过期',REJECTED:'核验拒绝',REVOKED:'已撤销',SUPERSEDED:'已被替代'};
async function load(){loading.value=true;const {data}=await session.client.GET('/qualifications',{params:{query:{keyword:query.keyword||undefined,status:query.status,page:query.page,size:query.size}}});loading.value=false;const page=data?.data;if(!page){ElMessage.error('资质台账加载失败');return;}rows.value=page.items;total.value=page.total;}
async function loadTypes(){const {data}=await session.client.GET('/qualifications/types');types.value=data?.data??[];}
async function openCreate(){await Promise.all([loadTypes(),session.client.GET('/suppliers',{params:{query:{page:0,size:100}}}).then(({data})=>suppliers.value=data?.data?.items??[])]);Object.assign(form,{supplierId:'',typeId:'',certificateNo:'',issuingAuthority:'',issueDate:'',effectiveDate:'',expiryDate:'',permanent:false,warningDays:30,fileId:''});dialog.value=true;}
async function create(){if(!form.supplierId||!form.typeId||!form.certificateNo||!form.fileId){ElMessage.warning('请填写供应商、资质类型、证书编号和文件 ID');return;}saving.value=true;const {error}=await session.client.POST('/qualifications',{body:{supplierId:form.supplierId,typeId:form.typeId,certificateNo:form.certificateNo,issuingAuthority:form.issuingAuthority||undefined,issueDate:form.issueDate||undefined,effectiveDate:form.effectiveDate||undefined,expiryDate:form.permanent?undefined:form.expiryDate||undefined,permanent:form.permanent,warningDays:form.warningDays,fileId:form.fileId,version:0}});saving.value=false;if(error){ElMessage.error(error.error.message);return;}dialog.value=false;ElMessage.success('资质草稿已创建');await load();}
async function verify(row:Row,decision:'APPROVE'|'REJECT'){const label=decision==='APPROVE'?'通过':'拒绝';const result=await ElMessageBox.prompt(`请输入核验${label}意见`,'资质核验',{inputPattern:/.+/,inputErrorMessage:'核验意见不能为空',type:decision==='APPROVE'?'success':'warning'});const {error}=await session.client.POST('/qualifications/{id}/verify',{params:{path:{id:row.id}},body:{decision,comment:result.value,version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success(`核验${label}`);await load();}}
async function revoke(row:Row){const result=await ElMessageBox.prompt('请输入撤销原因','撤销资质',{inputPattern:/.+/,inputErrorMessage:'撤销原因不能为空',type:'warning'});const {error}=await session.client.POST('/qualifications/{id}/revoke',{params:{path:{id:row.id}},body:{reason:result.value,version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('资质已撤销');await load();}}
function openType(){Object.assign(typeForm,{code:'',name:'',category:'LEGAL',validityRequired:true,defaultWarningDays:30,description:''});typeDialog.value=true;}
async function createType(){if(!typeForm.code||!typeForm.name){ElMessage.warning('请填写类型编码和名称');return;}const {error}=await session.client.POST('/qualifications/types',{body:{...typeForm,status:'ACTIVE',version:0}});if(error){ElMessage.error(error.error.message);return;}typeDialog.value=false;ElMessage.success('资质类型已创建');await loadTypes();}
function tagType(status:Status){return status==='VALID'?'success':status==='EXPIRING'?'warning':status==='EXPIRED'||status==='REJECTED'||status==='REVOKED'?'danger':'info';}
function pageChanged(value:number){query.page=value-1;void load();}
onMounted(()=>Promise.all([load(),loadTypes()]));
</script>
<template><div class="page"><div class="page-heading"><div><h1>资质证照</h1><p>统一维护供应商证照核验、有效期预警、撤销与换证记录</p></div><div><el-button :icon="Setting" @click="tab='types'">类型配置</el-button><el-button type="primary" :icon="Plus" @click="openCreate">新增证照</el-button></div></div>
  <el-tabs v-model="tab"><el-tab-pane label="证照台账" name="ledger"><el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键词"><el-input v-model="query.keyword" clearable placeholder="供应商、证书编号" :prefix-icon="Search" @keyup.enter="query.page=0;load()"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部状态" style="width:150px"><el-option v-for="(name,key) in statusNames" :key="key" :label="name" :value="key"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="query.page=0;load()">查询</el-button><el-button :icon="Refresh" @click="query.keyword='';query.status=undefined;query.page=0;load()">重置</el-button></el-form-item></el-form></el-card>
    <el-card shadow="never" class="table-card"><el-table v-loading="loading" :data="rows" stripe><el-table-column label="供应商" min-width="210"><template #default="{row}"><strong>{{row.supplierName}}</strong><div class="subtext">{{row.supplierCode}}</div></template></el-table-column><el-table-column prop="typeName" label="资质类型" min-width="150"/><el-table-column prop="certificateNo" label="证书编号" min-width="160"/><el-table-column label="有效期" width="150"><template #default="{row}">{{row.permanent?'长期有效':row.expiryDate||'—'}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="tagType(row.status)">{{statusNames[row.status as keyof typeof statusNames]}}</el-tag></template></el-table-column><el-table-column label="操作" width="210" fixed="right"><template #default="{row}"><template v-if="row.status==='DRAFT'"><el-button link type="success" @click="verify(row,'APPROVE')">通过</el-button><el-button link type="danger" @click="verify(row,'REJECT')">拒绝</el-button></template><el-button v-if="row.status==='VALID'||row.status==='EXPIRING'||row.status==='EXPIRED'" link type="danger" @click="revoke(row)">撤销</el-button></template></el-table-column></el-table><div class="pagination"><span>共 {{total}} 条</span><el-pagination background layout="prev, pager, next" :total="total" :page-size="query.size" :current-page="query.page+1" @current-change="pageChanged"/></div></el-card></el-tab-pane>
    <el-tab-pane label="资质类型" name="types"><div style="margin-bottom:16px;text-align:right"><el-button type="primary" :icon="Plus" @click="openType">新增类型</el-button></div><el-card shadow="never"><el-table :data="types"><el-table-column prop="code" label="编码"/><el-table-column prop="name" label="名称"/><el-table-column prop="category" label="分类"/><el-table-column label="有效期要求"><template #default="{row}">{{row.validityRequired?'必须填写':'可长期有效'}}</template></el-table-column><el-table-column prop="defaultWarningDays" label="默认预警天数"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{row.status==='ACTIVE'?'启用':'停用'}}</el-tag></template></el-table-column></el-table></el-card></el-tab-pane></el-tabs>
  <el-dialog v-model="dialog" title="新增供应商证照" width="720px"><el-form label-position="top"><el-row :gutter="18"><el-col :span="12"><el-form-item label="供应商 *"><el-select v-model="form.supplierId" filterable style="width:100%"><el-option v-for="item in suppliers" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="资质类型 *"><el-select v-model="form.typeId" style="width:100%"><el-option v-for="item in types.filter(x=>x.status==='ACTIVE')" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="证书编号 *"><el-input v-model="form.certificateNo"/></el-form-item></el-col><el-col :span="12"><el-form-item label="发证机关"><el-input v-model="form.issuingAuthority"/></el-form-item></el-col><el-col :span="8"><el-form-item label="签发日期"><el-date-picker v-model="form.issueDate" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="生效日期"><el-date-picker v-model="form.effectiveDate" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="到期日期"><el-date-picker v-model="form.expiryDate" value-format="YYYY-MM-DD" :disabled="form.permanent" style="width:100%"/></el-form-item></el-col><el-col :span="12"><el-form-item label="证照文件 ID *"><el-input v-model="form.fileId" placeholder="从文件中心选择"/></el-form-item></el-col><el-col :span="6"><el-form-item label="预警天数"><el-input-number v-model="form.warningDays" :min="0" :max="3650"/></el-form-item></el-col><el-col :span="6"><el-form-item label="长期有效"><el-switch v-model="form.permanent"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">保存草稿</el-button></template></el-dialog>
  <el-dialog v-model="typeDialog" title="新增资质类型" width="560px"><el-form label-position="top"><el-row :gutter="18"><el-col :span="12"><el-form-item label="类型编码 *"><el-input v-model="typeForm.code" placeholder="如 SAFETY_LICENSE"/></el-form-item></el-col><el-col :span="12"><el-form-item label="类型名称 *"><el-input v-model="typeForm.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="分类"><el-input v-model="typeForm.category"/></el-form-item></el-col><el-col :span="12"><el-form-item label="默认预警天数"><el-input-number v-model="typeForm.defaultWarningDays" :min="0" :max="3650"/></el-form-item></el-col></el-row><el-form-item><el-checkbox v-model="typeForm.validityRequired">必须填写有效期</el-checkbox></el-form-item><el-form-item label="说明"><el-input v-model="typeForm.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="typeDialog=false">取消</el-button><el-button type="primary" @click="createType">保存</el-button></template></el-dialog>
</div></template>
