<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRoute } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus, Refresh, Search } from '@element-plus/icons-vue';
import type { components } from '@ism/api-client';
import { useSessionStore } from '../stores/session';
import PersonalTableViews from '../components/PersonalTableViews.vue';
const columnDefinitions=[{key:'applicationNo',label:'申请单号',required:true,width:190},{key:'supplierName',label:'供应商',required:true,width:220},{key:'purchaseCategory',label:'采购类别',required:false,width:150},{key:'status',label:'状态',required:false,width:110},{key:'submittedAt',label:'提交时间',required:false,width:180}];
const tableColumns=ref(columnDefinitions.map(c=>({key:c.key,visible:true,width:c.width})));
type Row=components['schemas']['AdmissionSummary'];type View=components['schemas']['AdmissionApplication'];type Supplier=components['schemas']['SupplierSummary'];type Status=components['schemas']['AdmissionStatus'];
type MaterialDraft={type:string;name:string;fileId:string;required:boolean;remark:string};
const session=useSessionStore();const route=useRoute();const loading=ref(false);const saving=ref(false);const dialog=ref(false);const rows=ref<Row[]>([]);const suppliers=ref<Supplier[]>([]);const total=ref(0);
const query=reactive<{keyword:string;status?:Status;page:number;size:number}>({keyword:'',status:undefined,page:0,size:20});
const form=reactive({supplierId:'',purchaseCategory:'',reason:'',expectedAnnualAmount:undefined as number|undefined,currency:'CNY',licenseFileId:''});
const detail=ref<View|null>(null),detailOpen=ref(false),editOpen=ref(false),editBusy=ref(false);
const editForm=reactive({purchaseCategory:'',reason:'',expectedAnnualAmount:undefined as number|undefined,currency:'CNY'});
const editMaterials=ref<MaterialDraft[]>([]);
const statusNames={DRAFT:'草稿',SUBMITTED:'待审核',REVISION_REQUIRED:'待补正',APPROVED:'已通过',REJECTED:'已拒绝',CANCELLED:'已取消'};
async function load(){loading.value=true;const {data}=await session.client.GET('/admissions',{params:{query:{keyword:query.keyword||undefined,status:query.status,page:query.page,size:query.size}}});loading.value=false;const page=data?.data;if(!page){ElMessage.error('准入申请加载失败');return;}rows.value=page.items;total.value=page.total;}
async function openCreate(){const {data}=await session.client.GET('/suppliers',{params:{query:{page:0,size:100}}});suppliers.value=data?.data?.items??[];Object.assign(form,{supplierId:'',purchaseCategory:'',reason:'',expectedAnnualAmount:undefined,currency:'CNY',licenseFileId:''});dialog.value=true;}
async function create(){if(!form.supplierId||!form.purchaseCategory||!form.reason){ElMessage.warning('请完整填写供应商、采购类别和准入原因');return;}saving.value=true;const {error}=await session.client.POST('/admissions',{body:{supplierId:form.supplierId,purchaseCategory:form.purchaseCategory,reason:form.reason,expectedAnnualAmount:form.expectedAnnualAmount,currency:form.currency,materials:[{type:'BUSINESS_LICENSE',name:'营业执照',fileId:form.licenseFileId||undefined,required:true,provided:Boolean(form.licenseFileId),sortOrder:10}],version:0}});saving.value=false;if(error){ElMessage.error(error.error.message);return;}dialog.value=false;ElMessage.success('准入申请草稿已创建');await load();}
async function fetchDetail(id:string){const {data,error}=await session.client.GET('/admissions/{id}',{params:{path:{id}}});if(error||!data?.data){ElMessage.error('申请不存在或当前账号无权查看');return null;}return data.data;}
async function showDetail(id:string){const value=await fetchDetail(id);if(!value)return;detail.value=value;detailOpen.value=true;}
async function openEdit(row:Pick<Row,'id'>){const value=await fetchDetail(row.id);if(!value)return;if(value.status!=='DRAFT'&&value.status!=='REVISION_REQUIRED'){ElMessage.warning('当前状态不可编辑');return;}
  detail.value=value;editForm.purchaseCategory=value.purchaseCategory;editForm.reason=value.reason;editForm.expectedAnnualAmount=value.expectedAnnualAmount;editForm.currency=value.currency??'CNY';
  editMaterials.value=value.materials.map(m=>({type:m.type,name:m.name,fileId:m.fileId??'',required:m.required,remark:m.remark??''}));editOpen.value=true;
}
function addMaterial(){editMaterials.value.push({type:'',name:'',fileId:'',required:false,remark:''});}
function removeMaterial(index:number){if(editMaterials.value[index]?.required)return;editMaterials.value.splice(index,1);}
async function saveEdit(){const current=detail.value;if(!current)return;
  if(!editForm.purchaseCategory.trim()||!editForm.reason.trim()){ElMessage.warning('请填写采购类别和准入原因');return;}
  if(editMaterials.value.length===0||editMaterials.value.length>50||editMaterials.value.some(m=>!m.name.trim()||!(/^[A-Z][A-Z0-9_]{1,63}$/.test(m.type.trim()))||(m.fileId.trim()&&!/^[1-9][0-9]{0,18}$/.test(m.fileId.trim())))||new Set(editMaterials.value.map(m=>m.type.trim())).size!==editMaterials.value.length){ElMessage.warning('请检查资料类型、名称、文件 ID 和重复项');return;}
  editBusy.value=true;try{const {data,error}=await session.client.PUT('/admissions/{id}',{params:{path:{id:current.id}},body:{supplierId:current.supplierId,purchaseCategory:editForm.purchaseCategory.trim(),reason:editForm.reason.trim(),expectedAnnualAmount:editForm.expectedAnnualAmount,currency:editForm.currency,materials:editMaterials.value.map((m,i)=>({type:m.type.trim(),name:m.name.trim(),fileId:m.fileId.trim()||undefined,required:m.required,provided:Boolean(m.fileId.trim()),remark:m.remark.trim()||undefined,sortOrder:(i+1)*10})),version:current.version}});
    if(error){ElMessage.error(error.error.message);return;}detail.value=data?.data??null;editOpen.value=false;ElMessage.success('申请资料已保存');await load();
  }catch{ElMessage.error('保存失败，请刷新重试');}finally{editBusy.value=false;}
}
async function submit(row:Row){await ElMessageBox.confirm('提交后将进入准入审核，确认继续？','提交确认',{type:'warning'});const {error}=await session.client.POST('/admissions/{id}/submit',{params:{path:{id:row.id},query:{version:row.version}}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('已提交审核');await load();if(detailOpen.value&&detail.value?.id===row.id)detail.value=await fetchDetail(row.id);}}
async function review(row:Row,decision:'APPROVE'|'REQUIRE_REVISION'|'REJECT'){const label={APPROVE:'通过',REQUIRE_REVISION:'退回补正',REJECT:'拒绝'}[decision];const result=await ElMessageBox.prompt(`请输入${label}意见`,`准入审核：${label}`,{inputPattern:/.+/,inputErrorMessage:'审核意见不能为空',type:decision==='APPROVE'?'success':'warning'});const {error}=await session.client.POST('/admissions/{id}/review',{params:{path:{id:row.id}},body:{decision,comment:result.value,version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success(`审核${label}完成`);await load();if(detailOpen.value&&detail.value?.id===row.id)detail.value=await fetchDetail(row.id);}}
function pageChanged(value:number){query.page=value-1;void load();}
onMounted(async()=>{query.keyword=typeof route.query.keyword==='string'?route.query.keyword.slice(0,100):'';await load();const id=route.query.admissionId;if(typeof id==='string'&&/^[1-9][0-9]{0,18}$/.test(id))await showDetail(id);});
</script>
<template><div class="page"><div class="page-heading"><div><h1>供应商准入</h1><p>管理准入资料、补正与审核决定，通过后自动启用供应商</p></div><el-button type="primary" :icon="Plus" @click="openCreate">发起准入</el-button></div>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键词"><el-input v-model="query.keyword" clearable placeholder="申请单号、供应商" :prefix-icon="Search" @keyup.enter="query.page=0;load()"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部状态" style="width:150px"><el-option v-for="(name,key) in statusNames" :key="key" :label="name" :value="key"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="query.page=0;load()">查询</el-button><el-button :icon="Refresh" @click="query.keyword='';query.status=undefined;query.page=0;load()">重置</el-button></el-form-item></el-form></el-card>
  <el-card shadow="never" class="table-card"><PersonalTableViews table-key="supplier.admission" :defaults="columnDefinitions" @change="tableColumns=$event"/><el-table :key="tableColumns.filter(c=>c.visible).map(c=>c.key+':'+c.width).join('|')" v-loading="loading" :data="rows" stripe><el-table-column v-for="column in tableColumns.filter(c=>c.visible)" :key="column.key" :label="columnDefinitions.find(c=>c.key===column.key)?.label" :width="column.width"><template #default="{row}"><template v-if="column.key==='supplierName'"><strong>{{row.supplierName}}</strong><div class="subtext">{{row.supplierCode}}</div></template><el-tag v-else-if="column.key==='status'" :type="row.status==='APPROVED'?'success':row.status==='REJECTED'?'danger':row.status==='REVISION_REQUIRED'?'warning':''">{{statusNames[row.status as keyof typeof statusNames]}}</el-tag><template v-else>{{row[column.key as keyof Row]??'—'}}</template></template></el-table-column><el-table-column label="操作" width="310" fixed="right"><template #default="{row}"><el-button link @click="showDetail(row.id)">详情</el-button><el-button v-if="row.status==='DRAFT'||row.status==='REVISION_REQUIRED'" link type="primary" @click="openEdit(row)">补充资料</el-button><el-button v-if="row.status==='DRAFT'||row.status==='REVISION_REQUIRED'" link type="primary" @click="submit(row)">提交</el-button><template v-if="row.status==='SUBMITTED'"><el-button link type="success" @click="review(row,'APPROVE')">通过</el-button><el-button link type="warning" @click="review(row,'REQUIRE_REVISION')">补正</el-button><el-button link type="danger" @click="review(row,'REJECT')">拒绝</el-button></template></template></el-table-column></el-table><div class="pagination"><span>共 {{total}} 条</span><el-pagination background layout="prev, pager, next" :total="total" :page-size="query.size" :current-page="query.page+1" @current-change="pageChanged"/></div></el-card>
  <el-dialog v-model="dialog" title="发起供应商准入" width="680px" destroy-on-close><el-alert title="营业执照为必填资料。可先保存草稿，关联文件后再提交。" type="info" :closable="false"/><el-form label-position="top" style="margin-top:16px"><el-form-item label="供应商 *"><el-select v-model="form.supplierId" filterable style="width:100%"><el-option v-for="item in suppliers" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id"/></el-select></el-form-item><el-row :gutter="18"><el-col :span="12"><el-form-item label="采购类别 *"><el-input v-model="form.purchaseCategory" placeholder="如设备、原材料、工程服务"/></el-form-item></el-col><el-col :span="12"><el-form-item label="预计年采购额"><el-input-number v-model="form.expectedAnnualAmount" :min="0" :precision="2" style="width:100%"/></el-form-item></el-col></el-row><el-form-item label="准入原因 *"><el-input v-model="form.reason" type="textarea" :rows="3" maxlength="500" show-word-limit/></el-form-item><el-form-item label="营业执照文件 ID"><el-input v-model="form.licenseFileId" placeholder="可从文件中心选择；留空时仅保存草稿"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">保存草稿</el-button></template></el-dialog>
  <el-drawer v-model="detailOpen" :title="`准入申请 · ${detail?.applicationNo??''}`" size="760px">
    <template v-if="detail">
      <el-descriptions :column="2" border>
        <el-descriptions-item label="供应商">{{detail.supplierName}}（{{detail.supplierCode}}）</el-descriptions-item>
        <el-descriptions-item label="状态">{{statusNames[detail.status]}}</el-descriptions-item>
        <el-descriptions-item label="采购类别">{{detail.purchaseCategory}}</el-descriptions-item>
        <el-descriptions-item label="预计年采购额">{{detail.expectedAnnualAmount??'—'}} {{detail.currency??''}}</el-descriptions-item>
        <el-descriptions-item label="准入原因" :span="2">{{detail.reason}}</el-descriptions-item>
      </el-descriptions>
      <h3>申请材料</h3>
      <el-table :data="detail.materials" size="small"><el-table-column prop="name" label="材料" min-width="160"/><el-table-column prop="type" label="类型" min-width="150"/><el-table-column label="要求" width="90"><template #default="{row}">{{row.required?'必填':'选填'}}</template></el-table-column><el-table-column label="状态" width="90"><template #default="{row}">{{row.provided?'已提供':'未提供'}}</template></el-table-column><el-table-column prop="fileId" label="文件 ID" min-width="160"/></el-table>
      <h3>审核轨迹</h3>
      <el-table :data="detail.reviews" size="small"><el-table-column prop="operatedAt" label="时间" width="185"/><el-table-column prop="action" label="动作" width="130"/><el-table-column prop="operatorId" label="操作人" width="115"/><el-table-column prop="comment" label="意见" min-width="180" show-overflow-tooltip/></el-table>
      <template v-if="detail.status==='DRAFT'||detail.status==='REVISION_REQUIRED'"><el-button type="primary" style="margin-top:16px" @click="openEdit(detail)">补充资料</el-button></template>
    </template>
  </el-drawer>
  <el-dialog v-model="editOpen" :title="`补充准入资料 · ${detail?.applicationNo??''}`" width="900px" :close-on-click-modal="false">
    <el-form label-position="top"><el-row :gutter="16"><el-col :span="12"><el-form-item label="采购类别 *"><el-input v-model="editForm.purchaseCategory" maxlength="100"/></el-form-item></el-col><el-col :span="12"><el-form-item label="预计年采购额"><el-input-number v-model="editForm.expectedAnnualAmount" :min="0" :precision="2" style="width:100%"/></el-form-item></el-col></el-row><el-form-item label="准入原因 *"><el-input v-model="editForm.reason" type="textarea" maxlength="500" show-word-limit/></el-form-item></el-form>
    <h3>申请材料 <el-button link type="primary" @click="addMaterial">添加选填材料</el-button></h3>
    <el-table :data="editMaterials" size="small"><el-table-column label="资料类型" min-width="140"><template #default="{row}"><el-input v-model="row.type" maxlength="64" placeholder="大写英文编码"/></template></el-table-column><el-table-column label="资料名称" min-width="140"><template #default="{row}"><el-input v-model="row.name" maxlength="100"/></template></el-table-column><el-table-column label="文件 ID" min-width="160"><template #default="{row}"><el-input v-model="row.fileId" maxlength="19" placeholder="从文件中心获取"/></template></el-table-column><el-table-column label="要求" width="70"><template #default="{row}">{{row.required?'必填':'选填'}}</template></el-table-column><el-table-column label="操作" width="70"><template #default="{row,$index}"><el-button v-if="!row.required" link type="danger" @click="removeMaterial($index)">移除</el-button></template></el-table-column></el-table>
    <template #footer><el-button @click="editOpen=false">取消</el-button><el-button type="primary" :loading="editBusy" @click="saveEdit">保存补正</el-button></template>
  </el-dialog>
</div></template>
