<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import type { components } from '@ism/api-client';
import { useSessionStore } from '../stores/session';

type Case = components['schemas']['BlacklistCase'];
type Supplier = components['schemas']['SupplierSummary'];
type Status = components['schemas']['BlacklistStatus'];
const session=useSessionStore();
const statuses: Record<Status,string>={DRAFT:'草稿',SUBMITTED:'待审核',APPROVED:'已生效',REJECTED:'已驳回',REVOKED:'已撤销'};
const rows=ref<Case[]>([]);const suppliers=ref<Supplier[]>([]);const selected=ref<Case|null>(null);
const total=ref(0);const loading=ref(false);const dialog=ref(false);const detail=ref(false);
const filter=reactive({status:'' as ''|Status,page:0,size:20});
const form=reactive({supplierId:'',reason:'',sourceRef:''});
async function load(){loading.value=true;try{const {data,error}=await session.client.GET('/supplier-blacklist',{params:{query:{status:filter.status||undefined,page:filter.page,size:filter.size}}});if(error){ElMessage.error('黑名单列表加载失败');return;}rows.value=data?.data?.items??[];total.value=data?.data?.total??0;}finally{loading.value=false;}}
async function searchSuppliers(keyword:string){const {data}=await session.client.GET('/suppliers',{params:{query:{keyword:keyword||undefined,page:0,size:100}}});suppliers.value=(data?.data?.items??[]).filter(s=>s.status!=='EXITED');}
async function open(){Object.assign(form,{supplierId:'',reason:'',sourceRef:''});await searchSuppliers('');dialog.value=true;}
async function create(){if(!form.supplierId||!form.reason.trim()){ElMessage.warning('请选择供应商并填写原因');return;}const {error}=await session.client.POST('/supplier-blacklist',{body:{supplierId:form.supplierId,reason:form.reason,sourceRef:form.sourceRef||undefined}});if(error){ElMessage.error('创建失败，请检查是否已有进行中的申请');return;}dialog.value=false;ElMessage.success('黑名单申请草稿已创建');await load();}
async function submit(row:Case){try{await ElMessageBox.confirm(`确认提交“${row.supplierName}”的黑名单申请？`,'提交审核');}catch{return;}const {error}=await session.client.POST('/supplier-blacklist/{id}/submit',{params:{path:{id:row.id}},body:{version:row.version}});if(error)ElMessage.error('提交失败，请刷新后重试');else{ElMessage.success('已提交审核');await load();}}
async function review(row:Case,decision:'APPROVE'|'REJECT'){try{const comment=(await ElMessageBox.prompt('请输入审核意见',decision==='APPROVE'?'批准黑名单':'驳回申请',{inputPattern:/\S+/})).value;const {error}=await session.client.POST('/supplier-blacklist/{id}/review',{params:{path:{id:row.id}},body:{decision,comment,version:row.version}});if(error)ElMessage.error('审核失败，请刷新后重试');else{ElMessage.success('审核完成');await load();}}catch{/* cancelled */}}
async function revoke(row:Case){try{const reason=(await ElMessageBox.prompt('请输入撤销原因','撤销黑名单',{inputPattern:/\S+/})).value;const {error}=await session.client.POST('/supplier-blacklist/{id}/revoke',{params:{path:{id:row.id}},body:{reason,version:row.version}});if(error)ElMessage.error('撤销失败，请刷新后重试');else{ElMessage.success('已撤销');await load();}}catch{/* cancelled */}}
async function show(row:Case){const {data,error}=await session.client.GET('/supplier-blacklist/{id}',{params:{path:{id:row.id}}});if(error){ElMessage.error('详情加载失败');return;}selected.value=data?.data??null;detail.value=true;}
onMounted(load);
</script>
<template><div class="page"><div class="page-heading"><div><h1>供应商黑名单</h1><p>申请、独立审核、生效阻断与有理由撤销</p></div><el-button type="primary" @click="open">发起申请</el-button></div>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="状态"><el-select v-model="filter.status" clearable style="width:150px"><el-option v-for="(name,key) in statuses" :key="key" :label="name" :value="key" /></el-select></el-form-item><el-button type="primary" @click="filter.page=0;load()">查询</el-button></el-form></el-card>
  <el-card shadow="never" class="table-card"><el-table v-loading="loading" :data="rows"><el-table-column prop="supplierName" label="供应商" min-width="180"/><el-table-column prop="reason" label="列入原因" min-width="220" show-overflow-tooltip/><el-table-column label="状态" width="105"><template #default="{row}"><el-tag :type="row.status==='APPROVED'?'danger':row.status==='REJECTED'||row.status==='REVOKED'?'info':'warning'">{{statuses[row.status as Status]}}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="创建时间" width="180"/><el-table-column label="操作" width="275"><template #default="{row}"><el-button link @click="show(row)">详情</el-button><el-button v-if="row.status==='DRAFT'" link type="primary" @click="submit(row)">提交</el-button><template v-if="row.status==='SUBMITTED'&&row.createdBy!==session.actorId"><el-button link type="success" @click="review(row,'APPROVE')">批准</el-button><el-button link type="danger" @click="review(row,'REJECT')">驳回</el-button></template><el-button v-if="row.status==='APPROVED'" link type="warning" @click="revoke(row)">撤销</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination :current-page="filter.page+1" :total="total" :page-size="filter.size" layout="total, prev, pager, next" @current-change="(page:number)=>{filter.page=page-1;load()}"/></div></el-card>
  <el-dialog v-model="dialog" title="发起黑名单申请" width="640px"><el-form label-position="top"><el-form-item label="供应商 *"><el-select v-model="form.supplierId" filterable remote :remote-method="searchSuppliers" style="width:100%"><el-option v-for="supplier in suppliers" :key="supplier.id" :label="`${supplier.name} · ${supplier.code}`" :value="supplier.id"/></el-select></el-form-item><el-form-item label="列入原因 *"><el-input v-model="form.reason" type="textarea" :rows="4" maxlength="1000" show-word-limit/></el-form-item><el-form-item label="依据编号（可选）"><el-input v-model="form.sourceRef" maxlength="200"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="create">保存草稿</el-button></template></el-dialog>
  <el-drawer v-model="detail" :title="`${selected?.supplierName??''} · 黑名单记录`" size="600px"><template v-if="selected"><p>状态：{{statuses[selected.status]}} · 申请人：{{selected.createdBy}}</p><p>原因：{{selected.reason}}</p><p v-if="selected.sourceRef">依据：{{selected.sourceRef}}</p><p v-if="selected.reviewComment">审核意见：{{selected.reviewComment}}</p><p v-if="selected.revokedReason">撤销原因：{{selected.revokedReason}}</p><el-timeline><el-timeline-item v-for="event in selected.events" :key="event.id" :timestamp="event.createdAt">{{event.action}} · {{event.fromStatus||'新建'}} → {{event.toStatus}}<p>{{event.comment}}</p><small>操作人 {{event.actorId}}</small></el-timeline-item></el-timeline></template></el-drawer>
</div></template>
