<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import type { components } from '@ism/api-client';
import { useSessionStore } from '../stores/session';

type Case = components['schemas']['BlacklistCase'];
type Supplier = components['schemas']['SupplierSummary'];
type Status = components['schemas']['BlacklistStatus'];
type RestrictionType = components['schemas']['RestrictionType'];
const session=useSessionStore();
const statuses: Record<Status,string>={DRAFT:'草稿',SUBMITTED:'待审核',APPROVED:'已生效',REJECTED:'已驳回',REVOKED:'已撤销'};
const typeNames: Record<RestrictionType,string>={BLACKLIST:'长期黑名单',TEMPORARY:'限期限制',WATCH:'观察名单'};
const rows=ref<Case[]>([]);const suppliers=ref<Supplier[]>([]);const selected=ref<Case|null>(null);
const total=ref(0);const loading=ref(false);const dialog=ref(false);const detail=ref(false);
const filter=reactive({status:'' as ''|Status,page:0,size:20});
const form=reactive({supplierId:'',reason:'',sourceRef:'',restrictionType:'BLACKLIST' as RestrictionType,effectiveFrom:'',effectiveUntil:''});
async function load(){loading.value=true;try{const {data,error}=await session.client.GET('/supplier-blacklist',{params:{query:{status:filter.status||undefined,page:filter.page,size:filter.size}}});if(error){ElMessage.error('黑名单列表加载失败');return;}rows.value=data?.data?.items??[];total.value=data?.data?.total??0;}finally{loading.value=false;}}
async function searchSuppliers(keyword:string){const {data}=await session.client.GET('/suppliers',{params:{query:{keyword:keyword||undefined,page:0,size:100}}});suppliers.value=(data?.data?.items??[]).filter(s=>s.status!=='EXITED');}
async function open(){Object.assign(form,{supplierId:'',reason:'',sourceRef:'',restrictionType:'BLACKLIST',effectiveFrom:'',effectiveUntil:''});await searchSuppliers('');dialog.value=true;}
async function create(){if(!form.supplierId||!form.reason.trim()){ElMessage.warning('请选择供应商并填写原因');return;}if(form.restrictionType==='TEMPORARY'&&(!form.effectiveFrom||!form.effectiveUntil)){ElMessage.warning('限期限制必须填写起止日期');return;}const {error}=await session.client.POST('/supplier-blacklist',{body:{supplierId:form.supplierId,reason:form.reason,sourceRef:form.sourceRef||undefined,restrictionType:form.restrictionType,effectiveFrom:form.restrictionType==='TEMPORARY'?form.effectiveFrom:undefined,effectiveUntil:form.restrictionType==='TEMPORARY'?form.effectiveUntil:undefined}});if(error){ElMessage.error('创建失败，请检查日期或是否已有进行中的申请');return;}dialog.value=false;ElMessage.success('限制申请草稿已创建');await load();}
async function submit(row:Case){try{await ElMessageBox.confirm(`确认提交“${row.supplierName}”的${typeNames[row.restrictionType]}申请？`,'提交审核');}catch{return;}const {error}=await session.client.POST('/supplier-blacklist/{id}/submit',{params:{path:{id:row.id}},body:{version:row.version}});if(error)ElMessage.error('提交失败，请刷新后重试');else{ElMessage.success('已提交审核');await load();}}
async function review(row:Case,decision:'APPROVE'|'REJECT'){try{const comment=(await ElMessageBox.prompt('请输入审核意见',decision==='APPROVE'?`批准${typeNames[row.restrictionType]}`:'驳回申请',{inputPattern:/\S+/})).value;const {error}=await session.client.POST('/supplier-blacklist/{id}/review',{params:{path:{id:row.id}},body:{decision,comment,version:row.version}});if(error)ElMessage.error('审核失败，请刷新后重试');else{ElMessage.success('审核完成');await load();}}catch{/* cancelled */}}
async function show(row:Case){const {data,error}=await session.client.GET('/supplier-blacklist/{id}',{params:{path:{id:row.id}}});if(error){ElMessage.error('详情加载失败');return;}selected.value=data?.data??null;detail.value=true;}
type Appeal=components['schemas']['RestrictionAppeal'];const appeals=ref<Appeal[]>([]),appealCase=ref<Case|null>(null),appealDialog=ref(false),appealBusy=ref(false),appealTotal=ref(0),appealPage=ref(0);const appealForm=reactive({reason:'',evidenceFileId:''});const appealStates={SUBMITTED:'待独立复核',ACCEPTED:'申诉成立（限制未解除）',REJECTED:'申诉驳回'};
async function loadAppeals(){if(!appealCase.value)return;const {data,error}=await session.client.GET('/supplier-blacklist/{caseId}/appeals',{params:{path:{caseId:appealCase.value.id},query:{page:appealPage.value,size:20}}});if(error){ElMessage.error(error.error.message);return;}appeals.value=data?.data?.items??[];appealTotal.value=data?.data?.total??0;}
async function openAppeals(row:Case){appealCase.value=row;appealPage.value=0;appeals.value=[];appealTotal.value=0;appealForm.reason='';appealForm.evidenceFileId='';await loadAppeals();appealDialog.value=true;}
async function createAppeal(){if(!appealCase.value||!appealForm.reason.trim()||!appealForm.evidenceFileId.trim()){ElMessage.warning('请填写申诉理由和证据文件 ID');return;}appealBusy.value=true;try{const {error}=await session.client.POST('/supplier-blacklist/{caseId}/appeals',{params:{path:{caseId:appealCase.value.id}},body:{...appealForm}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('申诉已提交，原限制继续有效');appealForm.reason='';appealForm.evidenceFileId='';appealPage.value=0;await loadAppeals();}}finally{appealBusy.value=false;}}
async function reviewAppeal(row:Appeal,decision:'ACCEPT'|'REJECT'){if(!appealCase.value)return;try{const comment=(await ElMessageBox.prompt('填写独立复核结论；成立也不会自动解除限制','处理申诉',{inputValidator:(value:string)=>!!value.trim()||'结论不能为空'})).value;appealBusy.value=true;const {error}=await session.client.POST('/supplier-blacklist/{caseId}/appeals/{id}/review',{params:{path:{caseId:appealCase.value.id,id:row.id}},body:{decision,comment,version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('申诉结论已记录，原限制状态不变');await loadAppeals();}}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error('处理失败，请重试');}finally{appealBusy.value=false;}}
type Lift=components['schemas']['RestrictionLift'];
const liftDialog=ref(false),liftCase=ref<Case|null>(null),liftRows=ref<Lift[]>([]),liftReady=ref<components['schemas']['LiftReadiness']>(),liftBusy=ref(false),liftPage=ref(0),liftTotal=ref(0);
const liftForm=reactive({reason:'',evidenceFileId:''});
async function loadLifts(){if(!liftCase.value)return;const params={path:{caseId:liftCase.value.id}};const [history,ready]=await Promise.all([session.client.GET('/supplier-blacklist/{caseId}/lift-applications',{params:{...params,query:{page:liftPage.value,size:20}}}),session.client.GET('/supplier-blacklist/{caseId}/lift-applications/readiness',{params})]);if(history.error||ready.error){ElMessage.error('解除记录或核验加载失败');liftReady.value=undefined;return;}liftRows.value=history.data?.data?.items??[];liftTotal.value=history.data?.data?.total??0;liftReady.value=ready.data?.data;}
async function openLifts(row:Case){liftCase.value=row;liftPage.value=0;liftRows.value=[];liftReady.value=undefined;Object.assign(liftForm,{reason:'',evidenceFileId:''});liftDialog.value=true;await loadLifts();}
async function submitLift(){if(!liftCase.value||!liftForm.reason.trim()||!liftForm.evidenceFileId.trim()){ElMessage.warning('请填写解除理由与证据文件 ID');return;}liftBusy.value=true;try{const {error}=await session.client.POST('/supplier-blacklist/{caseId}/lift-applications',{params:{path:{caseId:liftCase.value.id}},body:{...liftForm}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('解除申请已提交，原限制继续有效');await loadLifts();}}finally{liftBusy.value=false;}}
async function reviewLift(row:Lift,decision:'APPROVE'|'REJECT'){if(!liftCase.value)return;try{const comment=(await ElMessageBox.prompt('填写解除审批意见；只解除本条限制','独立解除审批',{inputPattern:/\\S+/})).value;liftBusy.value=true;const {error}=await session.client.POST('/supplier-blacklist/{caseId}/lift-applications/{id}/review',{params:{path:{caseId:liftCase.value.id,id:row.id}},body:{decision,comment,version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('审批完成');await load();liftCase.value=rows.value.find(item=>item.id===liftCase.value?.id)??liftCase.value;await loadLifts();}}catch(e){if(e!=='cancel'&&e!=='close')ElMessage.error('审批失败');}finally{liftBusy.value=false;}}
onMounted(load);
</script>
<template><div class="page"><div class="page-heading"><div><h1>风险观察与限制</h1><p>观察名单仅提示风险；限期限制与黑名单生效后阻断新增业务</p></div><el-button type="primary" @click="open">发起申请</el-button></div>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="状态"><el-select v-model="filter.status" clearable style="width:150px"><el-option v-for="(name,key) in statuses" :key="key" :label="name" :value="key" /></el-select></el-form-item><el-button type="primary" @click="filter.page=0;load()">查询</el-button></el-form></el-card>
  <el-card shadow="never" class="table-card"><el-table v-loading="loading" :data="rows"><el-table-column prop="supplierName" label="供应商" min-width="180"/><el-table-column label="类型" width="110"><template #default="{row}">{{typeNames[row.restrictionType as RestrictionType]}}</template></el-table-column><el-table-column prop="reason" label="列入原因" min-width="200" show-overflow-tooltip/><el-table-column label="状态" width="115"><template #default="{row}"><el-tag :type="row.restrictionType==='WATCH'&&row.effective?'warning':row.effective?'danger':row.status==='REJECTED'||row.status==='REVOKED'?'info':'warning'">{{row.lifted?'已解除':row.status==='APPROVED'&&!row.effective?'未生效/已到期':row.status==='APPROVED'&&row.restrictionType==='WATCH'?'观察中':statuses[row.status as Status]}}</el-tag></template></el-table-column><el-table-column prop="createdAt" label="创建时间" width="180"/><el-table-column label="操作" width="335"><template #default="{row}"><el-button link @click="show(row)">详情</el-button><el-button link type="primary" @click="openAppeals(row)">申诉</el-button><el-button v-if="row.status==='DRAFT'" link type="primary" @click="submit(row)">提交</el-button><template v-if="row.status==='SUBMITTED'&&row.createdBy!==session.actorId"><el-button link type="success" @click="review(row,'APPROVE')">批准</el-button><el-button link type="danger" @click="review(row,'REJECT')">驳回</el-button></template><el-button v-if="row.status==='APPROVED'" link type="warning" @click="openLifts(row)">解除审批</el-button></template></el-table-column></el-table><div class="pagination"><el-pagination :current-page="filter.page+1" :total="total" :page-size="filter.size" layout="total, prev, pager, next" @current-change="(page:number)=>{filter.page=page-1;load()}"/></div></el-card>
  <el-dialog v-model="dialog" title="发起风险观察或限制申请" width="640px"><el-form label-position="top"><el-form-item label="供应商 *"><el-select v-model="form.supplierId" filterable remote :remote-method="searchSuppliers" style="width:100%"><el-option v-for="supplier in suppliers" :key="supplier.id" :label="`${supplier.name} · ${supplier.code}`" :value="supplier.id"/></el-select></el-form-item><el-form-item label="类型 *"><el-select v-model="form.restrictionType" style="width:100%"><el-option label="观察名单（仅提示）" value="WATCH"/><el-option label="限期限制（阻断新增业务）" value="TEMPORARY"/><el-option label="长期黑名单（阻断新增业务）" value="BLACKLIST"/></el-select></el-form-item><el-row v-if="form.restrictionType==='TEMPORARY'" :gutter="16"><el-col :span="12"><el-form-item label="开始日期 *"><el-date-picker v-model="form.effectiveFrom" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :span="12"><el-form-item label="结束日期 *"><el-date-picker v-model="form.effectiveUntil" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col></el-row><el-form-item label="列入原因 *"><el-input v-model="form.reason" type="textarea" :rows="4" maxlength="1000" show-word-limit/></el-form-item><el-form-item label="依据编号（可选）"><el-input v-model="form.sourceRef" maxlength="200"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="create">保存草稿</el-button></template></el-dialog>
  <el-drawer v-model="detail" :title="`${selected?.supplierName??''} · 风险记录`" size="600px"><template v-if="selected"><p>类型：{{typeNames[selected.restrictionType]}} · 状态：{{statuses[selected.status]}} · 当前{{selected.lifted?'已解除':selected.effective?(selected.restrictionType==='WATCH'?'观察中':'生效'):'未生效'}}</p><p v-if="selected.effectiveFrom">期限：{{selected.effectiveFrom}} 至 {{selected.effectiveUntil}}</p><p>申请人：{{selected.createdBy}} · 原因：{{selected.reason}}</p><p v-if="selected.sourceRef">依据：{{selected.sourceRef}}</p><p v-if="selected.reviewComment">审核意见：{{selected.reviewComment}}</p><p v-if="selected.revokedReason">撤销原因：{{selected.revokedReason}}</p><el-timeline><el-timeline-item v-for="event in selected.events" :key="event.id" :timestamp="event.createdAt">{{event.action}} · {{event.fromStatus||'新建'}} → {{event.toStatus}}<p>{{event.comment}}</p><small>操作人 {{event.actorId}}</small></el-timeline-item></el-timeline></template></el-drawer>
<el-dialog v-model="appealDialog" :title="`${appealCase?.supplierName??''} · 限制申诉`" width="900px"><el-alert title="管理后台代登记。申诉提交及成立均不暂停、不自动解除原限制；解除须另行处理。" type="warning" :closable="false"/><el-form v-if="appealCase?.status==='APPROVED'&&!appealCase.lifted" label-position="top"><el-form-item label="申诉理由"><el-input v-model="appealForm.reason" type="textarea" maxlength="2000" show-word-limit/></el-form-item><el-form-item label="已上传的证据文件 ID"><el-input v-model="appealForm.evidenceFileId" maxlength="19"/></el-form-item><el-button type="primary" :loading="appealBusy" @click="createAppeal">提交申诉</el-button></el-form><el-table :data="appeals"><el-table-column prop="reason" label="申诉理由" min-width="180" show-overflow-tooltip/><el-table-column prop="evidenceFileId" label="证据文件" width="170"/><el-table-column label="状态" width="180"><template #default="{row}">{{appealStates[row.status as keyof typeof appealStates]}}</template></el-table-column><el-table-column prop="createdBy" label="提交人" width="100"/><el-table-column prop="reviewedBy" label="复核人" width="100"/><el-table-column prop="reviewComment" label="结论" min-width="160" show-overflow-tooltip/><el-table-column label="处理" width="140"><template #default="{row}"><template v-if="row.status==='SUBMITTED' && row.createdBy!==session.actorId && appealCase?.reviewedBy!==session.actorId"><el-button link type="primary" :disabled="appealBusy" @click="reviewAppeal(row,'ACCEPT')">成立</el-button><el-button link type="danger" :disabled="appealBusy" @click="reviewAppeal(row,'REJECT')">驳回</el-button></template></template></el-table-column></el-table><el-pagination :current-page="appealPage+1" :total="appealTotal" :page-size="20" layout="total, prev, pager, next" @current-change="(page:number)=>{appealPage=page-1;loadAppeals()}"/><template #footer><el-button @click="appealDialog=false">关闭</el-button></template></el-dialog>
<el-dialog v-model="liftDialog" title="独立解除审批" width="900px"><el-alert title="批准只解除本条限制；原批准记录保留，其他有效限制仍阻断业务。" type="warning" :closable="false"/><p v-if="liftReady?.observationEndsAt">观察期结束：{{liftReady.observationEndsAt}}</p><el-table :data="liftReady?.blockers??[]"><el-table-column prop="label" label="核验项"/><el-table-column prop="count" label="未完成数量"/></el-table><el-form v-if="!liftCase?.lifted" label-position="top"><el-form-item label="解除理由"><el-input v-model="liftForm.reason" type="textarea" maxlength="2000"/></el-form-item><el-form-item label="证据文件 ID"><el-input v-model="liftForm.evidenceFileId" maxlength="19"/></el-form-item><el-button :loading="liftBusy" type="primary" @click="submitLift">提交解除申请</el-button></el-form><el-table :data="liftRows"><el-table-column prop="reason" label="申请理由"/><el-table-column prop="status" label="状态"/><el-table-column prop="reviewComment" label="审批结论"/><el-table-column label="处理"><template #default="{row}"><template v-if="row.status==='SUBMITTED'&&row.createdBy!==session.actorId"><el-button link :disabled="liftBusy||!liftReady?.ready" @click="reviewLift(row,'APPROVE')">批准解除</el-button><el-button link :disabled="liftBusy" @click="reviewLift(row,'REJECT')">驳回</el-button></template></template></el-table-column></el-table><el-pagination :current-page="liftPage+1" :total="liftTotal" :page-size="20" layout="total, prev, pager, next" @current-change="(page:number)=>{liftPage=page-1;loadLifts()}"/></el-dialog>
</div></template>
