<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus, Refresh, Search } from '@element-plus/icons-vue';
import type { components } from '@ism/api-client';
import { useSessionStore } from '../stores/session';
type Row=components['schemas']['AdmissionSummary'];type Supplier=components['schemas']['SupplierSummary'];type Status=components['schemas']['AdmissionStatus'];
const session=useSessionStore();const loading=ref(false);const saving=ref(false);const dialog=ref(false);const rows=ref<Row[]>([]);const suppliers=ref<Supplier[]>([]);const total=ref(0);
const query=reactive<{keyword:string;status?:Status;page:number;size:number}>({keyword:'',status:undefined,page:0,size:20});
const form=reactive({supplierId:'',purchaseCategory:'',reason:'',expectedAnnualAmount:undefined as number|undefined,currency:'CNY',licenseFileId:''});
const statusNames={DRAFT:'草稿',SUBMITTED:'待审核',REVISION_REQUIRED:'待补正',APPROVED:'已通过',REJECTED:'已拒绝',CANCELLED:'已取消'};
async function load(){loading.value=true;const {data}=await session.client.GET('/admissions',{params:{query:{keyword:query.keyword||undefined,status:query.status,page:query.page,size:query.size}}});loading.value=false;const page=data?.data;if(!page){ElMessage.error('准入申请加载失败');return;}rows.value=page.items;total.value=page.total;}
async function openCreate(){const {data}=await session.client.GET('/suppliers',{params:{query:{page:0,size:100}}});suppliers.value=data?.data?.items??[];Object.assign(form,{supplierId:'',purchaseCategory:'',reason:'',expectedAnnualAmount:undefined,currency:'CNY',licenseFileId:''});dialog.value=true;}
async function create(){if(!form.supplierId||!form.purchaseCategory||!form.reason){ElMessage.warning('请完整填写供应商、采购类别和准入原因');return;}saving.value=true;const {error}=await session.client.POST('/admissions',{body:{supplierId:form.supplierId,purchaseCategory:form.purchaseCategory,reason:form.reason,expectedAnnualAmount:form.expectedAnnualAmount,currency:form.currency,materials:[{type:'BUSINESS_LICENSE',name:'营业执照',fileId:form.licenseFileId||undefined,required:true,provided:Boolean(form.licenseFileId),sortOrder:10}],version:0}});saving.value=false;if(error){ElMessage.error(error.error.message);return;}dialog.value=false;ElMessage.success('准入申请草稿已创建');await load();}
async function submit(row:Row){await ElMessageBox.confirm('提交后将进入准入审核，确认继续？','提交确认',{type:'warning'});const {error}=await session.client.POST('/admissions/{id}/submit',{params:{path:{id:row.id},query:{version:row.version}}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('已提交审核');await load();}}
async function review(row:Row,decision:'APPROVE'|'REQUIRE_REVISION'|'REJECT'){const label={APPROVE:'通过',REQUIRE_REVISION:'退回补正',REJECT:'拒绝'}[decision];const result=await ElMessageBox.prompt(`请输入${label}意见`,`准入审核：${label}`,{inputPattern:/.+/,inputErrorMessage:'审核意见不能为空',type:decision==='APPROVE'?'success':'warning'});const {error}=await session.client.POST('/admissions/{id}/review',{params:{path:{id:row.id}},body:{decision,comment:result.value,version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success(`审核${label}完成`);await load();}}
function pageChanged(value:number){query.page=value-1;void load();}
onMounted(load);
</script>
<template><div class="page"><div class="page-heading"><div><h1>供应商准入</h1><p>管理准入资料、补正与审核决定，通过后自动启用供应商</p></div><el-button type="primary" :icon="Plus" @click="openCreate">发起准入</el-button></div>
  <el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键词"><el-input v-model="query.keyword" clearable placeholder="申请单号、供应商" :prefix-icon="Search" @keyup.enter="query.page=0;load()"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部状态" style="width:150px"><el-option v-for="(name,key) in statusNames" :key="key" :label="name" :value="key"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="query.page=0;load()">查询</el-button><el-button :icon="Refresh" @click="query.keyword='';query.status=undefined;query.page=0;load()">重置</el-button></el-form-item></el-form></el-card>
  <el-card shadow="never" class="table-card"><el-table v-loading="loading" :data="rows" stripe><el-table-column prop="applicationNo" label="申请单号" width="190"/><el-table-column label="供应商" min-width="220"><template #default="{row}"><strong>{{row.supplierName}}</strong><div class="subtext">{{row.supplierCode}}</div></template></el-table-column><el-table-column prop="purchaseCategory" label="采购类别" min-width="150"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag :type="row.status==='APPROVED'?'success':row.status==='REJECTED'?'danger':row.status==='REVISION_REQUIRED'?'warning':''">{{statusNames[row.status as keyof typeof statusNames]}}</el-tag></template></el-table-column><el-table-column prop="submittedAt" label="提交时间" width="180"/><el-table-column label="操作" width="250" fixed="right"><template #default="{row}"><el-button v-if="row.status==='DRAFT'||row.status==='REVISION_REQUIRED'" link type="primary" @click="submit(row)">提交</el-button><template v-if="row.status==='SUBMITTED'"><el-button link type="success" @click="review(row,'APPROVE')">通过</el-button><el-button link type="warning" @click="review(row,'REQUIRE_REVISION')">补正</el-button><el-button link type="danger" @click="review(row,'REJECT')">拒绝</el-button></template></template></el-table-column></el-table><div class="pagination"><span>共 {{total}} 条</span><el-pagination background layout="prev, pager, next" :total="total" :page-size="query.size" :current-page="query.page+1" @current-change="pageChanged"/></div></el-card>
  <el-dialog v-model="dialog" title="发起供应商准入" width="680px" destroy-on-close><el-alert title="营业执照为必填资料。可先保存草稿，关联文件后再提交。" type="info" :closable="false"/><el-form label-position="top" style="margin-top:16px"><el-form-item label="供应商 *"><el-select v-model="form.supplierId" filterable style="width:100%"><el-option v-for="item in suppliers" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id"/></el-select></el-form-item><el-row :gutter="18"><el-col :span="12"><el-form-item label="采购类别 *"><el-input v-model="form.purchaseCategory" placeholder="如设备、原材料、工程服务"/></el-form-item></el-col><el-col :span="12"><el-form-item label="预计年采购额"><el-input-number v-model="form.expectedAnnualAmount" :min="0" :precision="2" style="width:100%"/></el-form-item></el-col></el-row><el-form-item label="准入原因 *"><el-input v-model="form.reason" type="textarea" :rows="3" maxlength="500" show-word-limit/></el-form-item><el-form-item label="营业执照文件 ID"><el-input v-model="form.licenseFileId" placeholder="可从文件中心选择；留空时仅保存草稿"/></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">保存草稿</el-button></template></el-dialog>
</div></template>
