<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { useRoute } from 'vue-router';
import { ElMessage, ElMessageBox } from 'element-plus';
import { Plus, Refresh, Search, Setting } from '@element-plus/icons-vue';
import type { components } from '@ism/api-client';
import { useSessionStore } from '../stores/session';
import PersonalTableViews from '../components/PersonalTableViews.vue';
import FileUploadField from '../components/FileUploadField.vue';
const columnDefinitions=[{key:'supplierName',label:'供应商',required:true,width:210},{key:'typeName',label:'资质类型',required:false,width:150},{key:'certificateNo',label:'证书编号',required:true,width:160},{key:'expiryDate',label:'有效期',required:false,width:150},{key:'status',label:'状态',required:false,width:110}];
const tableColumns=ref(columnDefinitions.map(c=>({key:c.key,visible:true,width:c.width})));
type Row=components['schemas']['QualificationSummary'];type View=components['schemas']['Qualification'];type Type=components['schemas']['QualificationType'];type Supplier=components['schemas']['SupplierSummary'];type Status=components['schemas']['QualificationStatus'];
const session=useSessionStore();const route=useRoute();const tab=ref('ledger');const loading=ref(false);const saving=ref(false);const dialog=ref(false);const typeDialog=ref(false);const rows=ref<Row[]>([]);const types=ref<Type[]>([]);const suppliers=ref<Supplier[]>([]);const total=ref(0);
const detail=ref<View|null>(null),detailOpen=ref(false),amendOpen=ref(false),amendBusy=ref(false),amendMode=ref<'edit'|'renew'>('edit');
const query=reactive<{keyword:string;status?:Status;page:number;size:number}>({keyword:'',status:undefined,page:0,size:20});
const form=reactive({supplierId:'',typeId:'',certificateNo:'',issuingAuthority:'',issueDate:'',effectiveDate:'',expiryDate:'',permanent:false,warningDays:30,fileId:''});
const amend=reactive({certificateNo:'',issuingAuthority:'',issueDate:'',effectiveDate:'',expiryDate:'',permanent:false,warningDays:30,fileId:''});
const typeForm=reactive({code:'',name:'',category:'LEGAL',validityRequired:true,defaultWarningDays:30,description:''});
const statusNames={DRAFT:'待核验',VALID:'有效',EXPIRING:'即将到期',EXPIRED:'已过期',REJECTED:'核验拒绝',REVOKED:'已撤销',SUPERSEDED:'已被替代'};
async function load(){loading.value=true;const {data}=await session.client.GET('/qualifications',{params:{query:{keyword:query.keyword||undefined,status:query.status,page:query.page,size:query.size}}});loading.value=false;const page=data?.data;if(!page){ElMessage.error('资质台账加载失败');return;}rows.value=page.items;total.value=page.total;}
async function loadTypes(){const {data}=await session.client.GET('/qualifications/types');types.value=data?.data??[];}
async function openCreate(){await Promise.all([loadTypes(),session.client.GET('/suppliers',{params:{query:{page:0,size:100}}}).then(({data})=>suppliers.value=data?.data?.items??[])]);Object.assign(form,{supplierId:'',typeId:'',certificateNo:'',issuingAuthority:'',issueDate:'',effectiveDate:'',expiryDate:'',permanent:false,warningDays:30,fileId:''});dialog.value=true;}
async function create(){if(!form.supplierId||!form.typeId||!form.certificateNo||!form.fileId){ElMessage.warning('请填写供应商、资质类型、证书编号和文件 ID');return;}saving.value=true;const {error}=await session.client.POST('/qualifications',{body:{supplierId:form.supplierId,typeId:form.typeId,certificateNo:form.certificateNo,issuingAuthority:form.issuingAuthority||undefined,issueDate:form.issueDate||undefined,effectiveDate:form.effectiveDate||undefined,expiryDate:form.permanent?undefined:form.expiryDate||undefined,permanent:form.permanent,warningDays:form.warningDays,fileId:form.fileId,version:0}});saving.value=false;if(error){ElMessage.error(error.error.message);return;}dialog.value=false;ElMessage.success('资质草稿已创建');await load();}
async function fetchDetail(id:string){const {data,error}=await session.client.GET('/qualifications/{id}',{params:{path:{id}}});if(error||!data?.data){ElMessage.error('证照不存在或当前账号无权查看');return null;}return data.data;}
async function showDetail(id:string){const value=await fetchDetail(id);if(!value)return;detail.value=value;detailOpen.value=true;}
async function openAmend(id:string,mode:'edit'|'renew'){const value=await fetchDetail(id);if(!value)return;if(mode==='edit'&&value.status!=='DRAFT'){ElMessage.warning('只有待核验的证照可以编辑');return;}if(mode==='renew'&&!['VALID','EXPIRING','EXPIRED'].includes(value.status)){ElMessage.warning('当前证照不可换证');return;}
  detail.value=value;amendMode.value=mode;Object.assign(amend,{certificateNo:mode==='renew'?'':value.certificateNo,issuingAuthority:value.issuingAuthority??'',issueDate:value.issueDate??'',effectiveDate:value.effectiveDate??'',expiryDate:value.expiryDate??'',permanent:value.permanent,warningDays:value.warningDays,fileId:mode==='renew'?'':value.fileId});amendOpen.value=true;}
async function saveAmend(){const current=detail.value;if(!current)return;if(!amend.certificateNo.trim()||!/^[1-9][0-9]{0,18}$/.test(amend.fileId.trim())){ElMessage.warning('请填写证书编号和有效的文件 ID');return;}if(!amend.permanent&&!amend.expiryDate){ElMessage.warning('请填写到期日期，或选择长期有效');return;}if(amend.expiryDate&&amend.effectiveDate&&amend.effectiveDate>amend.expiryDate&&!amend.permanent){ElMessage.warning('生效日期不能晚于到期日期');return;}
  const body={supplierId:current.supplierId,typeId:current.typeId,certificateNo:amend.certificateNo.trim(),issuingAuthority:amend.issuingAuthority.trim()||undefined,issueDate:amend.issueDate||undefined,effectiveDate:amend.effectiveDate||undefined,expiryDate:amend.permanent?undefined:amend.expiryDate||undefined,permanent:amend.permanent,warningDays:amend.warningDays,fileId:amend.fileId.trim(),version:current.version};
  amendBusy.value=true;try{const response=amendMode.value==='edit'?await session.client.PUT('/qualifications/{id}',{params:{path:{id:current.id}},body}):await session.client.POST('/qualifications/{id}/renew',{params:{path:{id:current.id}},body});if(response.error){ElMessage.error(response.error.error.message);return;}amendOpen.value=false;ElMessage.success(amendMode.value==='edit'?'证照资料已保存':'换证草稿已建立');await load();if(amendMode.value==='renew'&&response.data?.data){detail.value=response.data.data;detailOpen.value=true;}else if(detailOpen.value)detail.value=await fetchDetail(current.id);}
  catch{ElMessage.error('保存失败，请刷新重试');}finally{amendBusy.value=false;}}
async function verify(row:Row,decision:'APPROVE'|'REJECT'){const label=decision==='APPROVE'?'通过':'拒绝';const result=await ElMessageBox.prompt(`请输入核验${label}意见`,'资质核验',{inputPattern:/.+/,inputErrorMessage:'核验意见不能为空',type:decision==='APPROVE'?'success':'warning'});const {error}=await session.client.POST('/qualifications/{id}/verify',{params:{path:{id:row.id}},body:{decision,comment:result.value,version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success(`核验${label}`);await load();}}
async function revoke(row:Row){const result=await ElMessageBox.prompt('请输入撤销原因','撤销资质',{inputPattern:/.+/,inputErrorMessage:'撤销原因不能为空',type:'warning'});const {error}=await session.client.POST('/qualifications/{id}/revoke',{params:{path:{id:row.id}},body:{reason:result.value,version:row.version}});if(error)ElMessage.error(error.error.message);else{ElMessage.success('资质已撤销');await load();}}
function openType(){Object.assign(typeForm,{code:'',name:'',category:'LEGAL',validityRequired:true,defaultWarningDays:30,description:''});typeDialog.value=true;}
async function createType(){if(!typeForm.code||!typeForm.name){ElMessage.warning('请填写类型编码和名称');return;}const {error}=await session.client.POST('/qualifications/types',{body:{...typeForm,status:'ACTIVE',version:0}});if(error){ElMessage.error(error.error.message);return;}typeDialog.value=false;ElMessage.success('资质类型已创建');await loadTypes();}
function tagType(status:Status){return status==='VALID'?'success':status==='EXPIRING'?'warning':status==='EXPIRED'||status==='REJECTED'||status==='REVOKED'?'danger':'info';}
function pageChanged(value:number){query.page=value-1;void load();}
onMounted(async()=>{query.keyword=typeof route.query.keyword==='string'?route.query.keyword.slice(0,100):'';await Promise.all([load(),loadTypes()]);const id=route.query.qualificationId;if(typeof id==='string'&&/^[1-9][0-9]{0,18}$/.test(id))await showDetail(id);});
</script>
<template><div class="page"><div class="page-heading"><div><h1>资质证照</h1><p>统一维护供应商证照核验、有效期预警、撤销与换证记录</p></div><div><el-button :icon="Setting" @click="tab='types'">类型配置</el-button><el-button type="primary" :icon="Plus" @click="openCreate">新增证照</el-button></div></div>
  <el-tabs v-model="tab"><el-tab-pane label="证照台账" name="ledger"><el-card shadow="never" class="filter-card"><el-form inline><el-form-item label="关键词"><el-input v-model="query.keyword" clearable placeholder="供应商、证书编号" :prefix-icon="Search" @keyup.enter="query.page=0;load()"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable placeholder="全部状态" style="width:150px"><el-option v-for="(name,key) in statusNames" :key="key" :label="name" :value="key"/></el-select></el-form-item><el-form-item><el-button type="primary" @click="query.page=0;load()">查询</el-button><el-button :icon="Refresh" @click="query.keyword='';query.status=undefined;query.page=0;load()">重置</el-button></el-form-item></el-form></el-card>
    <el-card shadow="never" class="table-card"><PersonalTableViews table-key="supplier.qualification" :defaults="columnDefinitions" @change="tableColumns=$event"/><el-table :key="tableColumns.filter(c=>c.visible).map(c=>c.key+':'+c.width).join('|')" v-loading="loading" :data="rows" stripe><el-table-column v-for="column in tableColumns.filter(c=>c.visible)" :key="column.key" :label="columnDefinitions.find(c=>c.key===column.key)?.label" :width="column.width"><template #default="{row}"><template v-if="column.key==='supplierName'"><strong>{{row.supplierName}}</strong><div class="subtext">{{row.supplierCode}}</div></template><template v-else-if="column.key==='expiryDate'">{{row.permanent?'长期有效':row.expiryDate||'—'}}</template><el-tag v-else-if="column.key==='status'" :type="tagType(row.status)">{{statusNames[row.status as keyof typeof statusNames]}}</el-tag><template v-else>{{row[column.key as keyof Row]??'—'}}</template></template></el-table-column><el-table-column label="操作" width="300" fixed="right"><template #default="{row}"><el-button link @click="showDetail(row.id)">详情</el-button><el-button v-if="row.status==='DRAFT'" link type="primary" @click="openAmend(row.id,'edit')">编辑</el-button><template v-if="row.status==='DRAFT'"><el-button link type="success" @click="verify(row,'APPROVE')">通过</el-button><el-button link type="danger" @click="verify(row,'REJECT')">拒绝</el-button></template><template v-if="row.status==='VALID'||row.status==='EXPIRING'||row.status==='EXPIRED'"><el-button link type="primary" @click="openAmend(row.id,'renew')">换证</el-button><el-button link type="danger" @click="revoke(row)">撤销</el-button></template></template></el-table-column></el-table><div class="pagination"><span>共 {{total}} 条</span><el-pagination background layout="prev, pager, next" :total="total" :page-size="query.size" :current-page="query.page+1" @current-change="pageChanged"/></div></el-card></el-tab-pane>
    <el-tab-pane label="资质类型" name="types"><div style="margin-bottom:16px;text-align:right"><el-button type="primary" :icon="Plus" @click="openType">新增类型</el-button></div><el-card shadow="never"><el-table :data="types"><el-table-column prop="code" label="编码"/><el-table-column prop="name" label="名称"/><el-table-column prop="category" label="分类"/><el-table-column label="有效期要求"><template #default="{row}">{{row.validityRequired?'必须填写':'可长期有效'}}</template></el-table-column><el-table-column prop="defaultWarningDays" label="默认预警天数"/><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.status==='ACTIVE'?'success':'info'">{{row.status==='ACTIVE'?'启用':'停用'}}</el-tag></template></el-table-column></el-table></el-card></el-tab-pane></el-tabs>
  <el-dialog v-model="dialog" title="新增供应商证照" width="720px"><el-form label-position="top"><el-row :gutter="18"><el-col :span="12"><el-form-item label="供应商 *"><el-select v-model="form.supplierId" filterable style="width:100%"><el-option v-for="item in suppliers" :key="item.id" :label="`${item.code} · ${item.name}`" :value="item.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="资质类型 *"><el-select v-model="form.typeId" style="width:100%"><el-option v-for="item in types.filter(x=>x.status==='ACTIVE')" :key="item.id" :label="item.name" :value="item.id"/></el-select></el-form-item></el-col><el-col :span="12"><el-form-item label="证书编号 *"><el-input v-model="form.certificateNo"/></el-form-item></el-col><el-col :span="12"><el-form-item label="发证机关"><el-input v-model="form.issuingAuthority"/></el-form-item></el-col><el-col :span="8"><el-form-item label="签发日期"><el-date-picker v-model="form.issueDate" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="生效日期"><el-date-picker v-model="form.effectiveDate" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="到期日期"><el-date-picker v-model="form.expiryDate" value-format="YYYY-MM-DD" :disabled="form.permanent" style="width:100%"/></el-form-item></el-col><el-col :span="12"><el-form-item label="证照文件 ID *"><FileUploadField v-model="form.fileId"/></el-form-item></el-col><el-col :span="6"><el-form-item label="预警天数"><el-input-number v-model="form.warningDays" :min="0" :max="3650"/></el-form-item></el-col><el-col :span="6"><el-form-item label="长期有效"><el-switch v-model="form.permanent"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" :loading="saving" @click="create">保存草稿</el-button></template></el-dialog>
  <el-dialog v-model="typeDialog" title="新增资质类型" width="560px"><el-form label-position="top"><el-row :gutter="18"><el-col :span="12"><el-form-item label="类型编码 *"><el-input v-model="typeForm.code" placeholder="如 SAFETY_LICENSE"/></el-form-item></el-col><el-col :span="12"><el-form-item label="类型名称 *"><el-input v-model="typeForm.name"/></el-form-item></el-col><el-col :span="12"><el-form-item label="分类"><el-input v-model="typeForm.category"/></el-form-item></el-col><el-col :span="12"><el-form-item label="默认预警天数"><el-input-number v-model="typeForm.defaultWarningDays" :min="0" :max="3650"/></el-form-item></el-col></el-row><el-form-item><el-checkbox v-model="typeForm.validityRequired">必须填写有效期</el-checkbox></el-form-item><el-form-item label="说明"><el-input v-model="typeForm.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="typeDialog=false">取消</el-button><el-button type="primary" @click="createType">保存</el-button></template></el-dialog>
  <el-drawer v-model="detailOpen" :title="`证照详情 · ${detail?.certificateNo??''}`" size="720px"><template v-if="detail"><el-descriptions :column="2" border>
    <el-descriptions-item label="供应商">{{detail.supplierName}}（{{detail.supplierCode}}）</el-descriptions-item><el-descriptions-item label="资质类型">{{detail.typeName}}</el-descriptions-item><el-descriptions-item label="状态">{{statusNames[detail.status]}}</el-descriptions-item><el-descriptions-item label="证书编号">{{detail.certificateNo}}</el-descriptions-item><el-descriptions-item label="发证机关">{{detail.issuingAuthority??'—'}}</el-descriptions-item><el-descriptions-item label="文件 ID">{{detail.fileId}}</el-descriptions-item><el-descriptions-item label="签发日期">{{detail.issueDate??'—'}}</el-descriptions-item><el-descriptions-item label="生效日期">{{detail.effectiveDate??'—'}}</el-descriptions-item><el-descriptions-item label="有效期">{{detail.permanent?'长期有效':detail.expiryDate??'—'}}</el-descriptions-item><el-descriptions-item label="预警天数">{{detail.warningDays}}</el-descriptions-item><el-descriptions-item label="核验意见" :span="2">{{detail.verificationComment??'—'}}</el-descriptions-item><el-descriptions-item v-if="detail.revokedReason" label="撤销原因" :span="2">{{detail.revokedReason}}</el-descriptions-item><el-descriptions-item v-if="detail.parentQualificationId" label="上一本证照" :span="2"><el-button link type="primary" @click="showDetail(detail.parentQualificationId!)">{{detail.parentQualificationId}}</el-button></el-descriptions-item>
  </el-descriptions><div style="margin-top:16px"><el-button v-if="detail.status==='DRAFT'" type="primary" @click="openAmend(detail.id,'edit')">编辑资料</el-button><el-button v-if="detail.status==='VALID'||detail.status==='EXPIRING'||detail.status==='EXPIRED'" type="primary" @click="openAmend(detail.id,'renew')">发起换证</el-button></div></template></el-drawer>
  <el-dialog v-model="amendOpen" :title="amendMode==='renew'?'发起换证':'编辑证照资料'" width="720px" :close-on-click-modal="false"><el-alert v-if="amendMode==='renew'" title="保存后创建新草稿并将原证照标记为已被替代；新证照仍需独立核验。" type="warning" :closable="false" style="margin-bottom:16px"/><el-form label-position="top"><el-row :gutter="16"><el-col :span="12"><el-form-item label="证书编号 *"><el-input v-model="amend.certificateNo" maxlength="100"/></el-form-item></el-col><el-col :span="12"><el-form-item label="发证机关"><el-input v-model="amend.issuingAuthority" maxlength="200"/></el-form-item></el-col><el-col :span="8"><el-form-item label="签发日期"><el-date-picker v-model="amend.issueDate" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="生效日期"><el-date-picker v-model="amend.effectiveDate" value-format="YYYY-MM-DD" style="width:100%"/></el-form-item></el-col><el-col :span="8"><el-form-item label="到期日期"><el-date-picker v-model="amend.expiryDate" value-format="YYYY-MM-DD" :disabled="amend.permanent" style="width:100%"/></el-form-item></el-col><el-col :span="12"><el-form-item label="文件 ID *"><FileUploadField v-model="amend.fileId"/></el-form-item></el-col><el-col :span="6"><el-form-item label="预警天数"><el-input-number v-model="amend.warningDays" :min="0" :max="3650"/></el-form-item></el-col><el-col :span="6"><el-form-item label="长期有效"><el-switch v-model="amend.permanent"/></el-form-item></el-col></el-row></el-form><template #footer><el-button @click="amendOpen=false">取消</el-button><el-button type="primary" :loading="amendBusy" @click="saveAmend">{{amendMode==='renew'?'建立换证草稿':'保存资料'}}</el-button></template></el-dialog>
</div></template>
