package io.github.turbopro.ism.safety;
import io.github.turbopro.ism.common.infrastructure.tenant.TenantScopedMapper;import org.apache.ibatis.annotations.*;import java.time.*;import java.util.*;
@Mapper public interface SafetyIssueMapper extends TenantScopedMapper{
 @Select("SELECT COUNT(*) total,COALESCE(SUM(CASE WHEN status<>'CLOSED' THEN 1 ELSE 0 END),0) open_count FROM saf_issue WHERE tenant_id=#{tenantId} AND supplier_id=#{supplierId} AND discovered_at>=#{start} AND discovered_at<DATE_ADD(#{end}, INTERVAL 1 DAY)")
 FactRow performanceFacts(long tenantId,long supplierId,LocalDate start,LocalDate end);
 record FactRow(int total,int openCount){}
 String S="<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND x.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'PROJECT_SET'\"> AND x.project_id IN <foreach collection='projectIds' item='p' open='(' separator=',' close=')'>#{p}</foreach></when><when test=\"scopeType == 'CREATED'\"> AND x.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>";String F="<if test='keyword != null'> AND (x.issue_no LIKE #{keyword} ESCAPE '=' OR x.title LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')</if><if test='status != null'> AND x.status=#{status}</if>";
 @Select("SELECT p.organization_id,p.supplier_id FROM prj_project p JOIN sup_supplier s ON s.id=p.supplier_id AND s.tenant_id=p.tenant_id WHERE p.tenant_id=#{tenantId} AND p.id=#{projectId} AND p.status IN ('PLANNED','ACTIVE','SUSPENDED') AND s.status='ACTIVE' AND s.deleted=0 FOR UPDATE")SafetyIssueModels.ProjectRef activeProject(long tenantId,long projectId);
 @Select("<script>SELECT COUNT(*) FROM saf_issue x JOIN sup_supplier s ON s.id=x.supplier_id WHERE x.tenant_id=#{tenantId}"+S+F+"</script>")long count(long tenantId,String keyword,String status,String scopeType,Set<Long>organizationIds,Set<Long>projectIds,long actorId);
 @Select("<script>SELECT x.*,p.project_code,p.project_name,s.supplier_code,s.supplier_name FROM saf_issue x JOIN prj_project p ON p.id=x.project_id JOIN sup_supplier s ON s.id=x.supplier_id WHERE x.tenant_id=#{tenantId}"+S+F+" ORDER BY x.updated_at DESC LIMIT #{size} OFFSET #{offset}</script>")List<SafetyIssueModels.Row> list(long tenantId,String keyword,String status,String scopeType,Set<Long>organizationIds,Set<Long>projectIds,long actorId,int offset,int size);
 @Select("SELECT x.*,p.project_code,p.project_name,s.supplier_code,s.supplier_name FROM saf_issue x JOIN prj_project p ON p.id=x.project_id JOIN sup_supplier s ON s.id=x.supplier_id WHERE x.tenant_id=#{tenantId} AND x.id=#{id}")SafetyIssueModels.Row get(long tenantId,long id);
 @Insert("INSERT INTO saf_issue(id,tenant_id,organization_id,project_id,supplier_id,issue_no,title,category,severity,description,location,discovered_at,deadline,responsible_user_id,created_by,updated_by) VALUES(#{id},#{tenantId},#{org},#{projectId},#{supplierId},#{no},#{title},#{category},#{severity},#{description},#{location},#{discoveredAt},#{deadline},#{responsible},#{actor},#{actor})")int insert(long id,long tenantId,long org,long projectId,long supplierId,String no,String title,String category,String severity,String description,String location,LocalDateTime discoveredAt,LocalDate deadline,long responsible,long actor);
 @Update("UPDATE saf_issue SET status='PENDING_REVIEW',rectification_note=#{note},rectification_file_id=#{fileId},submitted_at=CURRENT_TIMESTAMP(3),verification_result=NULL,verification_comment=NULL,verified_by=NULL,verified_at=NULL,updated_by=#{actor},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status='OPEN' AND version=#{version}")int rectify(long tenantId,long id,String note,long fileId,long actor,int version);
 @Update("UPDATE saf_issue SET status=CASE WHEN #{decision}='PASS' THEN 'CLOSED' ELSE 'OPEN' END,verification_result=#{decision},verification_comment=#{comment},verified_by=#{actor},verified_at=CURRENT_TIMESTAMP(3),updated_by=#{actor},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status='PENDING_REVIEW' AND version=#{version}")int verify(long tenantId,long id,String decision,String comment,long actor,int version);
}
