package io.github.turbopro.ism.safety;
import io.github.turbopro.ism.common.api.error.*;import io.github.turbopro.ism.common.infrastructure.authorization.*;import io.github.turbopro.ism.common.infrastructure.tenant.TenantContext;import io.github.turbopro.ism.operation.*;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service public class SafetyIssueService{private final SafetyIssueMapper mapper;private final OperationIdGenerator ids;private final AuditService audit;public SafetyIssueService(SafetyIssueMapper m,OperationIdGenerator i,AuditService a){mapper=m;ids=i;audit=a;}
 public SafetyIssueModels.Page list(String keyword,String status,int page,int size){var i=TenantContext.require();var s=AuthorizationContext.require().dataScope("safety:issue");String k=like(keyword),st=parse(status);return new SafetyIssueModels.Page(mapper.count(i.tenantId(),k,st,s.type().name(),s.organizationIds(),s.projectIds(),i.actorId()),page,size,mapper.list(i.tenantId(),k,st,s.type().name(),s.organizationIds(),s.projectIds(),i.actorId(),Math.multiplyExact(page,size),size).stream().map(this::view).toList());}
 @Transactional public SafetyIssueModels.View create(SafetyIssueModels.Create c){if(c.version()!=0)throw validation("新建隐患 version 必须为 0");if(c.discoveredAt().isAfter(LocalDateTime.now()))throw validation("发现时间不能晚于当前时间");if(c.deadline().isBefore(c.discoveredAt().toLocalDate()))throw validation("整改期限不能早于发现日期");var i=TenantContext.require();long project=id(c.projectId(),"项目 ID 无效");var p=mapper.activeProject(i.tenantId(),project);if(p==null)throw validation("项目不存在、已结束或供应商无效");requireScope(p.organizationId(),project,i.actorId());long issue=ids.nextId();try{mapper.insert(issue,i.tenantId(),p.organizationId(),project,p.supplierId(),c.issueNo(),c.title().trim(),c.category().name(),c.severity().name(),c.description().trim(),blank(c.location()),c.discoveredAt(),c.deadline(),id(c.responsibleUserId(),"责任人 ID 无效"),i.actorId());}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"隐患编号已存在");}audit("SAFETY_ISSUE_CREATE",issue,"OPEN");return view(mapper.get(i.tenantId(),issue));}
 @Transactional public SafetyIssueModels.View rectify(long id,SafetyIssueModels.Rectify c){var b=require(id);if(b.status().equals("CLOSED"))throw validation("已关闭隐患不能再次整改");var i=TenantContext.require();if(mapper.rectify(i.tenantId(),id,c.note().trim(),id(c.fileId(),"整改附件 ID 无效"),i.actorId(),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);audit("SAFETY_ISSUE_RECTIFY",id,"PENDING_REVIEW");return view(mapper.get(i.tenantId(),id));}
 @Transactional public SafetyIssueModels.View verify(long id,SafetyIssueModels.Verify c){require(id);var i=TenantContext.require();if(mapper.verify(i.tenantId(),id,c.decision().name(),c.comment().trim(),i.actorId(),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);audit("SAFETY_ISSUE_VERIFY",id,c.decision()==SafetyIssueModels.Decision.PASS?"CLOSED":"OPEN");return view(mapper.get(i.tenantId(),id));}
 private SafetyIssueModels.Row require(long id){var i=TenantContext.require();var r=mapper.get(i.tenantId(),id);if(r==null||!AuthorizationContext.require().dataScope("safety:issue").allows(new DataTarget(r.organizationId(),r.projectId(),r.responsibleUserId(),r.createdBy()),i.actorId()))throw new ApiException(CommonErrorCode.NOT_FOUND);return r;}private void requireScope(long org,long project,long actor){if(!AuthorizationContext.require().dataScope("safety:issue").allows(new DataTarget(org,project,actor,actor),actor))throw new ApiException(CommonErrorCode.FORBIDDEN);}
 private SafetyIssueModels.View view(SafetyIssueModels.Row r){return new SafetyIssueModels.View(""+r.id(),""+r.organizationId(),""+r.projectId(),""+r.supplierId(),r.projectCode(),r.projectName(),r.supplierCode(),r.supplierName(),r.issueNo(),r.title(),SafetyIssueModels.Category.valueOf(r.category()),SafetyIssueModels.Severity.valueOf(r.severity()),r.description(),r.location(),r.discoveredAt(),r.deadline(),""+r.responsibleUserId(),SafetyIssueModels.Status.valueOf(r.status()),r.rectificationNote(),r.rectificationFileId()==null?null:""+r.rectificationFileId(),r.submittedAt(),r.verificationResult(),r.verificationComment(),r.verifiedBy()==null?null:""+r.verifiedBy(),r.verifiedAt(),!r.status().equals("CLOSED")&&r.deadline().isBefore(LocalDate.now()),r.version(),r.createdAt(),r.updatedAt());}
 private String parse(String s){if(s==null||s.isBlank())return null;try{return SafetyIssueModels.Status.valueOf(s).name();}catch(Exception e){throw validation("隐患状态无效");}}private String like(String s){return s==null||s.isBlank()?null:"%"+s.trim().replace("=","==").replace("%","=%").replace("_","=_")+"%";}private long id(String s,String m){try{return Long.parseLong(s);}catch(Exception e){throw validation(m);}}private String blank(String s){return s==null||s.isBlank()?null:s.trim();}private ApiException validation(String m){return new ApiException(CommonErrorCode.VALIDATION_FAILED,m);}private void audit(String action,long id,String status){audit.append(new AuditService.AuditCommand(action,"SAFETY_ISSUE",id,null,Map.of(),Map.of("status",status),null,null));}}
