package io.github.turbopro.ism.safety;
import jakarta.validation.constraints.*;import java.time.*;import java.util.List;
public final class SafetyIssueModels{private SafetyIssueModels(){}public enum Category{BEHAVIOR,EQUIPMENT,ENVIRONMENT,MANAGEMENT,OTHER}public enum Severity{LOW,MEDIUM,HIGH,CRITICAL}public enum Status{OPEN,PENDING_REVIEW,CLOSED}public enum Decision{PASS,REJECT}
 public record Create(@NotBlank@Pattern(regexp="[A-Z0-9][A-Z0-9_-]{1,63}")String issueNo,@NotBlank@Size(max=200)String title,@NotBlank String projectId,@NotNull Category category,@NotNull Severity severity,@NotBlank@Size(max=2000)String description,@Size(max=300)String location,@NotNull LocalDateTime discoveredAt,@NotNull LocalDate deadline,@NotBlank String responsibleUserId,@NotNull@PositiveOrZero Integer version){}
 public record Rectify(@NotBlank@Size(max=2000)String note,@NotBlank String fileId,@NotNull@PositiveOrZero Integer version){}public record Verify(@NotNull Decision decision,@NotBlank@Size(max=1000)String comment,@NotNull@PositiveOrZero Integer version){}
 public record ProjectRef(long organizationId,long supplierId){}
 public record Row(long id,long organizationId,long projectId,long supplierId,String projectCode,String projectName,String supplierCode,String supplierName,String issueNo,String title,String category,String severity,String description,String location,LocalDateTime discoveredAt,LocalDate deadline,long responsibleUserId,String status,String rectificationNote,Long rectificationFileId,LocalDateTime submittedAt,String verificationResult,String verificationComment,Long verifiedBy,LocalDateTime verifiedAt,long createdBy,int version,LocalDateTime createdAt,LocalDateTime updatedAt){}
 public record View(String id,String organizationId,String projectId,String supplierId,String projectCode,String projectName,String supplierCode,String supplierName,String issueNo,String title,Category category,Severity severity,String description,String location,LocalDateTime discoveredAt,LocalDate deadline,String responsibleUserId,Status status,String rectificationNote,String rectificationFileId,LocalDateTime submittedAt,String verificationResult,String verificationComment,String verifiedBy,LocalDateTime verifiedAt,boolean overdue,int version,LocalDateTime createdAt,LocalDateTime updatedAt){}public record Page(long total,int page,int size,List<View>items){}
}
