package io.github.turbopro.ism.workflow;

import io.github.turbopro.ism.common.api.error.*;
import io.github.turbopro.ism.common.infrastructure.tenant.TenantContext;
import io.github.turbopro.ism.operation.OperationIdGenerator;
import org.flowable.engine.*;
import org.flowable.task.api.Task;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@Service
public class WorkflowService {
    private static final Set<String> RESERVED_VARIABLES=Set.of("_ismTenantId","_ismStarterId","_ismBusinessType","_ismBusinessId");
    private final WorkflowMapper mapper;private final OperationIdGenerator ids;private final BpmnPolicyValidator validator;private final RepositoryService repository;private final RuntimeService runtime;private final TaskService tasks;
    public WorkflowService(WorkflowMapper mapper,OperationIdGenerator ids,BpmnPolicyValidator validator,RepositoryService repository,RuntimeService runtime,TaskService tasks){this.mapper=mapper;this.ids=ids;this.validator=validator;this.repository=repository;this.runtime=runtime;this.tasks=tasks;}
    public List<WorkflowModels.DefinitionView> definitions(){return mapper.definitions(TenantContext.require().tenantId()).stream().map(this::view).toList();}
    public WorkflowModels.DefinitionView definition(long id){return view(require(id));}
    @Transactional public WorkflowModels.DefinitionView create(WorkflowModels.SaveDefinition command){if(command.version()!=0)throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"新建流程的 version 必须为 0");validator.validate(command.bpmnXml(),command.code());var i=TenantContext.require();long id=ids.nextId();try{mapper.insertDefinition(id,i.tenantId(),i.actorId(),command.code(),command.name().trim(),command.businessType(),command.bpmnXml());}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"流程编码已存在");}return view(require(id));}
    @Transactional public WorkflowModels.DefinitionView update(long id,WorkflowModels.SaveDefinition command){var row=require(id);if(!row.definitionCode().equals(command.code()))throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"流程编码发布后不可修改");validator.validate(command.bpmnXml(),command.code());var i=TenantContext.require();if(mapper.updateDefinition(i.tenantId(),i.actorId(),id,command.name().trim(),command.businessType(),command.bpmnXml(),Objects.requireNonNull(command.version()))!=1)throw new ApiException(CommonErrorCode.CONFLICT);return view(require(id));}
    @Transactional public WorkflowModels.DefinitionView publish(long id,int version){var row=require(id);if(row.version()!=version)throw new ApiException(CommonErrorCode.CONFLICT);validator.validate(row.draftBpmn(),row.definitionCode());var i=TenantContext.require();int next=row.currentVersion()+1;try{var deployment=repository.createDeployment().tenantId(Long.toString(i.tenantId())).name(row.definitionName()+" v"+next).addString(row.definitionCode()+".bpmn20.xml",row.draftBpmn()).deploy();var process=repository.createProcessDefinitionQuery().deploymentId(deployment.getId()).singleResult();if(process==null)throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"部署后未找到流程定义");mapper.insertVersion(ids.nextId(),i.tenantId(),i.actorId(),id,next,row.draftBpmn(),deployment.getId(),process.getId());if(mapper.markPublished(i.tenantId(),i.actorId(),id,next,version)!=1)throw new ApiException(CommonErrorCode.CONFLICT);}catch(org.flowable.common.engine.api.FlowableException e){throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"BPMN 部署校验失败: "+e.getMessage());}return view(require(id));}
    @Transactional public WorkflowModels.InstanceView start(WorkflowModels.StartInstance command){var i=TenantContext.require();var definition=mapper.definitionByCode(i.tenantId(),command.definitionCode());if(definition==null||definition.currentVersion()<1)throw new ApiException(CommonErrorCode.NOT_FOUND,"流程定义不存在或尚未发布");var published=mapper.definitionVersion(i.tenantId(),definition.id(),definition.currentVersion());Map<String,Object> variables=safeVariables(command.variables());variables.put("_ismTenantId",i.tenantId());variables.put("_ismStarterId",i.actorId());variables.put("_ismBusinessType",definition.businessType());variables.put("_ismBusinessId",command.businessId());var process=runtime.startProcessInstanceById(published.processDefinitionId(),command.businessId(),variables);long id=ids.nextId();mapper.insertInstance(id,i.tenantId(),definition.id(),published.definitionVersion(),process.getId(),i.actorId(),definition.businessType(),command.businessId());return instance(mapper.instanceByProcess(i.tenantId(),process.getId()));}
    public List<WorkflowModels.TaskView> myTasks(){var i=TenantContext.require();return tasks.createTaskQuery().taskTenantId(Long.toString(i.tenantId())).taskCandidateOrAssigned(Long.toString(i.actorId())).active().orderByTaskCreateTime().desc().listPage(0,200).stream().map(this::task).toList();}
    @Transactional public WorkflowModels.TaskView claim(String taskId){var i=TenantContext.require();Task task=requireTask(taskId,i.tenantId());if(task.getAssignee()!=null&&!task.getAssignee().equals(Long.toString(i.actorId())))throw new ApiException(CommonErrorCode.FORBIDDEN,"待办已由其他用户认领");if(task.getAssignee()==null){long candidates=tasks.createTaskQuery().taskId(taskId).taskCandidateUser(Long.toString(i.actorId())).count();if(candidates!=1)throw new ApiException(CommonErrorCode.FORBIDDEN,"当前用户不是该待办候选人");tasks.claim(taskId,Long.toString(i.actorId()));}return task(tasks.createTaskQuery().taskId(taskId).singleResult());}
    @Transactional public void complete(String taskId,WorkflowModels.CompleteTask command){var i=TenantContext.require();Task task=requireTask(taskId,i.tenantId());if(!Long.toString(i.actorId()).equals(task.getAssignee()))throw new ApiException(CommonErrorCode.FORBIDDEN,"请先认领待办");if(command.comment()!=null&&!command.comment().isBlank())tasks.addComment(taskId,task.getProcessInstanceId(),command.comment().trim());tasks.complete(taskId,Map.of("decision",command.decision().name()));if(runtime.createProcessInstanceQuery().processInstanceId(task.getProcessInstanceId()).count()==0)mapper.finishInstance(i.tenantId(),task.getProcessInstanceId(),"COMPLETED",command.decision()==WorkflowModels.Decision.APPROVE?"APPROVED":"REJECTED");}
    private Task requireTask(String taskId,long tenantId){Task task=tasks.createTaskQuery().taskId(taskId).taskTenantId(Long.toString(tenantId)).active().singleResult();if(task==null)throw new ApiException(CommonErrorCode.NOT_FOUND);return task;}
    private Map<String,Object> safeVariables(Map<String,Object> input){Map<String,Object> result=new HashMap<>();if(input==null)return result;if(input.size()>50)throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"流程变量不能超过 50 个");for(var e:input.entrySet()){if(RESERVED_VARIABLES.contains(e.getKey())||!e.getKey().matches("[A-Za-z][A-Za-z0-9_]{0,63}"))throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"流程变量名无效");Object value=e.getValue();if(value!=null&&!(value instanceof String||value instanceof Number||value instanceof Boolean))throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"流程变量只支持字符串、数字和布尔值");if(value instanceof String s&&s.length()>1000)throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"流程变量值过长");result.put(e.getKey(),value);}return result;}
    private WorkflowModels.DefinitionRow require(long id){var row=mapper.definition(TenantContext.require().tenantId(),id);if(row==null)throw new ApiException(CommonErrorCode.NOT_FOUND);return row;}
    private WorkflowModels.DefinitionView view(WorkflowModels.DefinitionRow row){return new WorkflowModels.DefinitionView(Long.toString(row.id()),row.definitionCode(),row.definitionName(),row.businessType(),row.draftBpmn(),row.status(),row.currentVersion(),row.version(),row.updatedAt());}
    private WorkflowModels.InstanceView instance(WorkflowModels.InstanceRow row){return new WorkflowModels.InstanceView(Long.toString(row.id()),Long.toString(row.definitionId()),row.definitionVersion(),row.processInstanceId(),row.businessType(),row.businessId(),row.status(),row.result(),row.startedAt(),row.finishedAt());}
    private WorkflowModels.TaskView task(Task task){return new WorkflowModels.TaskView(task.getId(),task.getProcessInstanceId(),task.getTaskDefinitionKey(),task.getName(),task.getAssignee(),task.getCreateTime().toInstant().atZone(java.time.ZoneId.systemDefault()).toLocalDateTime());}
}
