package io.github.turbopro.ism.qualification;

import io.github.turbopro.ism.common.api.error.*;
import io.github.turbopro.ism.common.infrastructure.authorization.*;
import io.github.turbopro.ism.common.infrastructure.tenant.TenantContext;
import io.github.turbopro.ism.operation.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.time.format.DateTimeFormatter;
import java.util.*;

@Service
public class AdmissionService {
    private final AdmissionMapper mapper;private final OperationIdGenerator ids;private final AuditService audit;private final io.github.turbopro.ism.supplier.SupplierReferenceService suppliers;private final QualificationFileReference files;private final io.github.turbopro.ism.supplier.PurchaseCategoryService categories;
    public AdmissionService(AdmissionMapper mapper,OperationIdGenerator ids,AuditService audit,io.github.turbopro.ism.supplier.SupplierReferenceService suppliers,QualificationFileReference files,io.github.turbopro.ism.supplier.PurchaseCategoryService categories){this.mapper=mapper;this.ids=ids;this.audit=audit;this.suppliers=suppliers;this.files=files;this.categories=categories;}
    public AdmissionModels.Page list(String keyword,String status,int page,int size){var i=TenantContext.require();var scope=scope();String like=keyword==null||keyword.isBlank()?null:"%"+keyword.trim().replace("=","==").replace("%","=%").replace("_","=_")+"%";String state=status==null||status.isBlank()?null:parseStatus(status).name();return new AdmissionModels.Page(mapper.count(i.tenantId(),like,state,scope.type().name(),scope.organizationIds(),i.actorId()),page,size,mapper.list(i.tenantId(),like,state,scope.type().name(),scope.organizationIds(),i.actorId(),Math.multiplyExact(page,size),size));}
    public AdmissionModels.View get(long id){return view(requireAllowed(id));}
    @Transactional public AdmissionModels.View create(AdmissionModels.SaveApplication c){if(c.version()!=0)throw validation("新建准入申请的 version 必须为 0");validateMaterials(c.materials(),false);var i=TenantContext.require();long supplier=parseId(c.supplierId(),"供应商 ID 无效");var reference=suppliers.eligibleForAdmission(supplier);Long org=reference==null?null:reference.organizationId();if(org==null)throw validation("供应商不存在或当前状态不可发起准入");requireScope(org,i.actorId());Long categoryId=categoryId(c.purchaseCategoryId());String category=categoryName(supplier,categoryId,c.purchaseCategory(),false);validatePolicyMaterials(categoryId,c.materials(),false);long id=ids.nextId();String number="ADM-"+LocalDate.now().format(DateTimeFormatter.BASIC_ISO_DATE)+"-"+Long.toString(id).substring(Math.max(0,Long.toString(id).length()-8));mapper.insert(id,i.tenantId(),i.actorId(),org,supplier,number,category,categoryId,c.reason().trim(),c.expectedAnnualAmount(),blank(c.currency()));replaceMaterials(i.tenantId(),id,c.materials());appendReview(id,"CREATE","DRAFT","DRAFT","创建准入申请");audit.append(new AuditService.AuditCommand("ADMISSION_CREATE","ADMISSION",id,null,Map.of(),Map.of("applicationNo",number,"supplierId",supplier),null,null));return view(mapper.find(i.tenantId(),id));}
    @Transactional public AdmissionModels.View update(long id,AdmissionModels.SaveApplication c){var before=requireAllowed(id);if(!Set.of("DRAFT","REVISION_REQUIRED").contains(before.status()))throw validation("当前状态不可编辑");if(before.supplierId()!=parseId(c.supplierId(),"供应商 ID 无效"))throw validation("申请关联供应商不可修改");validateMaterials(c.materials(),false);var i=TenantContext.require();Long categoryId=categoryId(c.purchaseCategoryId());if(before.purchaseCategoryId()!=null&&categoryId==null)throw validation("已绑定的采购品类不可退回自由文本");String category=categoryName(before.supplierId(),categoryId,c.purchaseCategory(),before.purchaseCategoryId()==null);validatePolicyMaterials(categoryId,c.materials(),false);if(mapper.update(i.tenantId(),i.actorId(),id,category,categoryId,c.reason().trim(),c.expectedAnnualAmount(),blank(c.currency()),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);mapper.deleteMaterials(i.tenantId(),id);replaceMaterials(i.tenantId(),id,c.materials());appendReview(id,"UPDATE",before.status(),before.status(),"补充准入申请资料");audit.append(new AuditService.AuditCommand("ADMISSION_UPDATE","ADMISSION",id,null,Map.of("version",before.version()),Map.of("version",before.version()+1,"materialCount",c.materials().size()),null,null));return view(mapper.find(i.tenantId(),id));}
    @Transactional public AdmissionModels.View submit(long id,int version){var before=requireAllowed(id);if(!Set.of("DRAFT","REVISION_REQUIRED").contains(before.status()))throw validation("只有草稿或待补正申请可以提交");if(suppliers.eligibleForAdmission(before.supplierId())==null)throw validation("供应商存在生效限制或不可准入");validateCategory(before);var materials=storedMaterials(id);validateMaterials(materials,true);validatePolicyMaterials(before.purchaseCategoryId(),materials,true);var i=TenantContext.require();if(mapper.submit(i.tenantId(),i.actorId(),id,version)!=1)throw new ApiException(CommonErrorCode.CONFLICT);appendReview(id,"SUBMIT",before.status(),"SUBMITTED","提交准入审核");audit.append(new AuditService.AuditCommand("ADMISSION_SUBMIT","ADMISSION",id,null,Map.of("status",before.status()),Map.of("status","SUBMITTED"),null,null));return view(mapper.find(i.tenantId(),id));}
    @Transactional public AdmissionModels.View review(long id,AdmissionModels.ReviewCommand c){var before=requireAllowed(id);if(!before.status().equals("SUBMITTED"))throw validation("只有已提交申请可以审核");if(c.decision()==AdmissionModels.Decision.APPROVE){if(before.createdBy()==TenantContext.require().actorId())throw validation("申请人不能批准自己的准入申请");if(suppliers.eligibleForAdmission(before.supplierId())==null)throw validation("供应商存在生效限制或不可准入");validateCategory(before);var materials=storedMaterials(id);validateMaterials(materials,true);validatePolicyMaterials(before.purchaseCategoryId(),materials,true);}String next=switch(c.decision()){case APPROVE->"APPROVED";case REQUIRE_REVISION->"REVISION_REQUIRED";case REJECT->"REJECTED";};var i=TenantContext.require();if(mapper.review(i.tenantId(),i.actorId(),id,next,c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);if(c.decision()==AdmissionModels.Decision.APPROVE)mapper.activateSupplier(i.tenantId(),i.actorId(),before.supplierId());appendReview(id,c.decision().name(),before.status(),next,c.comment().trim());audit.append(new AuditService.AuditCommand("ADMISSION_REVIEW","ADMISSION",id,null,Map.of("status",before.status()),Map.of("status",next,"comment",c.comment()),null,null));return view(mapper.find(i.tenantId(),id));}
    private Long categoryId(String value){return value==null?null:parseId(value,"采购品类 ID 无效");}
    private String categoryName(long supplierId,Long id,String legacy,boolean legacyEdit){
        if(id!=null)return categories.requireAdmissionCategory(supplierId,id);
        if(!legacyEdit&&categories.hasActiveCategories())throw validation("请选择已关联供应商的采购品类");
        return legacy.trim();
    }
    private void validateCategory(AdmissionModels.Row row){if(row.purchaseCategoryId()!=null)categories.requireAdmissionCategory(row.supplierId(),row.purchaseCategoryId());}
    private void validatePolicyMaterials(Long categoryId,List<AdmissionModels.MaterialCommand> materials,boolean submitting){
        if(categoryId==null)return;
        for(var rule:categories.requiredMaterials(categoryId)){
            var item=materials.stream().filter(m->m.type().equals(rule.type())).findFirst().orElse(null);
            if(item==null||!item.required())throw validation("缺少采购品类必交资料: "+rule.name());
            if(submitting&&!item.provided())throw validation("采购品类必交资料尚未提供: "+rule.name());
        }
    }
    private AdmissionModels.Row requireAllowed(long id){var i=TenantContext.require();var row=mapper.find(i.tenantId(),id);if(row==null||!scope().allows(new DataTarget(row.organizationId(),null,row.createdBy(),row.createdBy()),i.actorId()))throw new ApiException(CommonErrorCode.NOT_FOUND);return row;}
    private DataScope scope(){return AuthorizationContext.require().dataScope("supplier:admission");}
    private void requireScope(long org,long actor){if(!scope().allows(new DataTarget(org,null,actor,actor),actor))throw new ApiException(CommonErrorCode.FORBIDDEN);}
    private void validateMaterials(List<AdmissionModels.MaterialCommand> items,boolean submitting){Set<String> types=new HashSet<>();for(var m:items){if(!types.add(m.type()))throw validation("资料类型不可重复: "+m.type());if(m.provided()&&m.fileId()==null)throw validation("已提供资料必须关联文件: "+m.name());if(submitting&&m.required()&&!m.provided())throw validation("必填资料尚未提供: "+m.name());if(m.fileId()!=null&&!files.active(parseId(m.fileId(),"资料文件 ID 无效")))throw validation("资料文件不存在或不可用: "+m.name());}}
    private List<AdmissionModels.MaterialCommand> storedMaterials(long id){return mapper.materials(TenantContext.require().tenantId(),id).stream().map(m->new AdmissionModels.MaterialCommand(m.materialType(),m.materialName(),m.fileId()==null?null:Long.toString(m.fileId()),m.required(),m.provided(),m.remark(),m.sortOrder())).toList();}
    private void replaceMaterials(long tenant,long application,List<AdmissionModels.MaterialCommand> materials){for(var m:materials)mapper.insertMaterial(ids.nextId(),tenant,application,m.type(),m.name().trim(),m.fileId()==null?null:parseId(m.fileId(),"资料文件 ID 无效"),m.required(),m.provided(),blank(m.remark()),m.sortOrder());}
    private void appendReview(long application,String action,String from,String to,String comment){var i=TenantContext.require();mapper.insertReview(ids.nextId(),i.tenantId(),application,action,from,to,comment,i.actorId());}
    private AdmissionModels.Status parseStatus(String value){try{return AdmissionModels.Status.valueOf(value);}catch(Exception e){throw validation("准入状态无效");}}
    private long parseId(String value,String message){try{return Long.parseLong(value);}catch(Exception e){throw validation(message);}}
    private String blank(String value){return value==null||value.isBlank()?null:value.trim();}
    private ApiException validation(String message){return new ApiException(CommonErrorCode.VALIDATION_FAILED,message);}
    private AdmissionModels.View view(AdmissionModels.Row r){var i=TenantContext.require();return new AdmissionModels.View(Long.toString(r.id()),Long.toString(r.organizationId()),Long.toString(r.supplierId()),r.applicationNo(),r.supplierCode(),r.supplierName(),r.purchaseCategory(),r.admissionReason(),r.expectedAnnualAmount(),r.currency(),AdmissionModels.Status.valueOf(r.status()),r.workflowInstanceId(),r.version(),r.submittedAt(),r.decidedAt(),r.createdAt(),r.updatedAt(),mapper.materials(i.tenantId(),r.id()).stream().map(m->new AdmissionModels.MaterialView(Long.toString(m.id()),m.materialType(),m.materialName(),m.fileId()==null?null:Long.toString(m.fileId()),m.required(),m.provided(),m.remark(),m.sortOrder())).toList(),mapper.reviews(i.tenantId(),r.id()).stream().map(x->new AdmissionModels.ReviewView(Long.toString(x.id()),x.action(),AdmissionModels.Status.valueOf(x.fromStatus()),AdmissionModels.Status.valueOf(x.toStatus()),x.commentText(),Long.toString(x.operatorId()),x.operatedAt())).toList(),r.purchaseCategoryId()==null?null:Long.toString(r.purchaseCategoryId()));}
}
