package io.github.turbopro.ism.qualification;

import io.github.turbopro.ism.common.api.error.*;
import io.github.turbopro.ism.common.infrastructure.authorization.*;
import io.github.turbopro.ism.common.infrastructure.tenant.TenantContext;
import io.github.turbopro.ism.operation.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;
import java.util.*;

@Service
public class QualificationService {
    private final QualificationMapper mapper;private final OperationIdGenerator ids;private final AuditService audit;
    public QualificationService(QualificationMapper mapper,OperationIdGenerator ids,AuditService audit){this.mapper=mapper;this.ids=ids;this.audit=audit;}
    public List<QualificationModels.TypeView> types(){return mapper.types(TenantContext.require().tenantId()).stream().map(this::typeView).toList();}
    @Transactional public QualificationModels.TypeView createType(QualificationModels.SaveType c){if(c.version()!=0)throw validation("新建资质类型的 version 必须为 0");var i=TenantContext.require();long id=ids.nextId();try{mapper.insertType(id,i.tenantId(),i.actorId(),c.code(),c.name().trim(),c.category(),c.validityRequired(),c.defaultWarningDays(),blank(c.description()),c.status().name());}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"资质类型编码已存在");}return typeView(mapper.type(i.tenantId(),id));}
    @Transactional public QualificationModels.TypeView updateType(long id,QualificationModels.SaveType c){var i=TenantContext.require();var before=mapper.type(i.tenantId(),id);if(before==null)throw new ApiException(CommonErrorCode.NOT_FOUND);if(!before.typeCode().equals(c.code()))throw validation("资质类型编码不可修改");if(mapper.updateType(i.tenantId(),i.actorId(),id,c.name().trim(),c.category(),c.validityRequired(),c.defaultWarningDays(),blank(c.description()),c.status().name(),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);return typeView(mapper.type(i.tenantId(),id));}
    public QualificationModels.Page list(String keyword,String status,Long supplierId,int page,int size){var i=TenantContext.require();var scope=scope();String like=keyword==null||keyword.isBlank()?null:"%"+keyword.trim().replace("=","==").replace("%","=%").replace("_","=_")+"%";String state=status==null||status.isBlank()?null:parseStatus(status).name();return new QualificationModels.Page(mapper.count(i.tenantId(),like,state,supplierId,scope.type().name(),scope.organizationIds(),i.actorId()),page,size,mapper.list(i.tenantId(),like,state,supplierId,scope.type().name(),scope.organizationIds(),i.actorId(),Math.multiplyExact(page,size),size));}
    public QualificationModels.View get(long id){return view(requireAllowed(id));}
    @Transactional public QualificationModels.View create(QualificationModels.SaveQualification c){if(c.version()!=0)throw validation("新建资质的 version 必须为 0");return createInternal(c,null);}
    @Transactional public QualificationModels.View update(long id,QualificationModels.SaveQualification c){var before=requireAllowed(id);if(before.supplierId()!=parseId(c.supplierId(),"供应商 ID 无效")||before.qualificationTypeId()!=parseId(c.typeId(),"资质类型 ID 无效"))throw validation("供应商和资质类型不可修改");validate(c,mapper.type(TenantContext.require().tenantId(),before.qualificationTypeId()));var i=TenantContext.require();try{if(mapper.update(i.tenantId(),i.actorId(),id,c.certificateNo().trim(),blank(c.issuingAuthority()),c.issueDate(),c.effectiveDate(),c.permanent()?null:c.expiryDate(),c.permanent(),warning(c,before.qualificationTypeId()),parseId(c.fileId(),"文件 ID 无效"),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"证书编号已存在");}return view(mapper.find(i.tenantId(),id));}
    @Transactional public QualificationModels.View verify(long id,QualificationModels.VerifyCommand c){var before=requireAllowed(id);String next=c.decision()==QualificationModels.Decision.APPROVE?"VALID":"REJECTED";var i=TenantContext.require();if(mapper.verify(i.tenantId(),i.actorId(),id,next,c.comment().trim(),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);audit("QUALIFICATION_VERIFY",id,before.status(),next,c.comment());return view(mapper.find(i.tenantId(),id));}
    @Transactional public QualificationModels.View revoke(long id,QualificationModels.RevokeCommand c){var before=requireAllowed(id);var i=TenantContext.require();if(mapper.revoke(i.tenantId(),i.actorId(),id,c.reason().trim(),c.version())!=1)throw validation("只有已生效资质可以撤销，或数据版本已变化");audit("QUALIFICATION_REVOKE",id,before.status(),"REVOKED",c.reason());return view(mapper.find(i.tenantId(),id));}
    @Transactional public QualificationModels.View renew(long id,QualificationModels.SaveQualification c){var before=requireAllowed(id);if(!Set.of("VALID").contains(before.status()))throw validation("只有已生效资质可以换证");if(before.supplierId()!=parseId(c.supplierId(),"供应商 ID 无效")||before.qualificationTypeId()!=parseId(c.typeId(),"资质类型 ID 无效"))throw validation("换证不得变更供应商和资质类型");var replacement=createInternal(c,id);var i=TenantContext.require();if(mapper.supersede(i.tenantId(),i.actorId(),id,c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);audit("QUALIFICATION_RENEW",id,before.status(),"SUPERSEDED","换证草稿 "+replacement.id());return replacement;}
    private QualificationModels.View createInternal(QualificationModels.SaveQualification c,Long parent){var i=TenantContext.require();long supplier=parseId(c.supplierId(),"供应商 ID 无效"),typeId=parseId(c.typeId(),"资质类型 ID 无效");Long org=mapper.supplierOrganization(i.tenantId(),supplier);if(org==null)throw validation("供应商不存在或已退出");requireScope(org,i.actorId());var type=mapper.type(i.tenantId(),typeId);validate(c,type);long id=ids.nextId();try{mapper.insert(id,i.tenantId(),i.actorId(),org,supplier,typeId,parent,c.certificateNo().trim(),blank(c.issuingAuthority()),c.issueDate(),c.effectiveDate(),c.permanent()?null:c.expiryDate(),c.permanent(),c.warningDays()==null?type.defaultWarningDays():c.warningDays(),parseId(c.fileId(),"文件 ID 无效"));}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"证书编号已存在");}audit("QUALIFICATION_CREATE",id,null,"DRAFT","创建资质草稿");return view(mapper.find(i.tenantId(),id));}
    private void validate(QualificationModels.SaveQualification c,QualificationModels.TypeRow type){if(type==null||!type.status().equals("ACTIVE"))throw validation("资质类型不存在或已停用");if(c.permanent()&&c.expiryDate()!=null)throw validation("长期有效资质不能填写到期日");if(!c.permanent()&&type.validityRequired()&&c.expiryDate()==null)throw validation("该资质必须填写到期日");if(c.effectiveDate()!=null&&c.expiryDate()!=null&&c.effectiveDate().isAfter(c.expiryDate()))throw validation("生效日期不能晚于到期日期");if(c.issueDate()!=null&&c.issueDate().isAfter(LocalDate.now()))throw validation("签发日期不能晚于今天");}
    private QualificationModels.Row requireAllowed(long id){var i=TenantContext.require();var row=mapper.find(i.tenantId(),id);if(row==null||!scope().allows(new DataTarget(row.organizationId(),null,row.createdBy(),row.createdBy()),i.actorId()))throw new ApiException(CommonErrorCode.NOT_FOUND);return row;}
    private DataScope scope(){return AuthorizationContext.require().dataScope("supplier:qualification");}
    private void requireScope(long org,long actor){if(!scope().allows(new DataTarget(org,null,actor,actor),actor))throw new ApiException(CommonErrorCode.FORBIDDEN);}
    private int warning(QualificationModels.SaveQualification c,long typeId){var type=mapper.type(TenantContext.require().tenantId(),typeId);return c.warningDays()==null?type.defaultWarningDays():c.warningDays();}
    private QualificationModels.Status parseStatus(String value){try{return QualificationModels.Status.valueOf(value);}catch(Exception e){throw validation("资质状态无效");}}
    private long parseId(String value,String message){try{return Long.parseLong(value);}catch(Exception e){throw validation(message);}}
    private String blank(String value){return value==null||value.isBlank()?null:value.trim();}
    private ApiException validation(String message){return new ApiException(CommonErrorCode.VALIDATION_FAILED,message);}
    private void audit(String action,long id,String from,String to,String comment){audit.append(new AuditService.AuditCommand(action,"QUALIFICATION",id,null,from==null?Map.of():Map.of("status",from),Map.of("status",to,"comment",comment),null,null));}
    private QualificationModels.TypeView typeView(QualificationModels.TypeRow r){return new QualificationModels.TypeView(Long.toString(r.id()),r.typeCode(),r.typeName(),r.category(),r.validityRequired(),r.defaultWarningDays(),r.description(),QualificationModels.TypeStatus.valueOf(r.status()),r.version(),r.updatedAt());}
    private QualificationModels.View view(QualificationModels.Row r){return new QualificationModels.View(Long.toString(r.id()),Long.toString(r.organizationId()),Long.toString(r.supplierId()),r.supplierCode(),r.supplierName(),Long.toString(r.qualificationTypeId()),r.typeCode(),r.typeName(),r.parentQualificationId()==null?null:Long.toString(r.parentQualificationId()),r.certificateNo(),r.issuingAuthority(),r.issueDate(),r.effectiveDate(),r.expiryDate(),r.permanent(),r.warningDays(),Long.toString(r.fileId()),effective(r),r.verificationComment(),r.verifiedBy()==null?null:Long.toString(r.verifiedBy()),r.verifiedAt(),r.revokedReason(),r.version(),r.createdAt(),r.updatedAt());}
    private QualificationModels.Status effective(QualificationModels.Row r){if(!r.status().equals("VALID")||r.permanent()||r.expiryDate()==null)return QualificationModels.Status.valueOf(r.status());long days=java.time.temporal.ChronoUnit.DAYS.between(LocalDate.now(),r.expiryDate());return days<0?QualificationModels.Status.EXPIRED:days<=r.warningDays()?QualificationModels.Status.EXPIRING:QualificationModels.Status.VALID;}
}
