package io.github.turbopro.ism.qualification;

import io.github.turbopro.ism.common.infrastructure.tenant.TenantScopedMapper;
import org.apache.ibatis.annotations.*;
import java.time.LocalDate;
import java.util.*;

@Mapper
public interface QualificationMapper extends TenantScopedMapper {
    String EFFECTIVE_STATUS="CASE WHEN q.status='VALID' AND q.permanent_flag=0 AND CURRENT_DATE&gt;q.expiry_date THEN 'EXPIRED' WHEN q.status='VALID' AND q.permanent_flag=0 AND DATE_ADD(CURRENT_DATE,INTERVAL q.warning_days DAY)&gt;=q.expiry_date THEN 'EXPIRING' ELSE q.status END";
    String SCOPE="<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND q.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'CREATED'\"> AND q.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>";
    String FILTER="<if test='keyword != null and keyword != &quot;&quot;'> AND (s.supplier_code LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=' OR q.certificate_no LIKE #{keyword} ESCAPE '=')</if><if test='status != null and status != &quot;&quot;'> AND "+EFFECTIVE_STATUS+"=#{status}</if><if test='supplierId != null'> AND q.supplier_id=#{supplierId}</if>";
    @Select("SELECT id,type_code,type_name,category,validity_required,default_warning_days,description,status,version,updated_at FROM qua_qualification_type WHERE tenant_id=#{tenantId} ORDER BY status,type_name") List<QualificationModels.TypeRow> types(long tenantId);
    @Select("SELECT id,type_code,type_name,category,validity_required,default_warning_days,description,status,version,updated_at FROM qua_qualification_type WHERE tenant_id=#{tenantId} AND id=#{id}") QualificationModels.TypeRow type(long tenantId,long id);
    @Insert("INSERT INTO qua_qualification_type(id,tenant_id,type_code,type_name,category,validity_required,default_warning_days,description,status,created_by,updated_by) VALUES(#{id},#{tenantId},#{code},#{name},#{category},#{validity},#{warningDays},#{description},#{status},#{actorId},#{actorId})") int insertType(long id,long tenantId,long actorId,String code,String name,String category,boolean validity,int warningDays,String description,String status);
    @Update("UPDATE qua_qualification_type SET type_name=#{name},category=#{category},validity_required=#{validity},default_warning_days=#{warningDays},description=#{description},status=#{status},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND version=#{version}") int updateType(long tenantId,long actorId,long id,String name,String category,boolean validity,int warningDays,String description,String status,int version);
    @Select("<script>SELECT COUNT(*) FROM qua_supplier_qualification q JOIN sup_supplier s ON s.id=q.supplier_id AND s.tenant_id=q.tenant_id WHERE q.tenant_id=#{tenantId}"+SCOPE+FILTER+"</script>") long count(long tenantId,String keyword,String status,Long supplierId,String scopeType,Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT q.id,q.organization_id,q.supplier_id,s.supplier_code,s.supplier_name,q.qualification_type_id type_id,t.type_code,t.type_name,q.certificate_no,q.expiry_date,q.permanent_flag permanent,"+EFFECTIVE_STATUS+" status,CASE WHEN q.permanent_flag=1 OR q.expiry_date IS NULL THEN 2147483647 ELSE DATEDIFF(q.expiry_date,CURRENT_DATE) END days_until_expiry,q.version,q.updated_at FROM qua_supplier_qualification q JOIN sup_supplier s ON s.id=q.supplier_id AND s.tenant_id=q.tenant_id JOIN qua_qualification_type t ON t.id=q.qualification_type_id WHERE q.tenant_id=#{tenantId}"+SCOPE+FILTER+" ORDER BY CASE WHEN q.expiry_date IS NULL THEN 1 ELSE 0 END,q.expiry_date,q.updated_at DESC LIMIT #{size} OFFSET #{offset}</script>") List<QualificationModels.Summary> list(long tenantId,String keyword,String status,Long supplierId,String scopeType,Set<Long> organizationIds,long actorId,int offset,int size);
    @Select("SELECT q.id,q.organization_id,q.supplier_id,q.qualification_type_id,q.parent_qualification_id,s.supplier_code,s.supplier_name,t.type_code,t.type_name,q.certificate_no,q.issuing_authority,q.issue_date,q.effective_date,q.expiry_date,q.permanent_flag permanent,q.warning_days,q.file_id,q.status,q.verification_comment,q.verified_by,q.verified_at,q.revoked_reason,q.created_by,q.version,q.created_at,q.updated_at FROM qua_supplier_qualification q JOIN sup_supplier s ON s.id=q.supplier_id AND s.tenant_id=q.tenant_id JOIN qua_qualification_type t ON t.id=q.qualification_type_id WHERE q.tenant_id=#{tenantId} AND q.id=#{id}") QualificationModels.Row find(long tenantId,long id);
    @Select("SELECT organization_id FROM sup_supplier WHERE tenant_id=#{tenantId} AND id=#{supplierId} AND deleted=0 AND status!='EXITED'") Long supplierOrganization(long tenantId,long supplierId);
    @Insert("INSERT INTO qua_supplier_qualification(id,tenant_id,organization_id,supplier_id,qualification_type_id,parent_qualification_id,certificate_no,issuing_authority,issue_date,effective_date,expiry_date,permanent_flag,warning_days,file_id,created_by,updated_by) VALUES(#{id},#{tenantId},#{organizationId},#{supplierId},#{typeId},#{parentId},#{certificateNo},#{authority},#{issueDate},#{effectiveDate},#{expiryDate},#{permanent},#{warningDays},#{fileId},#{actorId},#{actorId})") int insert(long id,long tenantId,long actorId,long organizationId,long supplierId,long typeId,Long parentId,String certificateNo,String authority,LocalDate issueDate,LocalDate effectiveDate,LocalDate expiryDate,boolean permanent,int warningDays,long fileId);
    @Update("UPDATE qua_supplier_qualification SET certificate_no=#{certificateNo},issuing_authority=#{authority},issue_date=#{issueDate},effective_date=#{effectiveDate},expiry_date=#{expiryDate},permanent_flag=#{permanent},warning_days=#{warningDays},file_id=#{fileId},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status IN ('DRAFT','REJECTED') AND version=#{version}") int update(long tenantId,long actorId,long id,String certificateNo,String authority,LocalDate issueDate,LocalDate effectiveDate,LocalDate expiryDate,boolean permanent,int warningDays,long fileId,int version);
    @Update("UPDATE qua_supplier_qualification SET status=#{status},verification_comment=#{comment},verified_by=#{actorId},verified_at=CURRENT_TIMESTAMP(3),updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status='DRAFT' AND version=#{version}") int verify(long tenantId,long actorId,long id,String status,String comment,int version);
    @Update("UPDATE qua_supplier_qualification SET status='REVOKED',revoked_reason=#{reason},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status='VALID' AND version=#{version}") int revoke(long tenantId,long actorId,long id,String reason,int version);
    @Update("UPDATE qua_supplier_qualification SET status='SUPERSEDED',updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND status='VALID' AND version=#{version}") int supersede(long tenantId,long actorId,long id,int version);
}
