package io.github.turbopro.ism.operation.message;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import io.github.turbopro.ism.common.api.error.*;import io.github.turbopro.ism.common.infrastructure.tenant.TenantContext;import io.github.turbopro.ism.operation.OperationIdGenerator;import org.springframework.dao.DuplicateKeyException;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;import java.util.regex.*;
@Service public class MessageService{
 private static final Pattern VARIABLE=Pattern.compile("\\{\\{([a-zA-Z][a-zA-Z0-9_.-]{0,63})}} ".trim());private final MessageMapper mapper;private final OperationIdGenerator ids;private final ObjectMapper json;
 public MessageService(MessageMapper mapper,OperationIdGenerator ids,ObjectMapper json){this.mapper=mapper;this.ids=ids;this.json=json;}
 public List<MessageModels.TemplateView> templates(){return mapper.templates(tenant()).stream().map(this::view).toList();}
 @Transactional public MessageModels.TemplateView create(MessageModels.SaveTemplate c){validateTemplate(c);long id=ids.nextId();try{mapper.insertTemplate(tenant(),id,c.code(),c.name(),c.channel(),c.titleTemplate(),c.contentTemplate(),write(c.requiredVariables()));}catch(DuplicateKeyException e){throw new ApiException(MessageErrorCode.DUPLICATE);}return view(mapper.template(tenant(),id));}
 @Transactional public MessageModels.TemplateView update(long id,MessageModels.SaveTemplate c){validateTemplate(c);if(mapper.updateTemplate(tenant(),id,c.name(),c.titleTemplate(),c.contentTemplate(),write(c.requiredVariables()),c.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);return view(mapper.template(tenant(),id));}
 @Transactional public MessageModels.SendResult send(MessageModels.SendMessage c){long tenant=tenant();var t=mapper.activeTemplate(tenant,c.templateCode());if(t==null)throw new ApiException(CommonErrorCode.NOT_FOUND);if(!t.channel().equals("IN_APP"))throw new ApiException(MessageErrorCode.CHANNEL_UNAVAILABLE);Set<String> required=read(t.variableSchema());if(!c.variables().keySet().containsAll(required))throw new ApiException(MessageErrorCode.INVALID_VARIABLES);Set<Long> recipients=parse(c.recipientIds());if(mapper.validUsers(tenant,recipients).size()!=recipients.size())throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"收件人不存在或已停用");String title=render(t.titleTemplate(),c.variables()),content=render(t.contentTemplate(),c.variables());Long businessId=c.businessId()==null?null:parseId(c.businessId());List<String> deliveries=new ArrayList<>();for(long user:recipients){long delivery=ids.nextId();mapper.insertDelivery(tenant,delivery,t.id(),user,title,content,c.businessType(),businessId,LocalDateTime.now(ZoneOffset.UTC));mapper.insertInbox(tenant,ids.nextId(),delivery,user);deliveries.add(Long.toString(delivery));}return new MessageModels.SendResult(recipients.size(),deliveries.size(),deliveries);}
 public List<MessageModels.InboxView> inbox(){var i=TenantContext.require();return mapper.inbox(i.tenantId(),i.actorId()).stream().map(r->new MessageModels.InboxView(Long.toString(r.id()),r.title(),r.content(),r.businessType(),r.businessId()==null?null:Long.toString(r.businessId()),r.readAt(),r.createdAt())).toList();}
 public int unread(){var i=TenantContext.require();return mapper.unread(i.tenantId(),i.actorId());}
 @Transactional public void read(long id){var i=TenantContext.require();if(mapper.markRead(i.tenantId(),i.actorId(),id)!=1)throw new ApiException(CommonErrorCode.NOT_FOUND);}
 @Transactional public int readAll(){var i=TenantContext.require();return mapper.markAllRead(i.tenantId(),i.actorId());}
 private void validateTemplate(MessageModels.SaveTemplate c){Set<String> used=new HashSet<>();Matcher m=VARIABLE.matcher(c.titleTemplate()+" "+c.contentTemplate());while(m.find())used.add(m.group(1));if(!c.requiredVariables().containsAll(used)||!used.containsAll(c.requiredVariables()))throw new ApiException(MessageErrorCode.INVALID_VARIABLES);}
 private String render(String template,Map<String,String> values){Matcher m=VARIABLE.matcher(template);StringBuffer b=new StringBuffer();while(m.find()){String v=values.get(m.group(1));if(v==null)throw new ApiException(MessageErrorCode.INVALID_VARIABLES);m.appendReplacement(b,Matcher.quoteReplacement(v));}m.appendTail(b);return b.toString();}
 private MessageModels.TemplateView view(MessageModels.TemplateRow r){return new MessageModels.TemplateView(Long.toString(r.id()),r.templateCode(),r.templateName(),r.channel(),r.titleTemplate(),r.contentTemplate(),read(r.variableSchema()),r.status(),r.version());}
 private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException(e);}}private Set<String> read(String v){try{return json.readValue(v,new TypeReference<Set<String>>(){});}catch(Exception e){throw new IllegalStateException(e);}}
 private Set<Long> parse(Set<String> values){Set<Long> result=new HashSet<>();for(String v:values)result.add(parseId(v));return result;}private long parseId(String v){try{long id=Long.parseLong(v);if(id<=0)throw new NumberFormatException();return id;}catch(Exception e){throw new ApiException(CommonErrorCode.VALIDATION_FAILED,"ID 必须是正整数");}}private long tenant(){return TenantContext.require().tenantId();}
}
