package io.github.turbopro.ism.operation.message;
import io.github.turbopro.ism.common.infrastructure.tenant.TenantScopedMapper;import org.apache.ibatis.annotations.*;import java.time.LocalDateTime;import java.util.*;
@Mapper public interface MessageMapper extends TenantScopedMapper{
 @Insert("INSERT INTO msg_template(id,tenant_id,template_code,template_name,channel,title_template,content_template,variable_schema,status) VALUES(#{id},#{tenantId},'SUPPLIER_EXIT_ASSIGNMENT','退出事项责任分派','IN_APP','退出事项待处置','供应商 {{supplierId}} 的退出申请 {{applicationId}} 已分派事项 {{code}} / {{sourceId}} 给您。请在业务台账处置并通知管理人员重新核验；本消息不是完成凭证。',JSON_ARRAY('supplierId','applicationId','code','sourceId'),'ACTIVE') ON DUPLICATE KEY UPDATE id=id")
 int ensureExitAssignmentTemplate(long tenantId,long id);
 @Select("SELECT id,template_code,template_name,channel,title_template,content_template,variable_schema,status,version FROM msg_template WHERE tenant_id=#{tenantId} AND template_code='SUPPLIER_EXIT_ASSIGNMENT' AND channel='IN_APP' FOR SHARE")
 MessageModels.TemplateRow exitAssignmentTemplate(long tenantId);
 @Insert("INSERT INTO msg_template(id,tenant_id,template_code,template_name,channel,title_template,content_template,variable_schema,status) VALUES(#{id},#{tenantId},'SUPPLIER_EXIT_REMINDER','退出事项催办','IN_APP','退出事项催办','供应商 {{supplierId}} 的退出申请 {{applicationId}}，事项 {{code}} / {{sourceId}} 尚待处置；期限：{{dueDate}}。请处置后联系管理人员重新核验，本消息不是完成凭证。',JSON_ARRAY('supplierId','applicationId','code','sourceId','dueDate'),'ACTIVE') ON DUPLICATE KEY UPDATE id=id")
 int ensureExitReminderTemplate(long tenantId,long id);
 @Select("SELECT id,template_code,template_name,channel,title_template,content_template,variable_schema,status,version FROM msg_template WHERE tenant_id=#{tenantId} AND template_code='SUPPLIER_EXIT_REMINDER' AND channel='IN_APP' FOR SHARE")
 MessageModels.TemplateRow exitReminderTemplate(long tenantId);
 @Insert("INSERT INTO msg_template(id,tenant_id,template_code,template_name,channel,title_template,content_template,variable_schema,status) VALUES(#{id},#{tenantId},'SUPPLIER_EXIT_ESCALATION','退出事项逾期升级','IN_APP','退出事项逾期升级','供应商 {{supplierId}} 的退出申请 {{applicationId}}，事项 {{code}} / {{sourceId}} 已逾期，期限 {{dueDate}}，当前责任人 {{assigneeId}}。请督促处置并重新核验；本通知不代表事项已完成或责任已转移。',JSON_ARRAY('supplierId','applicationId','code','sourceId','dueDate','assigneeId'),'ACTIVE') ON DUPLICATE KEY UPDATE id=id")
 int ensureExitEscalationTemplate(long tenantId,long id);
 @Select("SELECT id,template_code,template_name,channel,title_template,content_template,variable_schema,status,version FROM msg_template WHERE tenant_id=#{tenantId} AND template_code='SUPPLIER_EXIT_ESCALATION' AND channel='IN_APP' FOR SHARE")
 MessageModels.TemplateRow exitEscalationTemplate(long tenantId);
 @Select("SELECT id,template_code,template_name,channel,title_template,content_template,variable_schema,status,version FROM msg_template WHERE tenant_id=#{tenantId} ORDER BY template_code,channel")List<MessageModels.TemplateRow> templates(long tenantId);
 @Select("SELECT id,template_code,template_name,channel,title_template,content_template,variable_schema,status,version FROM msg_template WHERE tenant_id=#{tenantId} AND template_code=#{code} AND status='ACTIVE' ORDER BY channel LIMIT 1")MessageModels.TemplateRow activeTemplate(long tenantId,String code);
 @Select("SELECT id,template_code,template_name,channel,title_template,content_template,variable_schema,status,version FROM msg_template WHERE tenant_id=#{tenantId} AND id=#{id}")MessageModels.TemplateRow template(long tenantId,long id);
 @Insert("INSERT INTO msg_template(id,tenant_id,template_code,template_name,channel,title_template,content_template,variable_schema,status) VALUES(#{id},#{tenantId},#{code},#{name},#{channel},#{title},#{content},CAST(#{schema} AS JSON),'ACTIVE')")int insertTemplate(long tenantId,long id,String code,String name,String channel,String title,String content,String schema);
 @Update("UPDATE msg_template SET template_name=#{name},title_template=#{title},content_template=#{content},variable_schema=CAST(#{schema} AS JSON),version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND version=#{version}")int updateTemplate(long tenantId,long id,String name,String title,String content,String schema,int version);
 @Select("<script>SELECT id FROM iam_user WHERE tenant_id=#{tenantId} AND status='ACTIVE' AND deleted=0 AND id IN <foreach collection='ids' item='id' open='(' separator=',' close=')'>#{id}</foreach></script>")Set<Long> validUsers(long tenantId,Set<Long> ids);
 @Insert("INSERT INTO msg_delivery(id,tenant_id,template_id,channel,recipient_id,title,content,business_type,business_id,status,sent_at) VALUES(#{id},#{tenantId},#{templateId},'IN_APP',#{recipientId},#{title},#{content},#{businessType},#{businessId},'DELIVERED',#{now})")int insertDelivery(long tenantId,long id,long templateId,long recipientId,String title,String content,String businessType,Long businessId,LocalDateTime now);
 @Insert("INSERT INTO msg_inbox(id,tenant_id,delivery_id,recipient_id) VALUES(#{id},#{tenantId},#{deliveryId},#{recipientId})")int insertInbox(long tenantId,long id,long deliveryId,long recipientId);
 @Select("SELECT i.id,i.delivery_id,d.title,d.content,d.business_type,d.business_id,i.read_at,i.created_at FROM msg_inbox i JOIN msg_delivery d ON d.id=i.delivery_id AND d.tenant_id=i.tenant_id WHERE i.tenant_id=#{tenantId} AND i.recipient_id=#{userId} ORDER BY i.created_at DESC,i.id DESC LIMIT 200")List<MessageModels.InboxRow> inbox(long tenantId,long userId);
 @Select("SELECT COUNT(*) FROM msg_inbox WHERE tenant_id=#{tenantId} AND recipient_id=#{userId} AND read_at IS NULL")int unread(long tenantId,long userId);
 @Update("UPDATE msg_inbox SET read_at=COALESCE(read_at,CURRENT_TIMESTAMP(3)) WHERE tenant_id=#{tenantId} AND recipient_id=#{userId} AND id=#{id}")int markRead(long tenantId,long userId,long id);
 @Update("UPDATE msg_inbox SET read_at=CURRENT_TIMESTAMP(3) WHERE tenant_id=#{tenantId} AND recipient_id=#{userId} AND read_at IS NULL")int markAllRead(long tenantId,long userId);
}
