package io.github.turbopro.ism.integration.search;

import io.github.turbopro.ism.common.infrastructure.tenant.TenantScopedMapper;
import org.apache.ibatis.annotations.*;
import java.time.LocalDateTime;
import java.util.List;

@Mapper
public interface SearchMapper extends TenantScopedMapper {
    String FILTER="""
      <if test='statuses != null and !statuses.isEmpty()'> AND status IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if>
      <if test='from != null'> AND updated_at &gt;= #{from}</if><if test='to != null'> AND updated_at &lt;= #{to}</if>
      """;
    @Select("<script>SELECT u.id,'USER' entity_type,u.display_name title,u.username subtitle,u.status,CONCAT('/system/users/',u.id) route,u.updated_at,uo.organization_id,NULL owner_id FROM iam_user u LEFT JOIN iam_user_organization uo ON uo.tenant_id=u.tenant_id AND uo.user_id=u.id AND uo.is_primary=1 WHERE u.tenant_id=#{tenantId} AND u.deleted=0 AND (u.display_name LIKE #{keyword} ESCAPE '=' OR u.username LIKE #{keyword} ESCAPE '=')<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND EXISTS(SELECT 1 FROM iam_user_organization permitted_uo WHERE permitted_uo.tenant_id=u.tenant_id AND permitted_uo.user_id=u.id AND permitted_uo.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach>)</when><otherwise> AND 1=0</otherwise></choose><if test='statuses != null and !statuses.isEmpty()'> AND u.status IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if><if test='from != null'> AND u.updated_at &gt;= #{from}</if><if test='to != null'> AND u.updated_at &lt;= #{to}</if> ORDER BY u.updated_at DESC,u.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> users(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT id,'ORGANIZATION' entity_type,organization_name title,CONCAT(organization_code,' · ',organization_type) subtitle,status,CONCAT('/system/organizations/',id) route,updated_at,id organization_id,NULL owner_id FROM iam_organization WHERE tenant_id=#{tenantId} AND (organization_name LIKE #{keyword} ESCAPE '=' OR organization_code LIKE #{keyword} ESCAPE '=')<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><otherwise> AND 1=0</otherwise></choose>"+FILTER+" ORDER BY updated_at DESC,id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> organizations(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT id,'FILE' entity_type,original_name title,content_type subtitle,status,CONCAT('/resources/files/',id) route,created_at updated_at,NULL organization_id,owner_id FROM res_file_object WHERE tenant_id=#{tenantId} AND original_name LIKE #{keyword} ESCAPE '='<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'OWNED' or scopeType == 'CREATED'\"> AND owner_id=#{actorId}</when><otherwise> AND 1=0</otherwise></choose><if test='statuses != null and !statuses.isEmpty()'> AND status IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if><if test='from != null'> AND created_at &gt;= #{from}</if><if test='to != null'> AND created_at &lt;= #{to}</if> ORDER BY created_at DESC,id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> files(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT id,'PRINT_TEMPLATE' entity_type,template_name title,CONCAT(template_code,' · ',business_type) subtitle,status,CONCAT('/resources/print-templates/',id) route,updated_at,NULL organization_id,NULL owner_id FROM prt_template WHERE tenant_id=#{tenantId} AND (template_name LIKE #{keyword} ESCAPE '=' OR template_code LIKE #{keyword} ESCAPE '=' OR business_type LIKE #{keyword} ESCAPE '=')"+FILTER+" ORDER BY updated_at DESC,id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> printTemplates(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit);
    @Select("<script>SELECT i.id,'MESSAGE' entity_type,d.title title,d.business_type subtitle,CASE WHEN i.read_at IS NULL THEN 'UNREAD' ELSE 'READ' END status,CONCAT('/messages/inbox/',i.id) route,i.created_at updated_at,NULL organization_id,i.recipient_id owner_id FROM msg_inbox i JOIN msg_delivery d ON d.id=i.delivery_id AND d.tenant_id=i.tenant_id WHERE i.tenant_id=#{tenantId} AND i.recipient_id=#{userId} AND (d.title LIKE #{keyword} ESCAPE '=' OR d.content LIKE #{keyword} ESCAPE '=')<if test='statuses != null and !statuses.isEmpty()'> AND (CASE WHEN i.read_at IS NULL THEN 'UNREAD' ELSE 'READ' END) IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if><if test='from != null'> AND i.created_at &gt;= #{from}</if><if test='to != null'> AND i.created_at &lt;= #{to}</if> ORDER BY i.created_at DESC,i.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> messages(long tenantId,long userId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit);
    @Select("<script>SELECT id,'TASK' entity_type,task_no title,CONCAT(task_type,COALESCE(CONCAT(' · ',current_stage),'')) subtitle,status,CONCAT('/resources/tasks/',id) route,created_at updated_at,NULL organization_id,requester_id owner_id FROM ops_async_task WHERE tenant_id=#{tenantId} AND requester_id=#{userId} AND (task_no LIKE #{keyword} ESCAPE '=' OR task_type LIKE #{keyword} ESCAPE '=' OR current_stage LIKE #{keyword} ESCAPE '=')<if test='statuses != null and !statuses.isEmpty()'> AND status IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if><if test='from != null'> AND created_at &gt;= #{from}</if><if test='to != null'> AND created_at &lt;= #{to}</if> ORDER BY created_at DESC,id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> tasks(long tenantId,long userId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit);
    @Select("<script>SELECT s.id,'SUPPLIER' entity_type,s.supplier_name title,s.supplier_code subtitle,s.status,'/suppliers/master' route,s.updated_at,s.organization_id,s.created_by owner_id FROM sup_supplier s WHERE s.tenant_id=#{tenantId} AND s.deleted=0 AND (s.supplier_name LIKE #{keyword} ESCAPE '=' OR s.supplier_code LIKE #{keyword} ESCAPE '=' OR s.unified_social_credit_code LIKE #{keyword} ESCAPE '=')<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND s.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'CREATED'\"> AND s.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose><if test='statuses != null and !statuses.isEmpty()'> AND s.status IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if><if test='from != null'> AND s.updated_at &gt;= #{from}</if><if test='to != null'> AND s.updated_at &lt;= #{to}</if> ORDER BY s.updated_at DESC,s.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> suppliers(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("""
        <script>SELECT a.id,'SUPPLIER_ADMISSION' entity_type,a.application_no title,
        CONCAT(s.supplier_name,' · ',a.purchase_category) subtitle,a.status,
        '/suppliers/admissions' route,a.updated_at,a.organization_id,a.created_by owner_id
        FROM qua_admission_application a
        JOIN sup_supplier s ON s.id=a.supplier_id AND s.tenant_id=a.tenant_id
        WHERE a.tenant_id=#{tenantId} AND (a.application_no LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=' OR s.supplier_code LIKE #{keyword} ESCAPE '=')
        <choose><when test="scopeType == 'TENANT_ALL'"></when>
        <when test="scopeType == 'ORGANIZATION_SET'"> AND a.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when>
        <when test="scopeType == 'CREATED'"> AND a.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>
        <if test='statuses != null and !statuses.isEmpty()'> AND a.status IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if>
        <if test='from != null'> AND a.updated_at &gt;= #{from}</if><if test='to != null'> AND a.updated_at &lt;= #{to}</if>
        ORDER BY a.updated_at DESC,a.id DESC LIMIT #{limit}</script>
        """)
    List<SearchModels.SearchRow> supplierAdmissions(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("""
        <script>SELECT q.id,'SUPPLIER_QUALIFICATION' entity_type,q.certificate_no title,
        CONCAT(s.supplier_name,' · ',t.type_name) subtitle,
        CASE WHEN q.status='VALID' AND q.permanent_flag=0 AND CURRENT_DATE&gt;q.expiry_date THEN 'EXPIRED'
             WHEN q.status='VALID' AND q.permanent_flag=0 AND DATE_ADD(CURRENT_DATE,INTERVAL q.warning_days DAY)&gt;=q.expiry_date THEN 'EXPIRING'
             ELSE q.status END status,
        '/suppliers/qualifications' route,q.updated_at,q.organization_id,q.created_by owner_id
        FROM qua_supplier_qualification q
        JOIN sup_supplier s ON s.id=q.supplier_id AND s.tenant_id=q.tenant_id
        JOIN qua_qualification_type t ON t.id=q.qualification_type_id AND t.tenant_id=q.tenant_id
        WHERE q.tenant_id=#{tenantId} AND (q.certificate_no LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=' OR s.supplier_code LIKE #{keyword} ESCAPE '=' OR t.type_name LIKE #{keyword} ESCAPE '=')
        <choose><when test="scopeType == 'TENANT_ALL'"></when>
        <when test="scopeType == 'ORGANIZATION_SET'"> AND q.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when>
        <when test="scopeType == 'CREATED'"> AND q.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>
        <if test='statuses != null and !statuses.isEmpty()'> AND (CASE WHEN q.status='VALID' AND q.permanent_flag=0 AND CURRENT_DATE&gt;q.expiry_date THEN 'EXPIRED' WHEN q.status='VALID' AND q.permanent_flag=0 AND DATE_ADD(CURRENT_DATE,INTERVAL q.warning_days DAY)&gt;=q.expiry_date THEN 'EXPIRING' ELSE q.status END) IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if>
        <if test='from != null'> AND q.updated_at &gt;= #{from}</if><if test='to != null'> AND q.updated_at &lt;= #{to}</if>
        ORDER BY q.updated_at DESC,q.id DESC LIMIT #{limit}</script>
        """)
    List<SearchModels.SearchRow> supplierQualifications(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT c.id,'CONTRACT' entity_type,c.contract_name title,CONCAT(c.contract_no,' · ',s.supplier_name) subtitle,c.status,'/projects/contracts' route,c.updated_at,c.organization_id,c.owner_id FROM prj_contract c JOIN sup_supplier s ON s.id=c.supplier_id AND s.tenant_id=c.tenant_id WHERE c.tenant_id=#{tenantId} AND (c.contract_name LIKE #{keyword} ESCAPE '=' OR c.contract_no LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND c.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'OWNED'\"> AND c.owner_id=#{actorId}</when><when test=\"scopeType == 'CREATED'\"> AND c.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose><if test='statuses != null and !statuses.isEmpty()'> AND c.status IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if><if test='from != null'> AND c.updated_at &gt;= #{from}</if><if test='to != null'> AND c.updated_at &lt;= #{to}</if> ORDER BY c.updated_at DESC,c.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> contracts(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT p.id,'PROJECT' entity_type,p.project_name title,CONCAT(p.project_code,' · ',s.supplier_name) subtitle,p.status,'/projects/ledger' route,p.updated_at,p.organization_id,p.manager_id owner_id FROM prj_project p JOIN sup_supplier s ON s.id=p.supplier_id AND s.tenant_id=p.tenant_id WHERE p.tenant_id=#{tenantId} AND (p.project_name LIKE #{keyword} ESCAPE '=' OR p.project_code LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND p.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'PROJECT_SET'\"> AND p.id IN <foreach collection='projectIds' item='x' open='(' separator=',' close=')'>#{x}</foreach></when><when test=\"scopeType == 'OWNED'\"> AND p.manager_id=#{actorId}</when><when test=\"scopeType == 'CREATED'\"> AND p.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose><if test='statuses != null and !statuses.isEmpty()'> AND p.status IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if><if test='from != null'> AND p.updated_at &gt;= #{from}</if><if test='to != null'> AND p.updated_at &lt;= #{to}</if> ORDER BY p.updated_at DESC,p.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> projects(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,java.util.Set<Long> projectIds,long actorId);
    @Select("""
        <script>SELECT x.id,'PERSON' entity_type,x.person_name title,CONCAT(x.person_code,' · ',s.supplier_name) subtitle,
        x.status,'/resources/persons' route,x.updated_at,x.organization_id,NULL owner_id
        FROM res_supplier_person x JOIN sup_supplier s ON s.id=x.supplier_id AND s.tenant_id=x.tenant_id
        WHERE x.tenant_id=#{tenantId} AND (x.person_name LIKE #{keyword} ESCAPE '=' OR x.person_code LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')
        <choose><when test="scopeType == 'TENANT_ALL'"></when>
        <when test="scopeType == 'ORGANIZATION_SET'"> AND x.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when>
        <when test="scopeType == 'PROJECT_SET'"> AND x.project_id IN <foreach collection='projectIds' item='p' open='(' separator=',' close=')'>#{p}</foreach></when>
        <when test="scopeType == 'CREATED'"> AND x.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>
        <if test='statuses != null and !statuses.isEmpty()'> AND x.status IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if>
        <if test='from != null'> AND x.updated_at &gt;= #{from}</if><if test='to != null'> AND x.updated_at &lt;= #{to}</if>
        ORDER BY x.updated_at DESC,x.id DESC LIMIT #{limit}</script>
        """)
    List<SearchModels.SearchRow> persons(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,java.util.Set<Long> projectIds,long actorId);
    @Select("""
        <script>SELECT x.id,'ASSET' entity_type,x.asset_name title,CONCAT(x.asset_code,' · ',s.supplier_name) subtitle,
        x.status,'/resources/assets' route,x.updated_at,x.organization_id,NULL owner_id
        FROM res_supplier_asset x JOIN sup_supplier s ON s.id=x.supplier_id AND s.tenant_id=x.tenant_id
        WHERE x.tenant_id=#{tenantId} AND (x.asset_name LIKE #{keyword} ESCAPE '=' OR x.asset_code LIKE #{keyword} ESCAPE '=' OR x.plate_no LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')
        <choose><when test="scopeType == 'TENANT_ALL'"></when>
        <when test="scopeType == 'ORGANIZATION_SET'"> AND x.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when>
        <when test="scopeType == 'PROJECT_SET'"> AND x.project_id IN <foreach collection='projectIds' item='p' open='(' separator=',' close=')'>#{p}</foreach></when>
        <when test="scopeType == 'CREATED'"> AND x.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>
        <if test='statuses != null and !statuses.isEmpty()'> AND x.status IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if>
        <if test='from != null'> AND x.updated_at &gt;= #{from}</if><if test='to != null'> AND x.updated_at &lt;= #{to}</if>
        ORDER BY x.updated_at DESC,x.id DESC LIMIT #{limit}</script>
        """)
    List<SearchModels.SearchRow> assets(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,java.util.Set<Long> projectIds,long actorId);
    String ISSUE_SCOPE = "<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND x.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'PROJECT_SET'\"> AND x.project_id IN <foreach collection='projectIds' item='p' open='(' separator=',' close=')'>#{p}</foreach></when><when test=\"scopeType == 'OWNED'\"> AND x.responsible_user_id=#{actorId}</when><when test=\"scopeType == 'CREATED'\"> AND x.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>";
    String ISSUE_FILTER = "<if test='statuses != null and !statuses.isEmpty()'> AND x.status IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if><if test='from != null'> AND x.updated_at &gt;= #{from}</if><if test='to != null'> AND x.updated_at &lt;= #{to}</if>";
    @Select("<script>SELECT x.id,'SAFETY_ISSUE' entity_type,x.title,CONCAT(x.issue_no,' · ',s.supplier_name) subtitle,x.status,'/safety/issues' route,x.updated_at,x.organization_id,x.responsible_user_id owner_id FROM saf_issue x JOIN sup_supplier s ON s.id=x.supplier_id AND s.tenant_id=x.tenant_id WHERE x.tenant_id=#{tenantId} AND (x.issue_no LIKE #{keyword} ESCAPE '=' OR x.title LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')" + ISSUE_SCOPE + ISSUE_FILTER + " ORDER BY x.updated_at DESC,x.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> safetyIssues(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,java.util.Set<Long> projectIds,long actorId);
    @Select("<script>SELECT x.id,'QUALITY_NCR' entity_type,x.title,CONCAT(x.ncr_no,' · ',s.supplier_name) subtitle,x.status,'/quality/nonconformances' route,x.updated_at,x.organization_id,x.responsible_user_id owner_id FROM qua_nonconformance x JOIN sup_supplier s ON s.id=x.supplier_id AND s.tenant_id=x.tenant_id WHERE x.tenant_id=#{tenantId} AND (x.ncr_no LIKE #{keyword} ESCAPE '=' OR x.title LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')" + ISSUE_SCOPE + ISSUE_FILTER + " ORDER BY x.updated_at DESC,x.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> qualityNcrs(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,java.util.Set<Long> projectIds,long actorId);
    @Select("<script>SELECT e.id,'PERFORMANCE_EVALUATION' entity_type,e.supplier_name title,CONCAT(e.supplier_code,' · ',DATE_FORMAT(e.period_start,'%Y-%m-%d'),' ~ ',DATE_FORMAT(e.period_end,'%Y-%m-%d')) subtitle,e.status,'/performance/evaluations' route,e.updated_at,e.organization_id,e.created_by owner_id FROM per_supplier_evaluation e WHERE e.tenant_id=#{tenantId} AND (e.supplier_name LIKE #{keyword} ESCAPE '=' OR e.supplier_code LIKE #{keyword} ESCAPE '=')<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND e.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'OWNED' or scopeType == 'CREATED'\"> AND e.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose><if test='statuses != null and !statuses.isEmpty()'> AND e.status IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if><if test='from != null'> AND e.updated_at &gt;= #{from}</if><if test='to != null'> AND e.updated_at &lt;= #{to}</if> ORDER BY e.updated_at DESC,e.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> performanceEvaluations(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT a.id,'SITE_ATTENDANCE' entity_type,p.person_name title,CONCAT(p.person_code,' · ',a.site_name) subtitle,CASE WHEN a.check_out_at IS NULL THEN 'OPEN' ELSE 'CLOSED' END status,'/safety/attendance' route,a.updated_at,a.organization_id,a.created_by owner_id FROM saf_site_attendance a JOIN res_supplier_person p ON p.id=a.person_id AND p.tenant_id=a.tenant_id JOIN sup_supplier s ON s.id=a.supplier_id AND s.tenant_id=a.tenant_id WHERE a.tenant_id=#{tenantId} AND (p.person_name LIKE #{keyword} ESCAPE '=' OR p.person_code LIKE #{keyword} ESCAPE '=' OR a.site_name LIKE #{keyword} ESCAPE '=' OR s.supplier_name LIKE #{keyword} ESCAPE '=')<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND a.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'PROJECT_SET'\"> AND a.project_id IN <foreach collection='projectIds' item='p' open='(' separator=',' close=')'>#{p}</foreach></when><when test=\"scopeType == 'CREATED'\"> AND a.created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose><if test='statuses != null and !statuses.isEmpty()'> AND (CASE WHEN a.check_out_at IS NULL THEN 'OPEN' ELSE 'CLOSED' END) IN <foreach collection='statuses' item='v' open='(' separator=',' close=')'>#{v}</foreach></if><if test='from != null'> AND a.updated_at &gt;= #{from}</if><if test='to != null'> AND a.updated_at &lt;= #{to}</if> ORDER BY a.updated_at DESC,a.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> siteAttendances(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,java.util.Set<Long> projectIds,long actorId);
    @Select("SELECT id,search_name,query_json,is_default default_search,version,updated_at FROM src_saved_search WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} ORDER BY is_default DESC,updated_at DESC,id DESC")List<SearchModels.SavedRow> saved(long tenantId,long ownerId);
    @Select("SELECT id,search_name,query_json,is_default default_search,version,updated_at FROM src_saved_search WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} AND id=#{id}")SearchModels.SavedRow savedOne(long tenantId,long ownerId,long id);
    @Insert("INSERT INTO src_saved_search(id,tenant_id,owner_id,search_name,query_json,is_default) VALUES(#{id},#{tenantId},#{ownerId},#{name},CAST(#{query} AS JSON),#{defaultSearch})")int insertSaved(long tenantId,long ownerId,long id,String name,String query,boolean defaultSearch);
    @Update("UPDATE src_saved_search SET search_name=#{name},query_json=CAST(#{query} AS JSON),is_default=#{defaultSearch},version=version+1 WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} AND id=#{id} AND version=#{version}")int updateSaved(long tenantId,long ownerId,long id,String name,String query,boolean defaultSearch,int version);
    @Update("UPDATE src_saved_search SET is_default=0,version=version+1 WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} AND is_default=1 AND id!=#{exceptId}")int clearDefault(long tenantId,long ownerId,long exceptId);
    @Delete("DELETE FROM src_saved_search WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} AND id=#{id} AND version=#{version}")int deleteSaved(long tenantId,long ownerId,long id,int version);
}
