package io.github.turbopro.ism.integration.search;

import io.github.turbopro.ism.common.infrastructure.tenant.TenantScopedMapper;
import org.apache.ibatis.annotations.*;
import java.time.LocalDateTime;
import java.util.List;

@Mapper
public interface SearchMapper extends TenantScopedMapper {
    String FILTER="""
      <if test='statuses != null and !statuses.isEmpty()'> AND status IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if>
      <if test='from != null'> AND updated_at &gt;= #{from}</if><if test='to != null'> AND updated_at &lt;= #{to}</if>
      """;
    @Select("<script>SELECT u.id,'USER' entity_type,u.display_name title,u.username subtitle,u.status,CONCAT('/system/users/',u.id) route,u.updated_at,uo.organization_id,NULL owner_id FROM iam_user u LEFT JOIN iam_user_organization uo ON uo.tenant_id=u.tenant_id AND uo.user_id=u.id AND uo.is_primary=1 WHERE u.tenant_id=#{tenantId} AND u.deleted=0 AND (u.display_name LIKE #{keyword} ESCAPE '=' OR u.username LIKE #{keyword} ESCAPE '=')<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND EXISTS(SELECT 1 FROM iam_user_organization permitted_uo WHERE permitted_uo.tenant_id=u.tenant_id AND permitted_uo.user_id=u.id AND permitted_uo.organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach>)</when><otherwise> AND 1=0</otherwise></choose><if test='statuses != null and !statuses.isEmpty()'> AND u.status IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if><if test='from != null'> AND u.updated_at &gt;= #{from}</if><if test='to != null'> AND u.updated_at &lt;= #{to}</if> ORDER BY u.updated_at DESC,u.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> users(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT id,'ORGANIZATION' entity_type,organization_name title,CONCAT(organization_code,' · ',organization_type) subtitle,status,CONCAT('/system/organizations/',id) route,updated_at,id organization_id,NULL owner_id FROM iam_organization WHERE tenant_id=#{tenantId} AND (organization_name LIKE #{keyword} ESCAPE '=' OR organization_code LIKE #{keyword} ESCAPE '=')<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><otherwise> AND 1=0</otherwise></choose>"+FILTER+" ORDER BY updated_at DESC,id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> organizations(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT id,'FILE' entity_type,original_name title,content_type subtitle,status,CONCAT('/resources/files/',id) route,created_at updated_at,NULL organization_id,owner_id FROM res_file_object WHERE tenant_id=#{tenantId} AND original_name LIKE #{keyword} ESCAPE '='<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'OWNED' or scopeType == 'CREATED'\"> AND owner_id=#{actorId}</when><otherwise> AND 1=0</otherwise></choose><if test='statuses != null and !statuses.isEmpty()'> AND status IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if><if test='from != null'> AND created_at &gt;= #{from}</if><if test='to != null'> AND created_at &lt;= #{to}</if> ORDER BY created_at DESC,id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> files(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit,String scopeType,java.util.Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT id,'PRINT_TEMPLATE' entity_type,template_name title,CONCAT(template_code,' · ',business_type) subtitle,status,CONCAT('/resources/print-templates/',id) route,updated_at,NULL organization_id,NULL owner_id FROM prt_template WHERE tenant_id=#{tenantId} AND (template_name LIKE #{keyword} ESCAPE '=' OR template_code LIKE #{keyword} ESCAPE '=' OR business_type LIKE #{keyword} ESCAPE '=')"+FILTER+" ORDER BY updated_at DESC,id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> printTemplates(long tenantId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit);
    @Select("<script>SELECT i.id,'MESSAGE' entity_type,d.title title,d.business_type subtitle,CASE WHEN i.read_at IS NULL THEN 'UNREAD' ELSE 'READ' END status,CONCAT('/messages/inbox/',i.id) route,i.created_at updated_at,NULL organization_id,i.recipient_id owner_id FROM msg_inbox i JOIN msg_delivery d ON d.id=i.delivery_id AND d.tenant_id=i.tenant_id WHERE i.tenant_id=#{tenantId} AND i.recipient_id=#{userId} AND (d.title LIKE #{keyword} ESCAPE '=' OR d.content LIKE #{keyword} ESCAPE '=')<if test='statuses != null and !statuses.isEmpty()'> AND (CASE WHEN i.read_at IS NULL THEN 'UNREAD' ELSE 'READ' END) IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if><if test='from != null'> AND i.created_at &gt;= #{from}</if><if test='to != null'> AND i.created_at &lt;= #{to}</if> ORDER BY i.created_at DESC,i.id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> messages(long tenantId,long userId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit);
    @Select("<script>SELECT id,'TASK' entity_type,task_no title,CONCAT(task_type,COALESCE(CONCAT(' · ',current_stage),'')) subtitle,status,CONCAT('/resources/tasks/',id) route,created_at updated_at,NULL organization_id,requester_id owner_id FROM ops_async_task WHERE tenant_id=#{tenantId} AND requester_id=#{userId} AND (task_no LIKE #{keyword} ESCAPE '=' OR task_type LIKE #{keyword} ESCAPE '=' OR current_stage LIKE #{keyword} ESCAPE '=')<if test='statuses != null and !statuses.isEmpty()'> AND status IN <foreach collection='statuses' item='s' open='(' separator=',' close=')'>#{s}</foreach></if><if test='from != null'> AND created_at &gt;= #{from}</if><if test='to != null'> AND created_at &lt;= #{to}</if> ORDER BY created_at DESC,id DESC LIMIT #{limit}</script>")
    List<SearchModels.SearchRow> tasks(long tenantId,long userId,String keyword,java.util.Set<String> statuses,LocalDateTime from,LocalDateTime to,int limit);
    @Select("SELECT id,search_name,query_json,is_default default_search,version,updated_at FROM src_saved_search WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} ORDER BY is_default DESC,updated_at DESC,id DESC")List<SearchModels.SavedRow> saved(long tenantId,long ownerId);
    @Select("SELECT id,search_name,query_json,is_default default_search,version,updated_at FROM src_saved_search WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} AND id=#{id}")SearchModels.SavedRow savedOne(long tenantId,long ownerId,long id);
    @Insert("INSERT INTO src_saved_search(id,tenant_id,owner_id,search_name,query_json,is_default) VALUES(#{id},#{tenantId},#{ownerId},#{name},CAST(#{query} AS JSON),#{defaultSearch})")int insertSaved(long tenantId,long ownerId,long id,String name,String query,boolean defaultSearch);
    @Update("UPDATE src_saved_search SET search_name=#{name},query_json=CAST(#{query} AS JSON),is_default=#{defaultSearch},version=version+1 WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} AND id=#{id} AND version=#{version}")int updateSaved(long tenantId,long ownerId,long id,String name,String query,boolean defaultSearch,int version);
    @Update("UPDATE src_saved_search SET is_default=0,version=version+1 WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} AND is_default=1 AND id!=#{exceptId}")int clearDefault(long tenantId,long ownerId,long exceptId);
    @Delete("DELETE FROM src_saved_search WHERE tenant_id=#{tenantId} AND owner_id=#{ownerId} AND id=#{id} AND version=#{version}")int deleteSaved(long tenantId,long ownerId,long id,int version);
}
