package io.github.turbopro.ism.supplier;

import io.github.turbopro.ism.common.infrastructure.tenant.TenantScopedMapper;
import org.apache.ibatis.annotations.*;
import java.util.*;

@Mapper
public interface SupplierMapper extends TenantScopedMapper {
    @Select("SELECT id,organization_id,supplier_code,supplier_name,short_name,unified_social_credit_code,supplier_type,industry,country_code,province,city,address,legal_representative,registered_capital,currency,established_date,website,source,status,risk_level,remark,created_by,version,created_at,updated_at FROM sup_supplier WHERE tenant_id=#{tenantId} AND id=#{id} AND deleted=0 FOR UPDATE")
    SupplierModels.SupplierRow findForNewBusiness(long tenantId,long id);
    @Select("SELECT status FROM sup_supplier WHERE tenant_id=#{tenantId} AND id=#{id} AND deleted=0 FOR UPDATE")
    String currentStatusForExit(long tenantId,long id);
    String SCOPE="<choose><when test=\"scopeType == 'TENANT_ALL'\"></when><when test=\"scopeType == 'ORGANIZATION_SET'\"> AND organization_id IN <foreach collection='organizationIds' item='o' open='(' separator=',' close=')'>#{o}</foreach></when><when test=\"scopeType == 'CREATED'\"> AND created_by=#{actorId}</when><otherwise> AND 1=0</otherwise></choose>";
    String FILTER="<if test='keyword != null and keyword != &quot;&quot;'> AND (supplier_code LIKE #{keyword} ESCAPE '=' OR supplier_name LIKE #{keyword} ESCAPE '=' OR unified_social_credit_code LIKE #{keyword} ESCAPE '=')</if><if test='status != null and status != &quot;&quot;'> AND status=#{status}</if><if test='organizationId != null'> AND organization_id=#{organizationId}</if>";
    @Select("<script>SELECT COUNT(*) FROM sup_supplier WHERE tenant_id=#{tenantId} AND deleted=0"+SCOPE+FILTER+"</script>")
    long count(long tenantId,String keyword,String status,Long organizationId,String scopeType,Set<Long> organizationIds,long actorId);
    @Select("<script>SELECT s.id,s.organization_id,s.supplier_code,s.supplier_name,s.short_name,s.unified_social_credit_code,s.supplier_type,s.status,s.risk_level,EXISTS(SELECT 1 FROM sup_blacklist_case b WHERE b.tenant_id=s.tenant_id AND b.supplier_id=s.id AND b.status='APPROVED' AND b.restriction_type='WATCH') observed,s.version,s.updated_at FROM sup_supplier s WHERE tenant_id=#{tenantId} AND deleted=0"+SCOPE+FILTER+" ORDER BY updated_at DESC,id DESC LIMIT #{size} OFFSET #{offset}</script>")
    List<SupplierModels.SupplierSummary> list(long tenantId,String keyword,String status,Long organizationId,String scopeType,Set<Long> organizationIds,long actorId,int offset,int size);
    @Select("SELECT id,organization_id,supplier_code,supplier_name,short_name,unified_social_credit_code,supplier_type,industry,country_code,province,city,address,legal_representative,registered_capital,currency,established_date,website,source,status,risk_level,remark,created_by,version,created_at,updated_at FROM sup_supplier WHERE tenant_id=#{tenantId} AND id=#{id} AND deleted=0")
    SupplierModels.SupplierRow find(long tenantId,long id);
    @Select("SELECT id,contact_name,position_name,mobile,telephone,email,is_primary `primary`,sort_order FROM sup_supplier_contact WHERE tenant_id=#{tenantId} AND supplier_id=#{supplierId} ORDER BY is_primary DESC,sort_order,id")
    List<SupplierModels.ContactRow> contacts(long tenantId,long supplierId);
    @Select("SELECT COUNT(*) FROM iam_organization WHERE tenant_id=#{tenantId} AND id=#{organizationId} AND status='ACTIVE'") int organizationExists(long tenantId,long organizationId);
    @Insert("INSERT INTO sup_supplier(id,tenant_id,organization_id,supplier_code,supplier_name,short_name,unified_social_credit_code,supplier_type,industry,country_code,province,city,address,legal_representative,registered_capital,currency,established_date,website,risk_level,remark,created_by,updated_by) VALUES(#{id},#{tenantId},#{organizationId},#{code},#{name},#{shortName},NULLIF(#{creditCode},''),#{type},#{industry},#{countryCode},#{province},#{city},#{address},#{legalRepresentative},#{registeredCapital},#{currency},#{establishedDate},#{website},#{riskLevel},#{remark},#{actorId},#{actorId})")
    int insert(long id,long tenantId,long actorId,long organizationId,String code,String name,String shortName,String creditCode,String type,String industry,String countryCode,String province,String city,String address,String legalRepresentative,java.math.BigDecimal registeredCapital,String currency,java.time.LocalDate establishedDate,String website,String riskLevel,String remark);
    @Update("UPDATE sup_supplier SET organization_id=#{organizationId},supplier_name=#{name},short_name=#{shortName},unified_social_credit_code=NULLIF(#{creditCode},''),supplier_type=#{type},industry=#{industry},country_code=#{countryCode},province=#{province},city=#{city},address=#{address},legal_representative=#{legalRepresentative},registered_capital=#{registeredCapital},currency=#{currency},established_date=#{establishedDate},website=#{website},risk_level=#{riskLevel},remark=#{remark},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND deleted=0 AND status IN ('DRAFT','ACTIVE','SUSPENDED') AND version=#{version}")
    int update(long tenantId,long actorId,long id,long organizationId,String name,String shortName,String creditCode,String type,String industry,String countryCode,String province,String city,String address,String legalRepresentative,java.math.BigDecimal registeredCapital,String currency,java.time.LocalDate establishedDate,String website,String riskLevel,String remark,int version);
    @Insert("INSERT INTO sup_supplier_contact(id,tenant_id,supplier_id,contact_name,position_name,mobile,telephone,email,is_primary,sort_order) VALUES(#{id},#{tenantId},#{supplierId},#{name},#{position},#{mobile},#{telephone},#{email},#{primary},#{sortOrder})") int insertContact(long id,long tenantId,long supplierId,String name,String position,String mobile,String telephone,String email,boolean primary,int sortOrder);
    @Delete("DELETE FROM sup_supplier_contact WHERE tenant_id=#{tenantId} AND supplier_id=#{supplierId}") int deleteContacts(long tenantId,long supplierId);
    @Update("UPDATE sup_supplier SET status=#{status},updated_by=#{actorId},version=version+1 WHERE tenant_id=#{tenantId} AND id=#{id} AND deleted=0 AND version=#{version}") int changeStatus(long tenantId,long actorId,long id,String status,String reason,int version);
}
