package io.github.turbopro.ism.supplier;

import io.github.turbopro.ism.common.api.error.*;
import io.github.turbopro.ism.common.infrastructure.authorization.*;
import io.github.turbopro.ism.common.infrastructure.tenant.TenantContext;
import io.github.turbopro.ism.operation.*;
import org.springframework.dao.DuplicateKeyException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.util.*;

@Service
public class SupplierService {
    private final SupplierMapper mapper;private final OperationIdGenerator ids;private final AuditService audit;
    public SupplierService(SupplierMapper mapper,OperationIdGenerator ids,AuditService audit){this.mapper=mapper;this.ids=ids;this.audit=audit;}
    public SupplierModels.SupplierPage list(String keyword,String status,Long organizationId,int page,int size){var i=TenantContext.require();var scope=scope();String like=keyword==null||keyword.isBlank()?null:"%"+keyword.trim().replace("=","==").replace("%","=%").replace("_","=_")+"%";String state=status==null||status.isBlank()?null:parseStatus(status).name();int offset=Math.multiplyExact(page,size);long total=mapper.count(i.tenantId(),like,state,organizationId,scope.type().name(),scope.organizationIds(),i.actorId());return new SupplierModels.SupplierPage(total,page,size,mapper.list(i.tenantId(),like,state,organizationId,scope.type().name(),scope.organizationIds(),i.actorId(),offset,size));}
    public SupplierModels.SupplierView get(long id){return view(requireAllowed(id));}
    @Transactional public SupplierModels.SupplierView create(SupplierModels.SaveSupplier command){if(command.version()!=0)throw validation("新建供应商的 version 必须为 0");validateContacts(command.contacts());var i=TenantContext.require();long org=parseId(command.organizationId());requireOrganization(org);requireScope(org,i.actorId());long id=ids.nextId();try{mapper.insert(id,i.tenantId(),i.actorId(),org,command.code(),command.name().trim(),blank(command.shortName()),blank(command.unifiedSocialCreditCode()),command.type().name(),blank(command.industry()),command.countryCode(),blank(command.province()),blank(command.city()),blank(command.address()),blank(command.legalRepresentative()),command.registeredCapital(),blank(command.currency()),command.establishedDate(),blank(command.website()),command.riskLevel().name(),blank(command.remark()));replaceContacts(i.tenantId(),id,command.contacts());}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"供应商编码或统一社会信用代码已存在");}audit.append(new AuditService.AuditCommand("SUPPLIER_CREATE","SUPPLIER",id,null,Map.of(),Map.of("code",command.code(),"name",command.name()),null,null));return view(mapper.find(i.tenantId(),id));}
    @Transactional public SupplierModels.SupplierView update(long id,SupplierModels.SaveSupplier command){validateContacts(command.contacts());var before=requireAllowed(id);if(!before.supplierCode().equals(command.code()))throw validation("供应商编码不可修改");var i=TenantContext.require();long org=parseId(command.organizationId());requireOrganization(org);requireScope(org,i.actorId());try{if(mapper.update(i.tenantId(),i.actorId(),id,org,command.name().trim(),blank(command.shortName()),blank(command.unifiedSocialCreditCode()),command.type().name(),blank(command.industry()),command.countryCode(),blank(command.province()),blank(command.city()),blank(command.address()),blank(command.legalRepresentative()),command.registeredCapital(),blank(command.currency()),command.establishedDate(),blank(command.website()),command.riskLevel().name(),blank(command.remark()),command.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);mapper.deleteContacts(i.tenantId(),id);replaceContacts(i.tenantId(),id,command.contacts());}catch(DuplicateKeyException e){throw new ApiException(CommonErrorCode.CONFLICT,"统一社会信用代码已存在");}audit.append(new AuditService.AuditCommand("SUPPLIER_UPDATE","SUPPLIER",id,null,Map.of("name",before.supplierName(),"status",before.status()),Map.of("name",command.name(),"organizationId",org),null,null));return view(mapper.find(i.tenantId(),id));}
    @Transactional public SupplierModels.SupplierView changeStatus(long id,SupplierModels.ChangeStatus command){var before=requireAllowed(id);var from=SupplierModels.Status.valueOf(before.status());if(!allowed(from,command.status()))throw validation("不允许从 "+from+" 变更为 "+command.status());if((command.status()==SupplierModels.Status.SUSPENDED||command.status()==SupplierModels.Status.EXITED)&&(command.reason()==null||command.reason().isBlank()))throw validation("停用或退出必须填写原因");var i=TenantContext.require();if(mapper.changeStatus(i.tenantId(),i.actorId(),id,command.status().name(),blank(command.reason()),command.version())!=1)throw new ApiException(CommonErrorCode.CONFLICT);audit.append(new AuditService.AuditCommand("SUPPLIER_STATUS_CHANGE","SUPPLIER",id,null,Map.of("status",from),Map.of("status",command.status(),"reason",Objects.toString(command.reason(),"")),null,null));return view(mapper.find(i.tenantId(),id));}
    private SupplierModels.SupplierRow requireAllowed(long id){var i=TenantContext.require();var row=mapper.find(i.tenantId(),id);if(row==null||!scope().allows(new DataTarget(row.organizationId(),null,row.createdBy(),row.createdBy()),i.actorId()))throw new ApiException(CommonErrorCode.NOT_FOUND);return row;}
    private DataScope scope(){return AuthorizationContext.require().dataScope("supplier:master");}
    private void requireScope(long org,long actor){if(!scope().allows(new DataTarget(org,null,actor,actor),actor))throw new ApiException(CommonErrorCode.FORBIDDEN);}
    private void requireOrganization(long org){if(mapper.organizationExists(TenantContext.require().tenantId(),org)!=1)throw validation("归属组织不存在或已停用");}
    private void replaceContacts(long tenant,long supplier,List<SupplierModels.ContactCommand> contacts){for(var c:contacts)mapper.insertContact(ids.nextId(),tenant,supplier,c.name().trim(),blank(c.position()),blank(c.mobile()),blank(c.telephone()),blank(c.email()),c.primary(),c.sortOrder());}
    private void validateContacts(List<SupplierModels.ContactCommand> contacts){if(contacts.stream().filter(SupplierModels.ContactCommand::primary).count()>1)throw validation("只能设置一个主要联系人");for(var c:contacts)if((c.mobile()==null||c.mobile().isBlank())&&(c.telephone()==null||c.telephone().isBlank())&&(c.email()==null||c.email().isBlank()))throw validation("联系人至少填写手机、电话或邮箱之一");}
    private boolean allowed(SupplierModels.Status from,SupplierModels.Status to){return from!=to&&switch(from){case DRAFT->to==SupplierModels.Status.ACTIVE||to==SupplierModels.Status.EXITED;case ACTIVE->to==SupplierModels.Status.SUSPENDED||to==SupplierModels.Status.EXITED;case SUSPENDED->to==SupplierModels.Status.ACTIVE||to==SupplierModels.Status.EXITED;case EXITED->false;};}
    private SupplierModels.Status parseStatus(String value){try{return SupplierModels.Status.valueOf(value);}catch(Exception e){throw validation("供应商状态无效");}}
    private long parseId(String value){try{return Long.parseLong(value);}catch(Exception e){throw validation("组织 ID 无效");}}
    private String blank(String value){return value==null||value.isBlank()?null:value.trim();}
    private ApiException validation(String message){return new ApiException(CommonErrorCode.VALIDATION_FAILED,message);}
    private SupplierModels.SupplierView view(SupplierModels.SupplierRow r){var i=TenantContext.require();return new SupplierModels.SupplierView(Long.toString(r.id()),Long.toString(r.organizationId()),r.supplierCode(),r.supplierName(),r.shortName(),r.unifiedSocialCreditCode(),SupplierModels.Type.valueOf(r.supplierType()),r.industry(),r.countryCode(),r.province(),r.city(),r.address(),r.legalRepresentative(),r.registeredCapital(),r.currency(),r.establishedDate(),r.website(),r.source(),SupplierModels.Status.valueOf(r.status()),SupplierModels.RiskLevel.valueOf(r.riskLevel()),r.remark(),r.version(),r.createdAt(),r.updatedAt(),mapper.contacts(i.tenantId(),r.id()).stream().map(c->new SupplierModels.ContactView(Long.toString(c.id()),c.contactName(),c.positionName(),c.mobile(),c.telephone(),c.email(),c.primary(),c.sortOrder())).toList());}
}
